### ISSUE TITLE
-==New Features collection==-

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#1028]
In case somebody want to develop one of this feature, please take and reopen one of them.
#302 - Refactor home page (phase 2)
#303 - Crash report collection
#359 - Custom autocomplete ComboBox
#386 - OFX Import
#396 - automatic assignment
#528 - Pagination support for all item list
#628 - New feature: insert new operations directly
#637 - Remove Historic Items without disturbing Current Balances
#707 - Pre-loaded data translation
#735 - Backup location
#842 - User agent refine
#847 - Expanded Assets section on Home screen, similar to Stocks
#893 - Make secure connection for web server
#910 - Notes in split categories
#925 - Compound interest in assets
#926 - Auto update current market values for goods in assets
#952 - Migrate/import from Quicken

**Comment by J316** [comment]
In case somebody want to develop one of this feature, please take and reopen one of them.
#1025 - Auto linking of transactions cntinuation of #560 
#628 - New feature: insert new operations directly
#302 - Refactor home page (phase 2)
#303 - Crash report collection
#735 - Backup location
#626 - New feature: be able to remove unused reports
#791 - Feature Request - Charts for monthly budget performance
#952 - Migrate/import from Quicken
#925 - Compound interest in assets
#910 - Notes in split categories
#847 - Expanded Assets section on Home screen, similar to Stocks
#742 - "Budget Performance Summary" - Enhancement Needed
#926 - Auto update current market values for goods in assets
#842 - User agent refine
#893 - Make secure connection for web server
#637 - Remove Historic Items without disturbing Current Balances
#713 - YQL
#396 - automatic assignment
#386 - OFX Import
#359 - Custom autocomplete ComboBox
#629 - New feature: trend/evolution of the account should be a standard report
#707 - Pre-loaded data translation
#528 - Pagination support for all item list
#478 - User interface scaling too tiny on high DPI devices

FTFY. I can't see any reason for closing everything though. Anyway you can update your post and delete mine.

**Comment by vomikan** [comment]
@J316  thank you for update. I'll update case nàmes.

**Comment by siena123** [comment]
I have already started working on some changes to reports in general that include some of the report items noted above. I will work on the others as well while I am doing them. I will be submitting just small framework changes to start with working toward the end goal of overall improvement of the reports.

#626 - New feature: be able to remove unused reports
#791 - Feature Request - Charts for monthly budget performance
#742 - "Budget Performance Summary" - Enhancement Needed
#629 - New feature: trend/evolution of the account should be a standard report

**Comment by vomikan** [comment]
I suggest next tecnology of working on cases:
- Any new feature should be registered in github firstly;
- Assign yourself in case you will do some coding for this request;
- Any PR should contains case (ticket) number. For example:
~~~~~~
feat(#742): updates to budget reports 
~~~~~~

**Comment by vomikan** [comment]
Should we keep open cases that are several years old?
Is it possible to close them?
It is better to live with current problems, which abound.

**Comment by luisdev** [comment]
> Should we keep open cases that are several years old? Is it possible to close them? It is better to live with current problems, which abound.

I think they should remain open, so that we can see that they are still "un-fixed" and sitting in a "backlog queue".

**Comment by tactilis** [comment]
> I think they should remain open, so that we can see that they are still "un-fixed" and sitting in a "backlog queue".

I partially agree with @vomikan (i.e. close) and partially with @luisdev (keep open) because I don't think it is as simple as just closing them all or just leaving them all open:

- Some will have been completely overtaken by events, i.e. new capabilities in MMEX have provided a way to solve the problem raised/feature requested. These can be closed with a comment saying why.

- Some will have been partially overtaken by events but still contain some useful ideas that could be implemented in the future. These ideally should have the useful idea summarised in a new issue and the old issue closed.

- Some will not have been addressed at all and still be fully relevant. These can be retained, perhaps with a new comment saying that they were re-assessed as still being applicable.

- Some will not have addressed but are not really relevant now. These can be marked `Won't fix` and be closed.

Obviously, it's going to take a fair bit of work to go through them (sort by oldest issues first) and tackle them one by one.

**Comment by vomikan** [comment]
> Obviously, it's going to take a fair bit of work to go through them (sort by oldest issues first) and tackle them one by one.

That's the point. We do not have such an opportunity and desire.
If someone finds it necessary to register the bug (feature) again, this will be his constructive contribution.

And so, personally, I am pressed by such a large number of open cases. It takes a lot of time to read the headlines alone, not to mention correcting them.

**Comment by tactilis** [comment]
>> Obviously, it's going to take a fair bit of work to go through them (sort by oldest issues first) and tackle them one by one.

> That's the point. We do not have such an opportunity and desire.

OK, below is a start, beginning with the oldest issues.

If you could CLOSE (or KEEP OPEN) and paste my REASON as a comment, then I will keep working through a few more each day. Even looking at _just_ 2 per day (no more than 10 per week), we'll have been through them all in 8 months.

However, it's OK with me if you don't want to do this, 
 

---

#301 Implement Object-relational mapping to SQLite tables
Opened Dec 2014
enhancement, on hold

CLOSE: wontfix

REASON: ORM hasn't been implemented in the past 9 years and MMEX development continues OK without it.

---

#305 Automatically fallback to readonly mode if the program has no write permission
Opened Dec 2014
enhancement

CLOSE: wontfix

REASON: Hasn't been implemented in the past 9 years and we do have not received multiple requests for a readonly mode.

---

#343 Transfers not ex-/imported to/from CSV
Opened Jan 2015
on hold

KEEP OPEN

REASON: There is a possibility with the work that @n_stein has been doing that Account matching could be added as a subset of Payee matching, which would allow a transfers to be identified during Import.

---

#529 Asset Allocation
Opened Jul 2015
feature

KEEP OPEN AND RE-ASSESS

REASON: NEEDS REVIEWING BY SOMEONE ELSE as I don't have any expertise in this area and cannot judge how important this feature is.

Apparently the work was done for the Android app but not brought into MMEX desktop app.

---

#709 SPLITTRANSACTIONS: add ACCOUNTID and NOTES columns
Opened Feb 2016
enhancement

CLOSE: fixed

REASON: Notes have now been added to Split Transactions.

---

#1103 Crosslink between transactions
Opened Mar 2017
feature

KEEP OPEN

REASON: @vomikan's comment: "I think in case if referenced transaction number, for example #1103, present in notes it should be way to reach it easy." is still valid.

---

#1151 Wrong format of AFN (Afghan afghani) - problem with chars from right-to-left scripts
Opened May 2017
i18n

CLOSE: Wontfix

REASON: This issue was raised in 2017 by a developer. Address the problem when/if a real world user raises a new issue about this.

---

#1196 Foreign Calenders
Opened May 2017
feature, i18n, on hold 

CLOSE: Wontfix

REASON: This issue was raised in 2017 by a developer. Address the problem when/if a real world user raises a new issue about this.

---

#1206 Store right application ID in sqlite database header
Opened Jun 2017

CLOSE: fixed

REASON: #1254 solves the problem of registering the .mmb file type on Linux and a different issue exists for Windows.

**Comment by tactilis** [comment]
@vomikan You added the REASON comments to 709 and 1196 but I think you missed closing the issues.

**Comment by tactilis** [comment]
@vomikan Here's the next batch:

---
#1216 Fullscreen menu item's checkbox not synchronized with window state
Opened Jul 2017

CLOSE: fixed

REASON: Works correctly now.

---

#1218  Multiple Recurring Transactions at once
Opened Jul 2017

CLOSE: wontfix

REASON: Original issue was just question which was answered in subsequent comments.

---

#1253  Use PackageCloud as official MMEX repo from next release
Opened Jul 2017

CLOSE: outdated

REASON: Overtaken by later events regarding MMEX repos.

---

#1255  Register filetypes for mmex at system level in Windows 
Opened Jul 2017

CLOSE: wontfix

REASON: Nice to have but not essential. Users can associate .mmb with MMEX app via file Properties.

---

#1260 Add envelope budgeting option  
Opened Jul 2017

CLOSE: wontfix

REASON: Complex feature request, overtaken by subsequent budgeting enhancements.

---

#1265  revenue forecast 
Opened Jul 2017

CLOSE: wontfix

REASON: Vague requirement. No details given. 

---
#1297  Year end rollover 
Opened Aug 2017

CLOSE: wontfix

REASON: Discussion in the issue showed little appetite (or need) for providing this feature, which is more relevant to business style accounts.

---

_And a recent one:_

#6112 MMEX transactions not importing correctly
Opened Jul 2023

CLOSE: question

REASON: OP's problem/question has been resolved.

**Comment by tactilis** [comment]
Here is the next batch:


---
#1298 Describe new features and GUI controls in manual
Opened Aug 2017

KEEP OPEN

REASON: The Help/Documentation needs a major update to cover all the new MMEX features.

---
#1314 conversion from Quicken
Opened Sep 2017

CLOSE: wontfix

REASON: Exporting as QIF or CSV from Quicken then importing into MMEX addresses most of the stated need without requiring the development of a dedicated Quicken to MMEX convertor.

---
#1325 Reconciled helper function
Opened Sep 2017

CLOSE: wontfix

REASON: There are later discussions ongoing about how MMEX might help with reconciliation (for example https://github.com/moneymanagerex/moneymanagerex/discussions/5992) and helpful advice on the forum (for example https://forum.moneymanagerex.org/viewtopic.php?p=24077#p24077)

---
#1349 Consolidate README.md and README.TXT
Opened Oct 2017

KEEP OPEN

REASON: The two readme files are still different.

Perhaps @ovari would be able to take a look at this and either consolidate the files or recommend closing this issue as wontfix.

---
#1354 Provide 'due date' for every transaction
Opened Oct 2017

CLOSE: wontfix

REASON: The OP gave little information about the requested feature and did not respond in 2022 when asked for more details about their requirement.

---
#1386 Option to exclude the account from calculating overall balance
Opened Dec 2017

CLOSE: wontfix

REASON: The OP gave no justification for why their suggested feature was needed.

---
#1396 ability to split transfer transaction
Opened Jan 2018

KEEP OPEN

REASON: There is a reasonable justification given for this enhancement and some discussion as to how it might be achieved.
