### ISSUE TITLE
Monthly Summary of Accounts crash

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#1086]
The report crashed without crash report.
- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x

[test7.zip](https://github.com/moneymanagerex/moneymanagerex/files/821127/test7.zip)

**Comment by vomikan** [comment]
Необработанное исключение по адресу 0x00000001407BE6F8 в mmex.exe: Код инcтрументирования объектов cookie стека обнаружил переполнение буфера, связанное со стеком..

**Comment by vomikan** [comment]
I can't reproduce this issue in v 1.4.0

**Comment by grabags** [comment]
This is still happening in V 1.3.3 and V 1.3.4 rc? for Windows 10 x64 portable version.
I have seen elsewhere that this may be due to Asset accounts and this would appear to be the case for me - I have two databases, one with and one without Assets - the one with crashes about 5 seconds after requesting 'Monthly Summary of Accounts'

**Comment by vomikan** [comment]
I can open the attahed DB and run the report with no problem.
mmex 1.3.4.rc.5
