### ISSUE TITLE
Multiple Recurring Transactions at once

### ISSUE THREAD

**Issue by Big-Mug** [moneymanagerex/moneymanagerex#1218]
Is it possible to select multiple recurring transactions to enter in one, rather than having to select and enter each one separately?

**Comment by colourqueen** [comment]
Either multiple transactions or all for upcoming month would be good...

**Comment by slodki** [comment]
Do you know recurring transaction can be auto entered by MMEX without manual user action when *grant automatic execute* option is selected?

**Comment by colourqueen** [comment]
Thanks yes but I like to see the end of month balance with all transaction processed up front, not as they occur during the month.

**Comment by slodki** [comment]
Cash Flow reports will give you such info for all or selected accounts.

Current MMEX flow for Recurring Transactions requires validation and confirmation step before entering any transaction to fine-tune transaction params (like exact amount - it can change in time)...

There can be new button for "Enter next occurances of selected transactions with stored default values". Mistakes cannot be easily undone because this action can modify multiple accounts and will rearrange Recurring Transactions list ordering.

**Comment by colourqueen** [comment]
OK thanks for the information. I think I was just used to posting all recurring transactions for the month having migrated from Quicken where it was available.

**Comment by vomikan** [comment]
CLOSE: wontfix

REASON: Original issue was just question which was answered in subsequent comments.
