### ISSUE TITLE
Transaction report not showing transactions when using date filter

### ISSUE THREAD

**Issue by Ribo69** [moneymanagerex/moneymanagerex#1378]
Your OS:
- [X] Windows

MMEX version:
- [X] 1.3.x

![mmex resoconto operazioni](https://user-images.githubusercontent.com/34349970/33731558-caeb025e-db83-11e7-91ff-52db4f551d4d.jpg)
![mmex resoconto operazioni_2](https://user-images.githubusercontent.com/34349970/33731610-f3a9e0c0-db83-11e7-9608-f1b7cc453187.jpg)

The result is not correct, because if I select the same voice without date, I have a lot of voices in the 2017.
![mmex resoconto operazioni_3](https://user-images.githubusercontent.com/34349970/33731713-58e25aa8-db84-11e7-914c-8c73b1676825.jpg)
![mmex resoconto operazioni_4](https://user-images.githubusercontent.com/34349970/33731727-66234fa6-db84-11e7-8956-58eb6c7e7e8d.jpg)

Someone have an idea?

Thanks

**Comment by stef145g** [comment]
Tried duplicating in English, and could not duplicate.
Possibly a language identification problem.
Could try to duplicate in a test database using English and one in Italian. Then using the latest alpha release as this problem may be fixed.

**Comment by Ribo69** [comment]
Hi Stefano, thanks for your suggest, but nothing happen, theproblem is still present. sabato, 09 dicembre 2017, 00:02AM +01:00 da Stefano  notifications@github.com :

**Comment by slodki** [comment]
Date filter works without problems in v1.4.0 (in transaction window and transaction report):

![filter1](https://user-images.githubusercontent.com/3155552/33799000-5ed305de-dd23-11e7-9cdc-2da768e15d0c.png)

![filter2](https://user-images.githubusercontent.com/3155552/33799001-636a0570-dd23-11e7-9a22-bcdeca662f2d.png)

@Ribo69: could you try to install v1.4.0 alpha to confirm it's fixed in this version?

**Comment by Ribo69** [comment]
Hello,
I confirm, in V1.4 alpha3 it's working. Thanks for all sabato, 09 dicembre 2017, 08:58PM +01:00 da slodki  notifications@github.com :
