### ISSUE TITLE
Transaction report no longer works

### ISSUE THREAD

**Issue by stantheman1** [moneymanagerex/moneymanagerex#1384]
Hi. Wonderful program, but since your last update the Transactions Report no longer works. Whatever criteria you enter, the report shows NOTHING!!

**Comment by stantheman1** [comment]
Hi. Wonderful program, but since your last update the Transactions Report no longer works.  Whatever criteria you enter, the report shows NOTHING!!

**Comment by stef145g** [comment]
Interesting that you have closed this immediately. I am assuming the report is no longer valid as I cannot replicate your initial report.

**Comment by stantheman1** [comment]
Hi Stefano
Unfortunately the transaction report manager is still not working.
Kind regards
Stanley Pearce

**Comment by stef145g** [comment]
More info please...

**Comment by stantheman1** [comment]
Hi
When you input information i. e. Car servicing from 1st January 2016 to
10th Nov 2017 nothing is found. The system produced correct relevant
entries prior to update.
Regards
Stanley Pearce

**Comment by slodki** [comment]
It's working in 1.4.0 alpha as you can see at [my screenshots](https://github.com/moneymanagerex/moneymanagerex/issues/1378#issuecomment-350501608).
Could you post your MMEX versions used before and after update (and your OS)?

**Comment by stantheman1** [comment]
Hi
My MMEX update check says I have the latest version 1.3.3
How to I obtain version 1.4 please?
Stanley Pearce


On 20 Dec 2017 20:02, "slodki" <notifications@github.com> wrote:

It's working in 1.4.0 alpha as you can see at my screenshots
<https://github.com/moneymanagerex/moneymanagerex/issues/1378#issuecomment-350501608>
.
Could you post your MMEX versions used before and after update (and your
OS)?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/moneymanagerex/moneymanagerex/issues/1384#issuecomment-353167338>,
or mute the thread

**Comment by stef145g** [comment]
This is available in the releases section of GitHub: https://github.com/moneymanagerex/moneymanagerex/releases

**Comment by stantheman1** [comment]
Stefano.
I do not understand. Firstly I use Windows 10, 64 bit.
Why does my system say that I have latest update which is 1.3.3
Secondly how do I update my program with 1.4 version.
Please answer both questions for me.
Thank you
Stanley Pearce

**Comment by stef145g** [comment]
Hi Stanley, 
When MMEX checks for updates, it refers to a file on our website that defines the latest "Release" version. This is a stable version that will not change. Initially there were some bug fix releases specified by the 3rd counter of the version number, but has basically remained static since the development of 1.4.0. 

To assist users, Alpha versions of 1.4 have been released. These include bug fixes to the 1.3.x series as well as new features that have been in development. These releases are just as valid as the release versions, except that the documentation may not be quite accurate or language files have not been updated. Think of the pre release versions as being on an insider program if we use Microsoft's Windows 10 terminology.

So If you use a release version to check for updates it looks at the Latest Release counter that is set at 1.3.3. Using the link above, and downloading and running the win64-mmex-1.4.0-ALPHA-3.exe this will install the new version. Any upgrades to the database will be automatically handled.

Alternatively you can download the .zip version where you can unpack it directly and use it. This will reinitialise MMEX because it comes with the initialisation file mmexini.db3 which is empty. Deleting this file will use the one in the systems user area. If one is not found, it will create one.

Checking for updates with the new version will give you a different version. Using the About: will give you the version you are using.

I hope this answers your questions
Stefano

**Comment by stantheman1** [comment]
Thanks Stefano.
I'll try and download as you suggest..
If any issues, I hope you won't mind me contacting you in the New Year.
Have a great holiday.
Stanley 6

**Comment by stantheman1** [comment]
Hi Stefano

Just downloaded version 1.4 and it has solved my 'transaction history'
problem.
Thanks for all your help and patience.
Kind regards
Stanley Pearce

**Comment by stantheman1** [comment]
Hi
I have another more serious problem.
When I just opened Money Manager it dies not give me the option of OPEN
LAST OPENED DATABASE - it has been greyed out!  The last time I backed up
was early November which means I cannot see my last few weeks work.  How
can I see everything up to yesterday please?
Stanley Pearce

**Comment by stantheman1** [comment]
Hi Stefano
Did you get my email below regarding the 'greyed out' problem that has
occurred over last few days?
Please respond
Stanley Pearce



On 2 Jan 2018 17:58, "Stanley Pearce" <stanley.pearce@gmail.com> wrote:

Hi
I have another more serious problem.
When I just opened Money Manager it dies not give me the option of OPEN
LAST OPENED DATABASE - it has been greyed out!  The last time I backed up
was early November which means I cannot see my last few weeks work.  How
can I see everything up to yesterday please?
Stanley Pearce

**Comment by stef145g** [comment]
Hi Stanley, Just saw this today.

It appears that your mmexini.db3 file may have a problem. Your working database should be OK, and there should also be backups of your database automatically generated. Just check the location of your database files.

Suggest that you delete or rename the mmexini.db3 file to something else such as mmexini_q.db3 and restart mmex. You should then be able to select and open your database.

Are you able to examine a database using a sql database browser program?

**Comment by stantheman1** [comment]
Hi Stefano
Thanks for info.
Regards
Stanley Pearce

On 4 Jan 2018 23:36, "Stefano" <notifications@github.com> wrote:

Hi Stanley, Just saw this today.

It appears that your mmexini.db3 file may have a problem. Your working
database should be OK, and there should also be backups of your database
automatically generated. Just check the location of your database files.

Suggest that you delete or rename the mmexini.db3 file to something else
such as mmexini_q.db3 and restart mmex. You should then be able to select
and open your database.

Are you able to examine a database using a sql database browser program?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/moneymanagerex/moneymanagerex/issues/1384#issuecomment-355430316>,
or mute the thread
