### ISSUE TITLE
cash account currency

### ISSUE THREAD

**Issue by Mak-PhD** [moneymanagerex/moneymanagerex#1385]
Hi,
I'm facing an issue working with different currencies.
Actually, I have a cash account set up in USD, while the reporting currency is EUR.
Even if the rates are updated, the total in my reporting currency (EUR) is simply equal to the one in USD, without any calculation (and the ER is not 1).

Ciao

MMEX version 1.3.3 on Windows

**Comment by lexa2** [comment]
Open up currency edit dialog and instead of trying to online-update right-click on the USD list entry and select "Edit" menu item. Check the conversion rate there, most probably it is set to "1".

As for online rate update - this functionality is broken at the moment due to Yahoo had discontinued web service that was used for this to function. Don't confuse "online rate update" with "online currency rate history" update - they are different things and are implemented independently of each other. History update is handled through ECB site web-service.

It is possible in theory to reimplement functionality that was broken due to Yahoo through ECB-provided web-service but I don't know if anyone is working on this.

**Comment by slodki** [comment]
See #1391

**Comment by lexa2** [comment]
@slodki Yep, that was my PR :-).
