### ISSUE TITLE
Option to exclude the account from calculating overall balance

### ISSUE THREAD

**Issue by bhagavan44** [moneymanagerex/moneymanagerex#1386]
Your OS:
- [x] Windows

MMEX version:
- [x] 1.3.x

It will be a good option, if we can able to exclude some of the accounts from calculating the overall balance.

**Comment by vomikan** [comment]
CLOSE: wontfix

REASON: The OP gave no justification for why their suggested feature was needed.

**Comment by luisdev** [comment]
> CLOSE: wontfix
> 
> REASON: The OP gave no justification for why their suggested feature was needed.

This could actually be a nice feature. I would use it! Why? There may be cases where you want to track an account that is not your money, so you don't want that account to reflect in your overall account balances.

For example: I look after a bank account for my terminally ill sister. I do it in MMX because it's a convenient place to do it. But I don't want the balance in that account to reflect in my overall accounts balances because the money in that account is not my money.
So, can we reopen this?

**Comment by tactilis** [comment]
@luisdev
> There may be cases where you want to track an account that is not your money, so you don't want that account to reflect in your overall account balances.
>
>For example: I look after a bank account for my terminally ill sister. I do it in MMX because it's a convenient place to do it. But I don't want the balance in that account to reflect in my overall accounts balance because the money in that account is not my money.

Just create a separate database for your sister's accounts. It keeps her finances separate from yours, so her account doesn't affect your overall accounts balance.

It's simple to switch between databases using `File | Recent Files...`

<br>

> I lent some money to a family member a long time ago. That person will never be able to repay the money so I've practically written the debt off, but I'm still keeping a record of it. But I don't want the account to reflect in my overall account balances.

This is a very niche requirement.

And if they will **_never_** be able to repay it, then money it is gone from your (i.e your wealth), so write it off and have your overall accounts in MMEX reflect the reality of the situation.


<br>

IMO, devising a UI (and all the code behind it) to achieve something that can be handled in other ways, feels to me to be more work than is worthwhile.
