### ISSUE TITLE
Deposit+Transfer/Withdrawal+Transfer transaction type at Edit Asset Transaction dialog

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1401]
Why there is ability to select Deposit+Transfer transaction type at Edit Asset Transaction dialog?

![mmex-deposit-with-transfer](https://user-images.githubusercontent.com/3155552/34653442-2f532778-f3ec-11e7-81ec-c484a1b53df9.png)

[There is also tooltip](https://github.com/moneymanagerex/moneymanagerex/blob/master/src/usertransactionpanel.cpp#L134) "Funds transfer from/to this account. Uncheck to set as Expense/Income."

Why we don't use simple 3 element list in this place?

**Comment by stef145g** [comment]
All transactions to assets from "General" accounts are indeed transfers. These transfer transaction are different to normal transfer transactions and I refer these as "foreign" transactions.

This mechanism allows these transfer transactions to be identified, and the transfer is to be considered as a deposit or a withdrawal in the normal accounts. This allows for an asset to be sold or purchased.

The transfer condition refers to both conditions because the transaction is indeed a transfer. The Transfer flag refers to the normal accounts, and identifies this transaction is to be considered as an income or expense in calculations. If the flag is selected, the withdrawal or deposit is considered as a transfer in the general accounts

The same mechanism is used for Stocks and Shares.

**Comment by stef145g** [comment]
oops... I meant to add comment, not close. Sorry.

**Comment by stef145g** [comment]
As there is no further comments I will close this issue.
