### ISSUE TITLE
Assets node not displayed at navigation tree

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1476]
There is no `Assets` node displayed if assets exist, but no asset account is created in current dev version.

How to reproduce:
1. Open `Tools`->`Assets` menu and create asset **without** asset account using `New` button
2. New asset is displayed in right panel but no Assets node in nav tree
3. Assets list can be displayed using `Tools`->`Assets` menu only
4. Open `Tools`->`Assets` menu and create asset **with** asset account using `New` button
5. Both assets are displayed in right panel and Assets node with new account in nav tree to
6. Assets list can be displayed using Assets node or `Tools`->`Assets` menu
7. Delete asset account
8. Assets node is gone, assets list can be displayed using `Tools`->`Assets` menu only

Expected behavior: Assets node should be hidden when no assets and no asset accounts are defined only. There should be `Assets` node without nodes below if assets without accounts are defined in db.

**Comment by stef145g** [comment]
Assets in the Navigation tree displays a list of assets maintained by MMEX and an individual asset therefore does not become part of the navigation tree.

With the extension of Assets to allow transfers to and from regular accounts to an asset, it may be necessary for an asset to be maintained in it's own account. Under this condition the Asset Account is created and displayed in the navigation tree. An asset can also share a common account, or associate itself to a regular account as necessary.

In my opinion this issue is invalid.

**Comment by stef145g** [comment]
After retesting the latest build, I find that my above comments do not quite reflect the actions of this issue.
My apologies.
When an asset is created in the Asset List, the Asset tag should be shown on the navigation tree.
