### ISSUE TITLE
MMEX database upgrade to version 8 failed!

### ISSUE THREAD

**Issue by MartinX3** [moneymanagerex/moneymanagerex#1632]
Your OS:
- [ ] Windows
- [ ] Mac OSX
- [X] Linux 
- [X] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [X] 1.4.x Alpha 4
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

Opened the DB file in the Android App
Then opened in 1.4.x Alpha 4

Error while opening = crash

MMEX database upgrade to version 8 failed!

Please restore DB from autocreated pre-upgrade backup and retry or contact MMEX support

SQL logic error[1]: duplicate column name: CURRENCY_TYPE

PS: I don't need a DB patch. I use a backup solution against such things. :)

**Comment by gabriele-v** [comment]
@MisterY could you check if in Android version your are upgrading correctly the DB based on https://github.com/moneymanagerex/database repository? Seems that we have some problems there..

@MartinX3 Please extract and apply attached patch
[currency_type_patch.zip](https://github.com/moneymanagerex/moneymanagerex/files/1976550/currency_type_patch.zip)

**Comment by MartinX3** [comment]
@gabriele-v 
Thank you for your fast response :)

But I also don't need the patch, I have a backup from before the "Android App Upgrade". :)

I also think, that the Android App needs a new version build.
The stable is from February, the beta is from March

**Comment by MisterY** [comment]
Android should be upgrading natively. No extra effort required. Will try to confirm next week when I get back home.
-- 
Sent from my Android phone with GMX Mail.On 5/5/18, 12:42 Gabriele-V <notifications@github.com> wrote:
@MisterY could you check if in Android version your are upgrading correctly the DB based on https://github.com/moneymanagerex/database repository? Seems that we have some problems there..
@MartinX3 Please extract and apply attached patch
currency_type_patch.zip

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/moneymanagerex/moneymanagerex","title":"moneymanagerex/moneymanagerex","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/moneymanagerex/moneymanagerex"}},"updates":{"snippets":[{"icon":"PERSON","message":"@gabriele-v in #1632: @MisterY could you check if in Android version your are upgrading correctly the DB based on https://github.com/moneymanagerex/database repository? Seems that we have some problems there..\r\n\r\n@MartinX3 Please extract and apply attached patch\r\n[currency_type_patch.zip](https://github.com/moneymanagerex/moneymanagerex/files/1976550/currency_type_patch.zip)\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/moneymanagerex/moneymanagerex/issues/1632#issuecomment-386796455"}}}

**Comment by MartinX3** [comment]
But Desktop Alpha 4 upgraded my DB to Version 9
The Android version downgraded it to version 8 back again
May this the source of trouble?

**Comment by gabriele-v** [comment]
@MisterY does Android downgrade the DB too?
This should not be supported, if you open a newer DB, app should prevent opening and asking to update app itself.

**Comment by MisterY** [comment]
Here is the reference: https://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper#onupgrade

**Comment by gabriele-v** [comment]
Yes, seems that it downgrades the DB too.. This should be disabled in some way ASAP

**Comment by gabriele-v** [comment]
I'm not an expert of Android coding: Downgrade function it's empty, but maybe just version it's still downgraded so desktop tries to re-upgrade?

**Comment by MisterY** [comment]
I can only guess. Haven't really done any Android development or reading in over a year now.

**Comment by gabriele-v** [comment]
It's really important to fix it, otherwise DB upgrade is useless..

**Comment by slodki** [comment]
to be continued in moneymanagerex/android-money-manager-ex#1234
