### ISSUE TITLE
Stock errors

### ISSUE THREAD

**Issue by slodki** [moneymanagerex/moneymanagerex#1691]
Please verify with db attached (v13). [test.mmb.zip](https://github.com/moneymanagerex/moneymanagerex/files/2040863/test.mmb.zip)

1. Account in USD created for Oracle Corp. shares
2. Base currency set to PLN
3. Two shares transactions:
   - buying 100 (2018-01-01, price 47.28) = 4728 total
   - selling 50 (2018-04-02, price 45.01) = 2250.5 total
   ![mmex1](https://user-images.githubusercontent.com/3155552/40564460-110a0144-6069-11e8-904b-932606db5e5e.png)
4. Last price downloaded for 2018-05-24: 46.46 (50*46.46=2323 total)
   ![mmex2](https://user-images.githubusercontent.com/3155552/40564583-7ca490fe-6069-11e8-8d4a-fe1cb3fa1b3d.png)

**ERRORS:**
1. Edit Stock Investment window (above):
   1. Dimmed shared price (*\*Share Price* field in left panel) is 0.00 - price for initial date (2018-01-01) is known but not displayed
   2. *Diff.* column in right panel displays duplicated values from Price column
2. Stocks panel:
   ![mmex3](https://user-images.githubusercontent.com/3155552/40564773-472a7e56-606a-11e8-9e4e-619a6c63f0d1.png)
   1. *\*Share Price* column is empty (0.00)
   2. *Invested* and *Init value* column values are wrong. Should be 50*47,28=2364 for date 2018-01-01, or *Date* column moved to 2018-04-02
   3. *Gain/Loss* value for currently owned 50 shares is wrong:
      - could be initial - current price diff for shares owned: (46.46-47.28)*50=-41
      - could be last investment period value change (ignoring realized loss?): 2323-(4728-2250.5)=-154,5
      - could be realized loss (current value and shares owned ignored): (45.01-47.28)*50=-113.5
      - could be total +- diff for investment history: (2323+2250.5)-4728=-154,5
      ... but -227.0 is displayed?
   4. *Curr. Share Price* column value is wrong: should be 46.46 but 45.01 is displayed
   5. *Curr. Total Value* column value is wrong: should be 2323 but 2250.5 is displayed
   6. Bottom line is totally... incomprehensible? (pay attention to PLN vs USD):
      ![mmex4](https://user-images.githubusercontent.com/3155552/40565854-77e4e80c-606e-11e8-9a55-7d1e6ad4c593.png)
   7. *Stock Web Page* context menu is active even no share selected and do nothing when used
   8. There is *Last updated* string displayed without any date at the bottom of the panel when no share selected
3. *Foreign Currency Balance* context menu option for Broker account (right mouse button) displays 0.0 values for both USD and PLN
4. Similar errors exist in *Summary of Stocks* report:
   ![mmex5](https://user-images.githubusercontent.com/3155552/40566247-21b1e08c-6070-11e8-8b7e-ffd0b677e4de.png)

**Comment by slodki** [comment]
https://forum.moneymanagerex.org/viewtopic.php?f=10&t=7027

**Comment by fra87** [comment]
Will this issue be fixed in upcoming versions?

**Comment by vomikan** [comment]
Is this bug still relevant? Can it be postponed?

**Comment by n-stein** [comment]
I think I fixed most of these in various releases over the past 6 months or so...

>     1. Edit Stock Investment window (above):
>        
>        1. Dimmed shared price (_*Share Price_ field in left panel) is 0.00 - price for initial date (2018-01-01) is known but not displayed

Already fixed. Note that the "Share Price" is not the "Initial Price", but the weighted average price of all currently held shares. In this case, it is the same as the initial price because there has only been one "buy" transaction.

![image](https://user-images.githubusercontent.com/16599929/229569973-1346ee32-f88c-4a94-a5c4-683cebad4d38.png)

>        2. _Diff._ column in right panel displays duplicated values from Price column

I believe the "Diff" column was a 1.4 addition and does not exist in 1.3.x, 1.5.x, or 1.6.x.

>     2. Stocks panel:     

Current screenshot:
![image](https://user-images.githubusercontent.com/16599929/229571255-44251269-becf-4f50-91f7-ad638625f6a9.png)

>        1. _*Share Price_ column is empty (0.00)

Already fixed, again it shows the weighted average purchase price.

>        2. _Invested_ and _Init value_ column values are wrong. Should be 50*47,28=2364 for date 2018-01-01, or _Date_ column moved to 2018-04-02

Already fixed, as seen in screenshot above "Total Cost" is 2364.

>        3. _Gain/Loss_ value for currently owned 50 shares is wrong:
>           
>           * could be initial - current price diff for shares owned: (46.46-47.28)*50=-41

This is shown in the "Unrealized Gain/Loss" column.

>           * could be realized loss (current value and shares owned ignored): (45.01-47.28)*50=-113.5

This is shown in the "Realized Gain/Loss" column.

>           * could be total +- diff for investment history: (2323+2250.5)-4728=-154,5
>             ... but -227.0 is displayed?

We don't have a "Total Gain/Loss", but this is just Realized + Unrealized.

>        4. _Curr. Share Price_ column value is wrong: should be 46.46 but 45.01 is displayed

Is correct now.

>        5. _Curr. Total Value_ column value is wrong: should be 2323 but 2250.5 is displayed

Is correct now.

>        6. Bottom line is totally... incomprehensible? (pay attention to PLN vs USD):

Looks better now. It shows `|current_price - avg_price| = unrealized_gain_loss_per_share, unrealized_gain_loss_per_share * current_shares = unrealized_gain_loss (percent_of_total_cost)`
![image](https://user-images.githubusercontent.com/16599929/229572905-21615f72-52d9-4237-a781-16a89b08e979.png)

>        7. _Stock Web Page_ context menu is active even no share selected and do nothing when used

This one  is still an issue but should be an easy fix.

>        8. There is _Last updated_ string displayed without any date at the bottom of the panel when no share selected

I think this is OK. It's the last time the "Download Rates" was executed which updates rates for all symbols so it doesn't really apply to an individual stock.

>     3. _Foreign Currency Balance_ context menu option for Broker account (right mouse button) displays 0.0 values for both USD and PLN

Is this another 1.4.x only option? I don't see any context menu option for "Foreign Currency Balance".

>     4. Similar errors exist in _Summary of Stocks_ report:
![image](https://user-images.githubusercontent.com/16599929/229578526-ac628128-6a26-49c3-a5ae-d4872f72ea8e.png)

Report looks OK now I think.


So to me the only outstanding issue here is the "Stock Web Page" context menu option being available when there is no stock selected.

**Comment by n-stein** [comment]
I think this can be closed as there are no open items.
