### ISSUE TITLE
Budget Income Categories showing red X

### ISSUE THREAD

**Issue by jasonaleski** [moneymanagerex/moneymanagerex#2034]
Version: Money Manager EX - Version: 1.3.3 (DB v.7)

While working on a budget, three out of four budget items display a red "X" on the left side.  The "Other Income" is working correctly, but it came with Money Manager.  The other three, I've created myself.

I have three Income Categories
- [DEFAULT] Other Income
- [CUSTOM] Income
- [CUSTOM] Income :: Salary
- [CUSTOM] Income :: Interest Income

"Income" is just used as a holding category for sub accounts "Salary" and "Interest Income".

The Budget for these categories are configured as followed:
Category: Income; Sub Category: <blank>; Frequency: None; Amount $0.00; Estimated: $0.00; Type: Expense
Category: Income; Sub Category: Interest Income; Frequency: Monthly; Amount $25.00; Estimated: $300; Type: Income
Category: Income; Sub Category: Salary; Frequency: Bi-Weekly; Amount $1000.00; Estimated: $26000.00; Type: Income
Category: Other Income; Sub Category: <blank>; Frequency: Yearly; Amount $2500.00; Estimated: $2500.00; Type: Income

The transactions associated with each category are showing as Deposits.  I've tried created non-sub categories for salary and interest income, but the results are the same.  The Estimated Incomes at the top are correct.

I've tried changing the types to expenses, increasing and decreasing the budget amounts, but all result in the same. 

I think this may be a bug, but I'm also willing to accept I'm doing something wrong.  Any guides or suggestions?  I can provide additional information as necessary.

![screenshot](https://user-images.githubusercontent.com/25755956/52905425-c26f3400-31ff-11e9-8c80-ec6e5ed3e7e0.png)

**Comment by vomikan** [comment]
It's a feature not a bug.
![image](https://user-images.githubusercontent.com/6836805/53189161-ebd0fb00-3617-11e9-9ee3-828f6ef1e9a9.png)
In case if summary of all included subcategories is OK the category is OK as well.

**Comment by jasonaleski** [comment]
Given the example above, your budget amount is 1200 monthly.  If you enter $1300 as a transaction, you would be over the budget amount...which for income is a good thing; but see if it still displays a red X.  I would think it should display a green check once you reach meet or exceed the amount for a budget entry of type "income".

**Comment by vomikan** [comment]
How to reproduce? I can't
![image](https://user-images.githubusercontent.com/6836805/53299344-9f6d0180-3849-11e9-95f2-971116a57886.png)

**Comment by andrepg** [comment]
@vomikan I agree with @jasonaleski. I've watching this feature to better undestand behavior. It seems that:

---
* If I have an income of 1.200,00 and a budget of 1.000, we expected a green mark, given that we received more than expected. 
* If I have an income of 1.200,00 and a budget of 1.300,00 it's expected a red mark, since we received less than expected.
* If I have an expense of 1.000,00 and spent 900,00, it should be a good thing and show a green mark also. We spent less than planned.
* If I have an expense of 1.000,00 and spent 1.200,00, it's expected that a red mark be shown. It's more expensive that we planned.
---
So, in my opinion, the marks should work different to Expenses and Incomes. Every time that we spent more than expect, it's a hole on budget. And every time we received more than expected, it's a good thing, and maybe we can show a green mark.

**Comment by slodki** [comment]
My proposal:
* **green** up arrow &uarr; icon for income category above budget target
* **green** down arrow &darr; icon for expense category below budget target
* **red** up arrow &uarr; icon for expense category above budget target
* **red** down arrow &darr; icon for income category below budget target

**Comment by vomikan** [comment]
For me green is good. The red colour nean that something going bad.
If you spend more than planned that is bad.
If you earned less than planned the bad as well.

**Comment by vomikan** [comment]
@whalley what do you think regarding this issue?
