### ISSUE TITLE
Android app version

### ISSUE THREAD

**Issue by MarcusGHub** [moneymanagerex/moneymanagerex#2046]
I know I can get the latest release for my Windows PC here on GitHub. My current version is mmex-1.4.0-alpha.7. How do I get this version for my android device?

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/android-money-manager-ex
I hope here.

**Comment by alerque** [comment]
@MarcusGHub The Android app and the desktop app use separate code bases. They are written in different languages and follow a different release cycle. The version numbers  will never be the same because they are not the same program. They do use the same data file  format and do model their activities after each-other, but they are effectively independent projects.

**Comment by MarcusGHub** [comment]
Sorry to wake up a closed thread.
Is the Android app now dead?

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/android-money-manager-ex/releases

![Uploading image.png…]()

**Comment by MarcusGHub** [comment]
I realized that it hasn't been updated since 2019, but you have been posting in the issues section.
Also, it only works if the database is not encrypted.
