### ISSUE TITLE
wrong links on website download page

### ISSUE THREAD

**Issue by milotype** [moneymanagerex/moneymanagerex#2101]
**Describe the bug**
The MacOS link on the download page of your website for "Money Manager EX Desktop is 1.4.0-alpha1"

**To Reproduce**
1. Go to 'https://www.moneymanagerex.org/download', scroll to "Unstable build"
2. Click on 'MacOS link'
3. See error on next page

**Your OS:**
- [x] Mac OSX

**MMEX version:**
- [x] 1.4.x

**Comment by slodki** [comment]
FF on linux:
* `ubuntu-xenial-mmex-1.4.0-ALPHA-3.deb` is downloaded from SF when clicked on stable MacOS download button
* > Error
  > Web Link not found.

  is displayed in red on main page of MMEX website (redirected from download page) when clicked on unstable MacOS download button

**Comment by natrius** [comment]
Same for Windows. 

> The latest unstable build of Money Manager EX Desktop is 1.4.0-alpha1

Pressing ` Windows - 32BIT - Portable` or `Windows - 64BIT - Portable` results in `mmex_1.3.0-alpha_Win32_portable_build247.zip` or `mmex_1.3.0-alpha_x64_portable_build247.zip`

Downloading from https://github.com/moneymanagerex/moneymanagerex/releases the *.exe works perfectly fine, maybe point the download there?

**Comment by slodki** [comment]
see #1169 too

**Comment by guanlisheng** [comment]
i will take a look on the home website.

**Comment by natrius** [comment]
If i could make some suggestions:

1. **Stable** - Leave as it is
2. **Nightly** - Link to https://github.com/moneymanagerex/moneymanagerex/releases/tag/nightly instead of wherever it is linked now...
3. **Alpha** - as there is no really tag for "Alpha" unfortunately, i would just link to https://github.com/moneymanagerex/moneymanagerex/releases so it can be found by interested individuals and nobody has to change the homepage often.
4. **All releases** - same as above "Every prior release can be found at this link https://github.com/moneymanagerex/moneymanagerex/releases"

This way its at least a bit persistent and it can be found easy. For complete persistence establish a "Stable" tag and finally link the stable builds also to GitHub maybe.

**Comment by slodki** [comment]
github.../releases/latest link will always point to the stable release (used already in README.md file badges)

We have packagecloud and snapstore repos auto updated too - GH Releases is not the only source of MMEX packages.

Nighty build should be not provided for normal users - they should be assumed as broken and not working.

**Comment by natrius** [comment]
As i wrote, it was just a suggestion based on what's now available on the download-page, not what should be changed. (And, imho why not make nightly available, at the bottom as last option. There are always guys who wanna try the most recent stuff. Could probably help with developing too, bugs and so on *shrug*)

**Comment by vomikan** [comment]
Nobody are developing v1.4.0.
I have high hopes for the v1.3.4
