### ISSUE TITLE
filter by multiple categories and payees

### ISSUE THREAD

**Issue by netuser2** [moneymanagerex/moneymanagerex#2232]
Can you allow filtering by more than one category? It it not possible to select more than 1 category right now.

**Comment by vomikan** [comment]
You can do the following... Instead of the category selection button, make a wxComboBox drop-down menu. Fill it with all categories. And use regular expressions to search. Then you can search for several categories at once. For example.
Bills:Telephone
Bills:Electricity
Bills:Gas
To search for the first and second cases, you can set Bills:Telephone|Bills:Electricity
