### ISSUE TITLE
portable mode

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2590]
Incorrect path for mmexini.db3 for non portablу mode
![image](https://user-images.githubusercontent.com/6836805/83362609-51737180-a39b-11ea-824a-50e482f4b6ed.png)

- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [x] 1.4.x
  - [ ] 1.3.3

#2585

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/commit/d4c9d499231a3b22e049f2c3d22d6a15c48cfd2e#diff-af3b638bc2a3e6c650974192a53c7291

**Comment by gabriele-v** [comment]
FYI looks like that after your commit, now even portable mode it's not portable anymore, because mmex.ini it's missing, see latest artifact:
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/33475719/job/jos7wg2ldbfg7fw8/artifacts

**Comment by gabriele-v** [comment]
FYI looks like that after your change even portable mode it's not portable anymore, see latest artifacts:
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/33475719/job/jos7wg2ldbfg7fw8/artifacts

**Comment by vomikan** [comment]
Yes, I'll include mmexini.db3 file in zip manually.
The scripts to complex for me. I can't find better solution.

**Comment by whalley** [comment]
Remind me what exactly we want from this for Win builds and I can look at the scripts.

**Comment by gabriele-v** [comment]
Basically if MMEX finds the file `mmexini.db3` here
![image](https://user-images.githubusercontent.com/7106290/161211992-3ca8d166-6079-432e-aaee-5ba5e5eac942.png)

Then it goes in "portable mode" so it doesn't create any other files on the PC. Otherwise it creates a folder for the settings I think in appdata foler.

So when distributing the .zip for portable mode, it should be included an empty (0kb) file mmexini.db3 so mmex detects it and goes in portable mode.

Problem is that looks like the file is not created anymore.

Obviously installable artifacts should not have this file.

**Comment by vomikan** [comment]
I can't reproduce this issue with 1.5.14-beta

**Comment by gabriele-v** [comment]
Problem still there with 1.5.14 official release:
![image](https://user-images.githubusercontent.com/7106290/163540295-7f121029-5e6d-4710-92e2-906a67269f4d.png)

**Comment by vomikan** [comment]
mkdir mmex-1.5.14-win64
`fsutil file createnew mmex-1.5.14-win64\mmexini.db3 0 `
7z a mmex-1.5.14-win64-portable.zip mmex-1.5.14-Beta.1-win64\mmexini.db3
