### ISSUE TITLE
why i can't change the language to Chinese (Traditional)?

### ISSUE THREAD

**Issue by daniel89104** [moneymanagerex/moneymanagerex#2661]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by daniel89104** [comment]
why i can't change the language to Chinese (Traditional)?
thanks!

**Comment by vomikan** [comment]
There are no Chinese (Traditional)
https://crowdin.com/project/moneymanagerex
I've attached po file from old version of mmex.
This translation have been excluded from the project because it is incomplete.
[zh_tw.zip](https://github.com/moneymanagerex/moneymanagerex/files/5011168/zh_tw.zip)
You can use it as is or update it using https://poedit.net/
or crowdin.com

**Comment by vomikan** [comment]
I've added Chinese (Traditional) in crowdin
https://crowdin.com/translate/moneymanagerex/470/en-zhtw

**Comment by daniel89104** [comment]
I can help to translate Chinese (traditional), how can I contribute?

**Comment by daniel89104** [comment]
can you send me Chinese(Simplified).po file or English.po file? i can translate it !

**Comment by daniel89104** [comment]
https://drive.google.com/file/d/1gYdfZ0d-bZkmTf7O4HOpyZsKa7cwteuZ/view?usp=sharing
translated

**Comment by vomikan** [comment]
@daniel89104 this case has been opened regarding Chinese (Traditional).
To translate Chinese(Simplified) please use web interface 
https://crowdin.com/project/moneymanagerex/zh-CN#
Also it's possible to download po file from there.

**Comment by vomikan** [comment]
Related issue https://github.com/moneymanagerex/moneymanagerex/issues/1989
