### ISSUE TITLE
pacman repo appears to have out of date version

### ISSUE THREAD

**Issue by Castratikron** [moneymanagerex/moneymanagerex#2707]
It looks like the pacman repo still has version 1.3.3-3, while the website shows 1.3.5 as the stable version
![image](https://user-images.githubusercontent.com/26463709/96373214-020ac380-1139-11eb-8c5a-29a0b5397ae5.png)
![image](https://user-images.githubusercontent.com/26463709/96373230-164ec080-1139-11eb-8ba9-a7de3030275d.png)

Running on Manjaro:
![image](https://user-images.githubusercontent.com/26463709/96373264-557d1180-1139-11eb-8792-b1e7c337fa8c.png)

**Comment by MartinX3** [comment]
@Castratikron please use the AUR packet
https://aur.archlinux.org/packages/moneymanagerex-git/
It will showed as a new update everytime the git repo gets a new tag.
But you need to tick the "development packets" option, otherwise your AUR helper will ignore the `pkgver()` of every AUR packet and only look for the manual changed version in the AUR database.

The packet https://www.archlinux.org/packages/community/x86_64/moneymanagerex/ is already flagged as out of date since 2020-04-24, so the maintainer is aware of the problem, but doesn't care. (Maybe he has no time as a volunteer or whatever )

**Comment by Castratikron** [comment]
@MartinX3 thank you!  I was experiencing some bugs in 1.3.3 which I had a hunch were solved in the later versions, but I really wanted to keep the program management somewhat formalized within `pacman`.  Sure enough, the bugs I had are solved in the latest version.
BTW, I didn't quite understand your advice about "development packets"; I simply cloned the AUR repo and ran `makepkg -si` to install it.  Can you elaborate about the "development packets" option?

**Comment by MartinX3** [comment]
AUR helpers are software managers like pamac, but with AUR support.
I recommend yay as a terminal one or pamac as a gui one.

https://wiki.archlinux.org/index.php/AUR_helpers

**Comment by Castratikron** [comment]
@MartinX3 thanks!
