### ISSUE TITLE
Store the time of transaction

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2729]
#457

![image](https://user-images.githubusercontent.com/6836805/101279145-50e7e780-37d1-11eb-9f2f-b405635dbce2.png)

https://github.com/moneymanagerex/database/blob/master/tables.sql#L117-L135

**Comment by vomikan** [comment]
To implement this feature most easy way is to add one more column into 
CHECKINGACCOUNT_V1 table, for example, "TRANSTIME" (text).
Unix format not human readable but sort order using TRANSDATE column. This is a dilemma.

**Comment by tylla** [comment]
Wow, nice work!
I would have chosen UNIX timestamp, but I can completely understand and support your decision for choosing TRANSTIME. It is really much less work to implement.
What are the (are there any) plans about v2.0, should I hold my breath? ;-)

**Comment by vomikan** [comment]
This is my personal initiative. I want to be able to adequately monitor the stock market. This version is not coordinated with other developers and has no wide publicity and plans.
But if the experiment is successful, цу can make a release.
Main goals in the v2.0 :
#2718
#2712
#2717
#2702

**Comment by vomikan** [comment]
One more option is to use YYYY-MM-DDTHH:MM:SS format. It may be implremented without DB upgrade.

**Comment by n-stein** [comment]
@vomikan are you working on this? If not, I'll implement it.

**Comment by vomikan** [comment]
> @vomikan are you working on this? If not, I'll implement it.

At the moment, my participation in the project is limited to updating translations.

**Comment by n-stein** [comment]
That should be fully backward compatible, no database update required. Of course, if you add a time to a transaction in version 1.7.1 then edit the transaction in 1.7.0 it will revert the time back to 00:00:00.

**Comment by whalley** [comment]
Great work @n-stein, a couple of observations:

1. Maybe we should add an option to exclude the time gainst the date? Just thinking that the majoority of the users may not want that precision (default id DATE only?). If DATE only then we exclude the time from all transaction dialogs and account lists.
2. Transaction Report. Should probably include TIME as a field (and allow to be hidden). Although not essential, for completeness the date range should allow time to be specified.
3. As with (2), we should probably, for completeness, allow TIME on reports that allow a custom date range.

**Comment by n-stein** [comment]
All good points, will work on them.

I need to go over all the `find` statements, particularly those that use `GREATER` and `GREATER_EQUAL` because the ISO datetime string is always greater than ISO date string. For the same reason I think I also need to set the end date for the date ranges to append "T23:59:59" so that the `TRANSDATE <= end_date` checks work properly.

**Comment by whalley** [comment]
@n-stein Not sure if you spotted that that the Linux build is failing as a result of these changes.

**Comment by n-stein** [comment]
> 1. Maybe we should add an option to exclude the time against the date? Just thinking that the majoority of the users may not want that precision (default is DATE only?). If DATE only then we exclude the time from all transaction dialogs and account lists.

In Options->View Options there is now a checkbox `Use 'Time' in transaction recording/reporting`. Without enabling this option it should look and behave identically to 1.7.0 (this is the default, users have to manually enable the time field).

> 2\. Transaction Report. Should probably include TIME as a field (and allow to be hidden). Although not essential, for completeness the date range should allow time to be specified.

If the option in (1) is turned on, Time is now included in the transaction report selection dialog and is displayed in a column on the report. The column can be hidden.

> 3\. As with (2), we should probably, for completeness, allow TIME on reports that allow a custom date range.

If the option in (1) is turned on, the time field appears next to the date selection on the canned reports. It is displayed for all selections, but is only editable if 'Custom' is selected (otherwise it displays 00:00:00 for start date and 11:59:59 for end date).

**Comment by whalley** [comment]
@n-stein One anomaly I noted was that when 'View Time' is enabled that the Transaction 'Hide Columns' still listed the 'Time' field as an option

**Comment by n-stein** [comment]
> 1. When 'View Time' is enabled that the Transaction 'Hide Columns' still listed the 'Time' field as an option

I've got a fix for this.



> 2\. The date range 'Over Time' returns zero entries

Where are you seeing this behavior? 'Over Time' seems to be working for me in the reports and account panels.

**Comment by whalley** [comment]
> > 2. The date range 'Over Time' returns zero entries
> 
> Where are you seeing this behavior? 'Over Time' seems to be working for me in the reports and account panels.

I initially saw it on the Transaction Report... But just tried in Reports. The end date looks really odd.

![CleanShot 2024-02-07 at 21 22 24](https://github.com/moneymanagerex/moneymanagerex/assets/487345/b915484f-a7c2-49e7-8904-6e40a8512549)

**Comment by whalley** [comment]
![CleanShot 2024-02-07 at 21 38 18](https://github.com/moneymanagerex/moneymanagerex/assets/487345/6e0fd31f-a951-4134-b60d-ef4630a1d436)

?

**Comment by n-stein** [comment]
> Think this should be: 253402300799

Must be a Unix thing? On Windows that converts to a wxDateTime of `9999-12-31T18:59:59`

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/bd77bafb-633f-4eea-8403-67fce432ce52)
![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/e5613dba-4fa3-47c2-9e6d-0ca70fd0075e)

**Comment by n-stein** [comment]
Ah, right. Timezone conversion...

**Comment by n-stein** [comment]
That should fix both issues.

**Comment by rmelillo76** [comment]
Hey @n-stein just found a bug - right click and select "Find all transactions with Date '<date>'" will only find transactions without a time (00:00:00), transactions with a time set aren't displayed. And just an observation, there is no right click option to find by Time when hovered over that field in the grid, but maybe that's OK since I don't think it would be that useful. Keep up the good work, this is great stuff!

**Comment by n-stein** [comment]
> right click and select "Find all transactions with Date '[date]'" will only find transactions without a time (00:00:00), transactions with a time set aren't displayed

Good catch, I will fix this.

> there is no right click option to find by Time when hovered over that field in the grid

I debated about this when I added the Time column to the checking panel. Right now Time is combined with Date in the filter dialog (which makes sense because they are truly a single field in the db), but this would require having Time as a separate row in the filter dialog. It can definitely be done, but I wasn't sure it had much utility. And since there was precedent for not having all columns be 'Findable' -- Last Updated Time is also not right-clickable because it doesn't appear in the Transaction Filter dialog -- I just went with the simpler option.

Happy to look at it if the consensus is that it would be useful.

**Comment by whalley** [comment]
> Right now Time is combined with Date in the filter dialog (which makes sense because they are truly a single field in the db), but this would require having Time as a separate row in the filter dialog. It can definitely be done, but I wasn't sure it had much utility

Agree, current implementation seems logical.

**Comment by whalley** [comment]
Just spotted another issue on the Daily Cash Flow report related to identifying when the day changes. 

![CleanShot 2024-02-09 at 08 50 30](https://github.com/moneymanagerex/moneymanagerex/assets/487345/25760db6-b832-4148-b16f-75022ea0f247)

**Comment by rmelillo76** [comment]
> I debated about this when I added the Time column to the checking panel. Right now Time is combined with Date in the filter dialog (which makes sense because they are truly a single field in the db), but this would require having Time as a separate row in the filter dialog. It can definitely be done, but I wasn't sure it had much utility. And since there was precedent for not having all columns be 'Findable' -- Last Updated Time is also not right-clickable because it doesn't appear in the Transaction Filter dialog -- I just went with the simpler option.
> 
> Happy to look at it if the consensus is that it would be useful.

Good points, I would leave as-is

**Comment by n-stein** [comment]
Fixed right click filter and the cashflow reports.
