### ISSUE TITLE
Error when opening new budget

### ISSUE THREAD

**Issue by HNash22** [moneymanagerex/moneymanagerex#2930]
Upon creating a new budget and attempting to open it I get the following error 'invalid map<K, T> key'. This not only prevents the budget tool from working but requires the program to be restarted for anything else to work. I have only tried this in version 1.3.6 and did not have any existing budgets in the database to test.
![image](https://user-images.githubusercontent.com/73892064/108593927-977bc580-736e-11eb-8cd8-ebccb4b5e5cb.png)

**Comment by vomikan** [comment]
Could you please to download the folloving portable release and test it?
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/37866075/job/kt7b1d1pl7row3hv/artifacts

**Comment by HNash22** [comment]
It works fine in that release

**Comment by HNash22** [comment]
Apologies, I only searched open issues to make sure this wasn't a duplicate - didn't think to check the closed ones!!

**Comment by vomikan** [comment]
Thank you for your report. Seems this bug already fixed in issue #2775 

I recommend to use mentioned above beta version of mmex.
All subsequent changes can be found here:
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/history

The list of fixes for today is here:
https://github.com/moneymanagerex/moneymanagerex/releases/tag/untagged-d17f3c6febf1e663dc6e
