### ISSUE TITLE
New reporting look and feel

### ISSUE THREAD

**Issue by guanlisheng** [moneymanagerex/moneymanagerex#297]
I think it will be a good chance to examine all existing reports and do a complete reorganization like the following
![mmex_reporting](https://cloud.githubusercontent.com/assets/721973/5389995/93dc16aa-813f-11e4-9915-d289c0c61561.png)

**Comment by guanlisheng** [comment]
Any one want to take this ?

**Comment by siena123** [comment]
I was starting to look at this one so I will go ahead and work on it.

**Comment by guanlisheng** [comment]
thanks and assigned the issue to you

**Comment by guanlisheng** [comment]
@siena123 how was everything going? would we close this ?

**Comment by siena123** [comment]
I have not had much time to work on this yet but I am still trying to work on it. I am considering this as the major feature enhancement that I am currently working on. Right now I am focusing my time more on doing bug fixes to v1.3 rather than on staring to code changes for another new feature or enhancement. I am also helping two users at the moment with some custom reports in GRM. So the short answer is no don't close this item.

**Comment by siena123** [comment]
I want to make a few more changes but I have this to a point others can look look at the changes before I submit a pull request.
