### ISSUE TITLE
Position of New Transaction icon in the toolbar

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#3189]
# Description of the feature

The position of the New Transaction icon in the toolbar feels wrong. It is currently positioned after the Options icon (an infrequently used command).

I suggest that from a functional point of view,  the New Transaction icon more logically belongs in the position shown in the lower screenshot...
![image](https://user-images.githubusercontent.com/4060092/113452783-a25d5780-93fc-11eb-81a9-89183d4e0ca6.png)

**Comment by whalley** [comment]
@vomikan - These and other improvements are all being made to the 1.5.0 branch (though this issue is flagged for 1.5.1), thought plan was to keep this branch for essential bug fixes? I've no real issue but means we  have no long term stability on this branch at present so seems now to be a little further away from releasing it.

**Comment by vomikan** [comment]
For ease of changes, I use cherry-pick. The change in the position of the icon occurred along with the fixes.
This is a cosmetic change. It does not affect the stability in any way.
