### ISSUE TITLE
All Transactions panel currencies

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3209]
All values in the panel are presented in the base currency format.

I suggest redoing this to the following view:
![image](https://user-images.githubusercontent.com/6836805/113613508-03ce3200-965a-11eb-8993-d8446055f937.png)

**Comment by vomikan** [comment]
Hi Vomikan,

I am on 1.5.1 RC2 and can see this implementation. One issue I see is if there was a cross currency transfer, then the deposited value is showing the 'from' currency rather than the 'to' currency. Hope I made myself clear.

**Comment by reddyshyam** [comment]
Hi Vomikan,

I am on 1.5.1 RC2 and can see this implementation. One issue I see is if there was a cross currency transfer, then the deposited value is showing the 'from' currency rather than the 'to' currency. Hope I made myself clear.

Adding this again on the main feature ticket so that the issue is known.

**Comment by vomikan** [comment]
It is possible to make the values appear in two cells. But I don't want to load the UI and do unnecessary calculations in this screen.

**Comment by reddyshyam** [comment]
> It is possible to make the values appear in two cells. But I don't want to load the UI and do unnecessary calculations in this screen.

I understand, atleast those that are manually filled (both withdrawal and deposit) as in my case?

**Comment by whalley** [comment]
This can be closed it has been implemented.
