### ISSUE TITLE
Support transfer operation for stock account

### ISSUE THREAD

**Issue by guanlisheng** [moneymanagerex/moneymanagerex#326]
Now we only support the transfer between non-stock account and there will be one single transaction as Account A, $100 ==>Account B, ¥600. 
Both of the account will show this transaction will opposite transfer direction as
* Account A , -> $100
* Account B,  <- ¥600

This enhancement is to support the transfer to any account (even Asset).

**Comment by siena123** [comment]
I think this could be an interesting feature but it is not one that I would personally use. I don't know if enough people would be interested in it and use the feature to make it worth the effort.

**Comment by guanlisheng** [comment]
So what's behavior in your mind? This is the place to discuss the behavior

**Comment by siena123** [comment]
If we do this I don't think it should be restricted to just a transfer from Bank to Stock but between any accounts. This produces the following transaction that need to be considered.
     Bank to/from Bank (already done)
     Bank to/from Asset
     Bank to/from Stock
     Stock to/from Asset

Transfer to and from account type Asset should be restricted to asset type Cash (for Bank) or Other (for Stock).

Transfer to and from account type Stock needs some work. I see two ways to handle this. Although it is more work, my preference is the second one.
     1. Just modify the initial balance in the calculations as mentioned above for both transfers to and from the account.
     2. Treat the transfer as a purchase or sale of a stock symbol for the specified account.

Either way the transfer needs to be excluded from the online refresh/update of the price in some way. In the first option, it would be always excluded. In the second option, it would only be excluded on the transfer from (sale of stock).

On item two, the transfer into the account would be easy as it can be handled as a new record. For the transfer from the account, the transaction could be a new record as well (negative purchase values not currently allowed) but needs to be locked in some manor from getting updated automatically. This would require some kind of change in the way account value is calculated for that stock symbol since the sale transaction would be a fixed value.
     purchase 100 shares at currency of 100
     sell 25 shares at currency of 90 (record of fixed sale at this amount)
     current value at currency of 110
     value is 110 * (100 - 25) = 8250, currently calculation iterates through stock records which would give a wrong current value due to fixed transaction sale amount.

Option two has the added benefit of introducing a sale transaction into the stock account. Currently only purchase transaction types allowed. For sale transactions, the shares amount on an existing record must be edited.

**Comment by guanlisheng** [comment]
Hi @siena123 , we can't support transfer for asset until we have real asset account.
Initial balance as a pool here will simplify both transfer support and stock buying/selling. 

Your logic about the buying/selling is too complex and has conflict with existing online stock price update. Since we have no double-entry here, we should provide two kinds of modification:
* for real modification due to mistake input
* for buying/selling update due to stock number [+/-] and will add the profit into account's initial balance.

**Comment by guanlisheng** [comment]
@moneymanagerex/desktop-mmex-team @moneymanagerex/android-mmex-team , we can talk more about stock buying & selling with #336

**Comment by stef145g** [comment]
Closing this issue and continuing discussion on issue: Support buying & selling for stock account #336

**Comment by guanlisheng** [comment]
I think they are different request.

**Comment by stef145g** [comment]
Issue reopened. New solution required.

**Comment by MisterY** [comment]
Please see https://github.com/moneymanagerex/moneymanagerex/issues/336#issuecomment-135741409 for my suggestion. It is very simple yet effective. And we have almost all the infrastructure to support it.

**Comment by vomikan** [comment]
Related issue: https://sourceforge.net/p/moneymanagerex/feature-requests/397/

**Comment by stef145g** [comment]
Closing this issue as this feature is incorporated in the new feature provided by #336
