### ISSUE TITLE
Value Display Sample clipped

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3397]
![image](https://user-images.githubusercontent.com/6836805/117490469-7abb5b00-af77-11eb-919c-174fb54a7c15.png)

**Comment by vomikan** [comment]
We should do both of these examples in the same style.
![image](https://user-images.githubusercontent.com/6836805/117490661-c2da7d80-af77-11eb-9f91-3525f6807f4c.png)

**Comment by whalley** [comment]
Yes, this change seems sensible.

**Comment by tactilis** [comment]
@vomikan  Is the intention to display the value next to Locale on the Options dialog in an _identical_ way to the shown on the Currency dialog, i.e appropriately formatted _and_ with the currency symbol?

If so, perhaps you could make the label (on both dialogs):  _"Currency format"_ - because it is a currency value, not just a number.
