### ISSUE TITLE
Italian Locale Decimal

### ISSUE THREAD

**Issue by sommella** [moneymanagerex/moneymanagerex#3602]
Hi,

Selecting Italian Locale the decimal format results 1.234.567.90, instead should be 1.234.567,90.
Could you please fix it?

Source of trust:
https://en.wikipedia.org/wiki/Decimal_separator

<hr>Version: 1.5.2 64-bit<br>
 • Build: Giu  4 2021 07:16:03<br>
 • db 7 •  (aes128cbc)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.5 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.0.1<br>
 • libcurl/7.61.0-DEV WinSSL<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19043), 64-bit edition<br>
 •  Italian (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by tactilis** [comment]
Please check existing issues before raising a new one:

![image](https://user-images.githubusercontent.com/4060092/121671865-00ff1b80-caa7-11eb-9359-be403b96c5cd.png)

The answer was already given several times. For example in #3596:

--------
Known problem #3557 #3583. Fixed in the 1.5.3 development version.

A workaround for now in 1.5.2 is to set Options | General | Locale to blank, which will allow you to manually set the Group and Decimal Chars as you wish in Organize Currency | EUR | Edit
