### ISSUE TITLE
Decimal separator for Germany wrong since 1.5.2 

### ISSUE THREAD

**Issue by Urbi2k** [moneymanagerex/moneymanagerex#3608]
Since updating to the current version MMEX uses a . of an , as the decimal seperator even though I chose German language (or System Default - I use Windows on German as well). It hasn't been an issue before. 

<hr>Version: 1.5.2 64-bit<br>
 • Build: Juni  4 2021 07:16:03<br>
 • db 7 •  (aes128cbc)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.5 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.0.1<br>
 • libcurl/7.61.0-DEV WinSSL<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19041), 64-bit edition<br>
 •  German (windows-1252)<br>
 • 2560x1440 32bit 96x96ppi

**Comment by vomikan** [comment]
Thank you for your report. 
#3602 #3596:

Known problem #3557 #3583. Fixed in the 1.5.3 development version.

A workaround for now in 1.5.2 is to set Options | General | Locale to blank, which will allow you to manually set the Group and Decimal Chars as you wish in Organize Currency | EUR | Edit

or upgrade:
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/39573347/job/djw59anlscdr72h5/artifacts
