### ISSUE TITLE
Move import Dialog to a tab

### ISSUE THREAD

**Issue by sarjanwebdev** [moneymanagerex/moneymanagerex#3687]
So that while import is being configured, we can go back to the transactions list and check the latest transaction etc.
Also on full screen interfaces (my monitor is 42 inch!) it allows more space avoid scroll bars everywhere.

This could fix my requirement simply by displaying date of latest transaction beside account name in account selector. 😃 

_Originally posted by @vomikan in https://github.com/moneymanagerex/moneymanagerex/issues/745#issuecomment-215390305_

**Comment by tactilis** [comment]
Note that there are some complexities that would arise from having the Import user interface in a tab, instead of in the separate dialog as currently exists.

For example...

At present, because the Import dialog is modal, you can't interact with the rest of MMEX while the dialog is displayed. This means that you are prevented from editing the name of an account while the Import dialog is displayed (or even deleting the account!), which means that Import doesn't need to check for the account that it is just about to import into being re-named (or deleted) underneath it while the dialog is displayed.

If Import was non-modal (for example, in a tab), then it would allow the possibility of a user making changes to the account name, while that account was selected for import. I'd agree that it would be foolish for a user to do this, but MMEX import should be robust even when the user does unexpected things.

Of course, it's not impossible to make MMEX cope with this situation, but it's extra work that was, perhaps, not apparent from the relatively simple sounding request to "Move import dialog to a tab".

**Comment by sarjanwebdev** [comment]
> Note that there are some complexities that would arise from having the Import user interface in a tab, instead of in the separate dialog as currently exists.
> 
> For example...
> 
> At present, because the Import dialog is modal, you can't interact with the rest of MMEX while the dialog is displayed. This means that you are prevented from editing the name of an account while the Import dialog is displayed (or even deleting the account!), which means that Import doesn't need to check for the account that it is just about to import into being re-named (or deleted) underneath it while the dialog is displayed.
> 
> If Import was non-modal (for example, in a tab), then it would allow the possibility of a user making changes to the account name, while that account was selected for import. I'd agree that it would be foolish for a user to do this, but MMEX import should be robust even when the user does unexpected things.
> 
> Of course, it's not impossible to make MMEX cope with this situation, but it's extra work that was, perhaps, not apparent from the relatively simple sounding request to "Move import dialog to a tab".

This now can be closed.
