### ISSUE TITLE
Add <BR> for every new line in notes

### ISSUE THREAD

**Issue by Dandy64** [moneymanagerex/moneymanagerex#3700]
I have added a few notes for the transaction. Every comment starting from a new line.

![image](https://user-images.githubusercontent.com/83161661/125603476-42a3e3f7-8c2b-407b-ab87-ea61ed1c10d1.png)
In the transaction table, it looks different.

![image](https://user-images.githubusercontent.com/83161661/125603623-019522fd-492d-4347-a56b-687e51f7bb80.png)
 **It would be good to keep users' formatting and start every new comment from a new line**

# Use cases

If not obvious, explain the use cases or problems to solve.

**Comment by whalley** [comment]
It's an obvious trade-off between compact spacing of the transaction view and depicting the full multi-line notes.

**Comment by tactilis** [comment]
@Dandy64
> It would be good to keep users' formatting and start every new comment from a new line

Please could you please say in your enhancement requests exactly **_why_** something "_would be good_".

The GitHub Issue template requests you to: "_explain the use cases or problems to solve_".  You haven't said what is the problem caused by MMEX's current behaviour? 

In your solution, would you expect every row in the transaction list to be a different height depending on the number of lines in the Notes? Is that really a good idea?  What if there were 50 lines of Notes for one transaction? Would you expect to see all of them in the transaction list?

As @whalley says, MMEX already has a solution that shows the full multi-line notes in the transaction. And all you have to do to see your notes formatted on separate lines is to double-click the transaction to see the Edit Transaction dialog.

**Comment by 2BeeOrNot** [comment]
This issue is tagged as an enhancement. If it is implemented as @tactilis describes above please make it optional. After displaying the essentials, such as date, payee, deposit, withdrawal, balance etc. there isn't much room for notes. Making the transaction row height big enough to format the notes will make for some really high rows and, IMO, a messy transaction list. The notes are displayed formatted as entered in the area below the transactions where the money tips appear.

Somewhat related it would be nice if the notes in the money tips area would wrap for long lines and scroll.

**Comment by tactilis** [comment]
@2BeeOrNot
> Making the transaction row height big enough to format the notes will make for some really high rows and, IMO, a messy transaction list

Agreed. IMO, it's not a good idea and no use case has been provided.

And, as you say, there's already this:

> The notes are displayed formatted as entered in the area below the transactions where the money tips appear.

See also #3224

**Comment by Dandy64** [comment]
Probably, you are all right.
