### ISSUE TITLE
Summary of Accounts display shares wrong

### ISSUE THREAD

**Issue by renato-mmex** [moneymanagerex/moneymanagerex#3708]
![MMEX22](https://user-images.githubusercontent.com/76920138/126066785-0fe39fd4-e5f6-4ce7-93cb-bc32db42dd98.png)
![MMEX23](https://user-images.githubusercontent.com/76920138/126066791-112f904c-08e5-40af-89d4-fc61149c42e8.png)
> Replace this text (marked with >) with detailed description of your problem.
> Please do not remove information attached below this text.

<hr>Version: 1.5.4 64-bit<br>
 • Build: Jul 18 2021 10:50:49<br>
 • db 7 •  (aes128cbc)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.5 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.0.1<br>
 • libcurl/7.61.0-DEV WinSSL<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 22000), 64-bit edition<br>
 •  German (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by vomikan** [comment]
Related issue 
https://github.com/moneymanagerex/moneymanagerex/issues/2987

**Comment by whalley** [comment]
Having quickly looked at this the report it seems to showing the correct values.
@renato-mmex Are you able to test against the latest beta build?

![CleanShot 2022-09-30 at 18 55 40](https://user-images.githubusercontent.com/487345/193328819-0357d17e-9c7a-4bd7-8748-109b729652b9.png)
![CleanShot 2022-09-30 at 19 01 34](https://user-images.githubusercontent.com/487345/193329977-080bfc48-5ba2-4304-8073-9314e94782e6.png)
![CleanShot 2022-09-30 at 19 03 10](https://user-images.githubusercontent.com/487345/193330106-b5804e20-46bc-40df-9f6f-f552c5ce8952.png)
![CleanShot 2022-09-30 at 18 56 55](https://user-images.githubusercontent.com/487345/193329060-ea40d7f9-0ce4-4369-833f-505753cb9fc5.png)
![CleanShot 2022-09-30 at 18 57 26](https://user-images.githubusercontent.com/487345/193329111-59ae4251-cef1-4694-9ed6-8f807eecfa84.png)
![CleanShot 2022-09-30 at 18 57 56](https://user-images.githubusercontent.com/487345/193329262-908130d6-69c1-40ae-80b2-9ec7f264510d.png)

**Comment by n-stein** [comment]
I think this is a similar issue to the assets question in #5174. There is some confusion about the balance of the share account vs the value of the stocks. 

@renato-mmex You can see in your screenshots that the "stocks" portion of the report shows the correct value of the stocks while the "share accounts" value shows an equal and opposite value. This is because funds were withdrawn from the share account to the stock without making a corresponding deposit into the share account. Where did the money you used to purchase the stocks come from? You would need a transfer from that account into the share account to offset the movement of funds from the share account to the stock.

**Comment by n-stein** [comment]
Not a bug. 

@renato-mmex The share account section is showing the stock transaction withdrawal from the share account to the stock. This is based on the _purchase price_ of your stock shares. You are comparing that against the value of the stock based on _current price_. You can see the difference between the two values you have circled is exactly the loss on the stock.
