### ISSUE TITLE
Number of backup files - old issue

### ISSUE THREAD

**Issue by Dandy64** [moneymanagerex/moneymanagerex#3720]
MMEX version: all

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
There is an option to set the maximum number of backup files kept by the application.

![image](https://user-images.githubusercontent.com/83161661/126868515-2eddb660-cb41-4f4f-baee-764bfa2fb4c8.png)

In reality, the program saves and keeps much more files.
 
![image](https://user-images.githubusercontent.com/83161661/126868555-9017cf06-50f5-4208-a999-c01730e076a2.png)

It wouldn't be a problem, but after every DB change, the file's name becomes longer and longer. So at one moment, I have received an error message, that the system can not save backup files anymore.
Well, it is not a problem for me. I created a new folder named "backup" and moved there all the backups files besides the last one. And the last file I renamed from "_Main.mmb_update_2021-07-19.mmb_update_2021-07-19.mmb_update_2021-07-19.mmb_update_2021-07-19.mmb_update_2021-07-19.mmb_update_2021-07-19.mmb_update_2021-07-24..._" to "Main.mmb" and the problem was resolved.

**Resume: the system saves and keeps more backup files than it was set.**

# Reproduction

Is the bug reproducible? 
 - [x ] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. 
2. 
3. 

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/3648

**Comment by vomikan** [comment]
It seems that user open newest file in some folder. Then mmex append _updateyyyymmdd.mmb suffix.
I recommend to make shotcut #2387 or open last used file in app start dialogue.

**Comment by tactilis** [comment]
@Dandy64 It appears that you have at some point opened one of the backup .mmb database files in MMEX, instead of your Main.mmb file.

On exit, MMEX will append `_update_YYYY-MM-DD.mmb` to the filename.

Then, next time you ran MMEX, it appears that you opened that new backup .mmb (with the longer filename) instead of your Main.mmb file, adding another `_update_YYYY-MM-DD.mmb` to the filename.  And so on...

This is nothing to do with the `Max Files` limit. That functionality is working correctly.

All you need to do is ensure that you _always_ open your Main.mmb file, or as @vomikan says, open the last used file in the app start dialog (once you know you are dealing the the correct Main.mmb).
