### ISSUE TITLE
warning C4706: assignment within conditional expression

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3740]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

void mmBDDialog::OnsetPrevRepeatDate(wxCommandEvent& WXUNUSED(event))
void mmBDDialog::OnsetNextRepeatDate(wxCommandEvent& WXUNUSED(event))

4>d:\github\moneymanagerex\src\billsdepositsdialog.cpp(1342): warning C4706: assignment within conditional expression
4>d:\github\moneymanagerex\src\billsdepositsdialog.cpp(1363): warning C4706: assignment within conditional expression

```
            if (!valueStr.IsNumber() || !(span = wxAtoi(valueStr))) {
                mmErrorDialogs::ToolTip4Object(textNumRepeats_, _("Invalid value"), _("Error"));
            }
```

**Comment by whalley** [comment]
Whilst the `span = wxAtoi(valueStr)` assignment is correct I have tidied up the code to avoid the warning. However I have spotted that the `mmBDDialog::OnsetPrevRepeatDate` logic is actually in error and does not work for the cases in the switch statement due to the `break` statements. Have tidied to use same method for PREV and NEXT.
