### ISSUE TITLE
Invalid Vector

### ISSUE THREAD

**Issue by Speigy** [moneymanagerex/moneymanagerex#3833]
>The file attached shows the problem. Have reported it before but no response. Tony Speigal
![MMEX eroor](https://user-images.githubusercontent.com/39367770/131655022-c9fcfc54-e508-4745-a832-be8caa59a2d6.jpg)
![MMEX eroor](https://user-images.githubusercontent.com/39367770/131655051-73f78c17-b418-47de-9cb0-31b70ab27bee.jpg)

> Please do not remove information attached below this text.

<hr>Version: 1.5.0-RC.2 64-bit<br>
 • Build: Mar 28 2021 10:06:37<br>
 • db 7 •  (aes128cbc)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.4 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1) • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg <br>
 • libcurl/7.61.0-DEV WinSSL<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19042), 64-bit edition<br>
 •  English (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by tactilis** [comment]
@Speigy
> Version: 1.5.0-RC.2 64-bit
> Build: Mar 28 2021 10:06:37

You are running a very out of date version of MMEX.

The current version is 1.5.6

Please ensure that you have the option set to check for updates and follow the link on the update screen when you next start MMEX to download the latest version.

![image](https://user-images.githubusercontent.com/4060092/131660239-545c441a-1dc6-4786-9188-f021336df145.png)
 
 
Then please update your issue report if the bug is still present in 1.5.6.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/3727

**Comment by vomikan** [comment]
#4129
