### ISSUE TITLE
Translation is partially shown in previously selected language

### ISSUE THREAD

**Issue by tygryk** [moneymanagerex/moneymanagerex#3847]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [X] Mac OSX
 - [ ] Linux 

# Description of the bug

Translation is mixed up: some words are in current language, some word are in the language that was changed to.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Open settings
2. "General" tab
3. Current language is "English"
4. Change to "Belarusan" language
5. Click "Apply" button
6. Confirmation pop-up is shown

Expected result:

All text is either in English. Or all text is in Belarusan.

Actual result:

"General" word is shown in the "previous" language (English). Rest of text is shown in "new" language (Belarusan)

# Additional information

Same happens if reverting from Belarusan to English.

<img width="252" alt="Screen Shot 2021-09-09 at 19 54 36" src="https://user-images.githubusercontent.com/9718911/132730858-676b8330-609b-4f95-8a11-6c850fa6d3bd.png">
<img width="245" alt="Screen Shot 2021-09-09 at 19 55 29" src="https://user-images.githubusercontent.com/9718911/132730863-509748ce-15af-4bb6-bc24-dcfc9c22dbc4.png">

**Comment by lonemadmax** [comment]
Locale changes require a restart of the application to complete and a message is shown indicating so. Content generated before the change will have the strings in the previous language. Content generated after the change may have them in the new one. In the specific case you show (and there are surely more), the "General" string comes from the title of a section of the dialog you had open when you changed the language, so that title was generated before the language change.

I guess in this case we could put the title keys in an array and always retrieve the translation instead of calling GetPageText? There may still be untranslated text in other places, but this one message seems to stand out a bit.

**Comment by tygryk** [comment]
@lonemadmax thank you for the detailed explanation provided

**Comment by vomikan** [comment]
I don't understand the fix.

**Comment by whalley** [comment]
> I don't understand the fix.

I scratched my head at first, and I'm sure @lonemadmax can explain it better...

We create an array with the 'English' names for the pages (using N_(" now to indicate that we want to flag for translation - we can't use _(" as this would try to use wxGetTransation which would not be valid here) we then actually do the translation indirectly via this table each time we need it.

**Comment by vomikan** [comment]
Why N_ but not wxTRANSLATE ?

**Comment by lonemadmax** [comment]
Because N_ is the customary macro in gettext projects and I didn't know about wxTRANSLATE. Reading its documentation it does the same thing, so you may change that if it better aligns with this project.

**Comment by vomikan** [comment]
I did it this way, as it is already used in the code.
