### ISSUE TITLE
OFX Import

### ISSUE THREAD

**Issue by loki36** [moneymanagerex/moneymanagerex#386]
Hi,

there is an ofx import planed for future or not ?
Beacause ofx format is gowing.
A quick win could be include in mmex ofx2qif (an exe on windows and a package dependance on linux)

**Comment by guanlisheng** [comment]
Scheduled it in v1.3

**Comment by guanlisheng** [comment]
@loki36 , would you mind to help to complete this one since no other developer is using OFX

**Comment by loki36** [comment]
with which approch ?
I 've create a way to convert oxf's file to qif with ofx2qif under ubuntu directly from mmex.
I have the exe for Windows but i don't know how to build the windows version and I haven't environment to do it
And I don't know if there is a libofx version with ofx2qif under mac.

I could try to develop directly a parser for ofx but i don't know if i will have enough time

**Comment by guanlisheng** [comment]
I think we have to integrate your code to MMEX then we can import it automatically

**Comment by morphiumdeus** [comment]
The parser doesn't seem difficult, it's the same method as qif import, you just have to check if the line starts with any of those xml elements:
<ACCTTYPE> or <ACCTTYPE2> (= qifLineType AcctType, but only once in my bank ofx file)
<DTPOSTED> (= Date)
<TRNAMT> (= Amount)
<FITID> (=TransNumber)
<NAME> (=Memo)
There are more elements like <CURDEF> (currency) and depending on the bank probably elements for payee, address and so on.

I would love to help and installed MinGW and everything, but I've never worked with c++ and can't seem to get it to work. I could try to write the parser without any debugging, but I'm not sure that would help much?

**Comment by arthurp** [comment]
I may be interested in taking this on. Is the plan mentioned in #448 still valid? Importing https://github.com/libofx/libofx as a submodule. It looks to be lightly maintained and support OFX up to 2.0 (2.2 is the most recent spec released).

**Comment by dbolton** [comment]
Here's how OFX support would improve the efficiency and simplicity of using Money Manager EX
- **No need to set up custom mapping** for each bank account. Unlike CSV, OFX has standard fields.
  - This benefits new users who haven't set up their CSV mappings yet. (They wouldn't need to take the time to learn the CSV import dialog).
  - This benefits longtime users who have multiple financial accounts. (No need to worry about which mapping to use).
- **OFX prevents importing the same transaction twice**. 
  - Every transaction includes a unique FITID (Financial Institution Transaction ID). If Money Manager Ex stores this (either as a new column or a custom column to maintain compatibility), then Money Manager Ex can avoid importing the same transaction twice.
  - Users save time and frustration by download the last 60 days of transactions (or whatever time frame makes sense) rather than carefully finding the last transaction date for each account before downloading and importing more transactions. Money Manage Ex would just ignore the duplicates.
- **OFX is the dominant standard**.
   - OFX publishes detailed specifications online: https://www.ofx.net/downloads.html
   - Unlike QIF, the specification is actively maintained and supported by multiple institutions. 
   - After CSV files, it is the most widely supported file format by financial institutions.

**Comment by mjacr** [comment]
Hello, I'm a new MMX user, and the OFX format is the most common here in Brazil.
I would like to know how difficult it is to implement this option based on the GNUCash implementation.
https://github.com/Gnucash/gnucash/tree/maint/gnucash/import-export/ofx

Is there any documentation for new programmers?
