### ISSUE TITLE
Recurring transactions: repeat monthly on first business day

### ISSUE THREAD

**Issue by iSnackyCracky** [moneymanagerex/moneymanagerex#3921]
# Description of the feature

When setting up a recurring transaction, there are options to repeat it "monthly", "monthly (last day)" or "monthly (last business day)".
I'd like to have the option to repeat transactions monthly on the *first* business day aswell.

# Use cases

I've got a lot of automated transactions on my bank account that (should) occur on the 1. of each month.
But of course every once in a while, the 1. of the month is a saturday or sunday and the bank won't process transactions during the weekend.
Therefore the transactions get executed on the next business day.

**Comment by whalley** [comment]
Having reviewed this and I think it better to wait until we can change some of the DB structure for this rather than adding another item. I'd like to add options to allow weekends to be skipped to prior or next working day as another field. We can do this by multiplexing the data into existing fields as is done with the execute actions... but the code then just gets messier and messier. Suggest we hold off until we agree to allow DB updates...
