### ISSUE TITLE
Autocomplete of "Account" not working on MacOS

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#3988]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Operating System:
 - [ ] Windows
 - [x] Mac OSX
 - [ ] Linux 

# Description of the bug

Auto complete of the 'Account' should be supported on Mac similar to 'Payee' / 'To Account'.

Change should support as below:
![CleanShot 2021-11-09 at 18 56 09](https://user-images.githubusercontent.com/487345/140987164-4eed49bd-cb8e-4de5-a41d-65e90f035df1.png)

Related: #3604

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/140995023-17029ce8-7ef9-4377-901d-10f4fc08ec9f.png)

**Comment by 2BeeOrNot** [comment]
This is tagged fixed and closed but it doesn't work as I expected it to work like for payees.

Using 1.5.10b2 on macOS 12.0.1

In my test database:
I have two bank accounts - checking and savings.
One credit card - MasterCard

1. I am viewing the Checking account in the account view.
2. I add a new transaction.
3. The account is filled in - Checking
4. I want to enter a Savings transaction.
5. Clicking on the drop down arrow only lists the Checking account. I expected all accounts to be listed. This is what happens in 1.5.9.
6. Checking is selected in the edit box. Pressing delete allows me to use auto fill but clicking on the drop down arrow still only pops up with Checking.
7. I use auto fill to select the Savings account. Clicking the drop down arrow only lists Savings. I expected all accounts to be listed.
8. I'm starting at number 6 again. Instead of deleting the selected account I delete it character by character. After deleting the last character all accounts are listed as expected.
9. I select Savings.
10. Now if I click on the drop down arrow all accounts are listed.

Entering a new transaction from the All Transactions views seems to work as expected.

Editing a transaction is like number 1 to number 10.

Clear as mud? Is it just me?

**Comment by whalley** [comment]
I can reproduce... Poor testing on my part obvioulsy.

**Comment by whalley** [comment]
Should be fixed (again) now. https://mmex.ipx.co.uk/builds/beta/mmex-1.5.10-Beta.2-Darwin-2021-11-12.dmg

**Comment by 2BeeOrNot** [comment]
Forbidden

You don't have permission to access this resource.
Apache/2.4.29 (Ubuntu) Server at mmex.ipx.co.uk Port 443

**Comment by whalley** [comment]
Try now!
