### ISSUE TITLE
Jump between accounts along the "Transfer" transaction

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#4110]
# Description of the feature

When I display a Transfer transaction in one account, it would be nice to have an ability (keystroke or menu) to jump directly (onscreen) to the corresponding transaction in the another account. Not just replacing a current account displayed but also focusing on the relevant date.

(I used it quite often in Quicken since 1995 or so)

https://forum.moneymanagerex.org/viewtopic.php?t=10546

**Comment by whalley** [comment]
Have added right-click menu option to support this.
![CleanShot 2022-01-13 at 00 42 29](https://user-images.githubusercontent.com/487345/149245561-e75d53bd-bd46-40e1-85bd-ab3ce20c9660.png)

**Comment by tactilis** [comment]
@whalley 'View in Other Account' works as intended and will be a great timesaver.

It would be even more helpful if the target transaction in the other account could be selected when it is displayed. I find it difficult to visually locate the target in the list.

Since you are coming from a selected transaction in the first account, and it's actually the _same_ transaction in the other account, it feels right to me that it should be selected.

**Comment by vomikan** [comment]
It's working fine for me with simple-black theme

![image](https://user-images.githubusercontent.com/6836805/149338573-b9eb990e-b150-401b-b710-56affe0c36b6.png)
