### ISSUE TITLE
Time to renew website certificate

### ISSUE THREAD

**Issue by 2BeeOrNot** [moneymanagerex/moneymanagerex#4117]
Maybe you already know. Maybe you don't.

![MMEX Cert](https://user-images.githubusercontent.com/63317977/149801444-90619b14-e97c-4517-bd1f-462384438e03.jpg)

**Comment by whalley** [comment]
Seems to have been renewed but only until Tuesday, 19 April 2022 at 05:44:52 British Summer Time

![CleanShot 2022-01-19 at 23 56 05](https://user-images.githubusercontent.com/487345/150237383-50b46f7a-72cd-402e-824d-e176cdc70f73.png)

**Comment by tactilis** [comment]
A lot of people rely on MMEX and I'm a little concerned about what would happen if @guanlisheng was suddenly no longer around due to accident/serious illness/anything major happening.

Other projects have been brought down by lack of written procedures, no knowledge of hosting passwords, ability to pay the bills (if applicable), etc.

So, can I ask please whether, as a project, MMEX has any single points of administrative failure? And if so, can we do something about it?

Anything I can do to help?

**Comment by whalley** [comment]
Great point, we should do this.
