### ISSUE TITLE
No RELEASE FILE

### ISSUE THREAD

**Issue by id027102** [moneymanagerex/moneymanagerex#4135]
MMEX version:
 - [x] 1.3.4 Newer versions NOT available on repositories
 - [ ] 1.6.x

Operating System:
 - [x] Linux 

# Description of the bug
DEBIAN
No RELEASE FILE in linux repositories from bookworm on. 
Repositoriy for bulleyes has version 1.3.4

 + more that is not working

Removed repository and app until beter follow and support

**Comment by mmm4m5m** [comment]
@vomikan - For your information:
(Here because I do not have registration in the forum. Sorry.)

Installation of MMEX 1.5.14 on Debian bullseye:
```
# wget https://repos.codelite.org/wx3.1.5/debian/pool/libs/w/wxwidgets3.1/wx3.1-i18n_3.1.5-2.bullseye_all.deb
# wget https://github.com/moneymanagerex/moneymanagerex/releases/download/v1.5.14/mmex_1.5.14-1.focal_amd64.deb

# dpkg -i wx3.1-i18n_3.1.5-2.bullseye_all.deb 
Preparing to unpack .../wx3.1-i18n_3.1.5-2.bullseye_all.deb ...
Unpacking wx3.1-i18n (3.1.5-2.bullseye) ...
Setting up wx3.1-i18n (3.1.5-2.bullseye) ...

# dpkg -i mmex_1.5.14-1.focal_amd64.deb 
Preparing to unpack .../mmex_1.5.14-1.focal_amd64.deb ...
Unpacking mmex (1.5.14-1~focal) over (1.5.14-1~focal) ...
Setting up mmex (1.5.14-1~focal) ...
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for mailcap (3.69) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
#
```

1. App start, Create New DB - OK
2. Open old DB created 2019-01 using Android MMEX app - OK

Thank you!

![image](https://user-images.githubusercontent.com/995706/174267791-452e7d23-703e-458e-86b0-1a429b5bf827.png)
