### ISSUE TITLE
Minor GUI problem: Closed account - icon color 

### ISSUE THREAD

**Issue by Dandy64** [moneymanagerex/moneymanagerex#4223]
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

**# Reproduction**

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

**Reproduction steps:**

1. Create an account.
2. Change the default icon for any other icon.
3. Edit account -> close it

**Expected result:**
The icon of the closed account became black and white.

**Actual result:**
Nothing changed, the icon did not change its color to black and white.

**# Additional information**
It works for the default icon with no problem.
![image](https://user-images.githubusercontent.com/83161661/154816971-670291d6-a87e-4dcc-bd9d-938b43cd7bdb.png)
But it doesn't work for any other icon:
1. 
![image](https://user-images.githubusercontent.com/83161661/154817044-524ffffb-35ea-47c4-8bac-1bc110ac63c7.png)
2.
![image](https://user-images.githubusercontent.com/83161661/154817074-f01f7028-a8b0-42e4-ad56-39b205311c36.png)
3.
![image](https://user-images.githubusercontent.com/83161661/154817127-b4839187-864c-47b8-88db-e891c2e6df42.png)

**Comment by vomikan** [comment]
@whalley We have all these symbols in SVG format. Probably, we can apply some kind of mask or we will have to finish drawing the missing icons for this. I would like to avoid the latter.

https://github.com/moneymanagerex/themes/tree/master/system-themes/simple-black/accounticons

**Comment by tactilis** [comment]
> Probably, we can apply some kind of mask or we will have to finish drawing the missing icons for this. I would like to avoid the latter. I would like to avoid the latter.

Rather than having greyed out icons for closed accounts (or icons with a red cross through them in the colorful theme), that only work when the default icon is used, we could sidestep the whole problem of redrawing or masking the icons by applying strikethrough to the text of closed accounts (and leave the icons alone).

For example:

![image](https://user-images.githubusercontent.com/4060092/154844561-4a8624f5-1929-4bc3-9ddc-d846e9b06758.png)

Easier to implement and, IMO, _much_ easier to differentiate between open and closed accounts.

**Comment by vomikan** [comment]
https://forums.wxwidgets.org/viewtopic.php?t=24698

**Comment by tactilis** [comment]
> https://forums.wxwidgets.org/viewtopic.php?t=24698

wxWidgets is such a pain sometimes!

That discussion was 13 years ago. One would hope that it had been improved since then (perhaps).

I really like the strikethrough presentation of closed accounts because visually it's much clearer.

**Comment by whalley** [comment]
How about wxFONTSTYLE_ITALIC ? Not quite a direct as strikethrough but will help distinguish the account status?

**Comment by tactilis** [comment]
> How about wxFONTSTYLE_ITALIC ?

I already mocked that up to see what it looked like. Unfortunately the italicized text does not stand out at all well from the regular text in the list. Certainly not enough to suggest a closed account or anything special.

**Comment by Dandy64** [comment]
Well, there is a very limited number of icons. I suppose that the easiest way is to have 2 versions of every image - regular and paled or black and white.

If Account type = close then **Paled_Image.SVG**
       Else
           **Regular_Image.SVG**

**Comment by tactilis** [comment]
>If Account type = close then Paled_Image.SVG
>Else
>Regular_Image.SVG
>
>Something like that...

Ha ha! So easy to write that. Just a small matter of programming!!

>I suppose that the easiest way is to have 2 versions of every image

This _is_ understood. It is what @vomikan wants to avoid having to do.

It would also place a burden on all _future_ creators of themes to produce two sets of icons (open and closed) for all the default icons _and_ the alternative icons.

**Comment by whalley** [comment]
One other option to consider is having a single icon to represent a closed account.

**Comment by Dandy64** [comment]
_"It would also place a burden on all future creators of themes to produce two sets of icons (open and closed) for all the default icons and the alternative icons."_

Agree. I have not thought about it.

"One other option to consider is having a single icon to represent a closed account."

Probably this is a very good solution!

**Comment by vomikan** [comment]
https://www.svgrepo.com/vectors/closed/
![](https://www.svgrepo.com/show/376227/status-failed.svg)

**Comment by tactilis** [comment]
Mock up using the first closed svg:

![image](https://user-images.githubusercontent.com/4060092/154950562-c51a81ec-943f-4b0e-aedb-5ba661ebbd29.png)

**Comment by Dandy64** [comment]
> Not sure what you'd do with the yellow-blue and colorful themes to make them look OK:

![image](https://user-images.githubusercontent.com/83161661/154954005-de438677-3926-47b8-90da-e26beaff21fa.png)

**Comment by whalley** [comment]
Single icon per theme.

**Comment by tactilis** [comment]
Looks nice. And neatly solves the original problem that @Dandy64 raised.

![image](https://user-images.githubusercontent.com/4060092/155034039-a7045c98-cc90-4edc-bae4-a24e37afb86c.png)

**Comment by tactilis** [comment]
This is what it would look like if the inside of the closed account icons was transparent.

![image](https://user-images.githubusercontent.com/4060092/155034640-d3f10dff-3f2f-457c-a6d5-0b625879e5f8.png)

IMO, this is preferable to the filled icons, which visually 'jump out' at you a little too much.

**Comment by whalley** [comment]
Feel free to change the icons. I'm OK with that.

**Comment by 2BeeOrNot** [comment]
I modified the new closed account icon color to match my theme. It worked on macOS 1.5.14 with beta builds dated 2.23.2022 and 3.4.2022. It does not work on build dated 3.6.2022. Instead of the new account closed icon it uses CURR.SVG. Same with switching to default theme and MMEX yellow-blue theme. Is it just me?
![Closed 2](https://user-images.githubusercontent.com/63317977/157141227-2e584182-6ada-4e30-abcb-16cdd1984c74.jpg)
![Closed 1](https://user-images.githubusercontent.com/63317977/157141233-4a8cf372-ae99-42a3-bb27-d68b0cd44857.jpg)

**Comment by whalley** [comment]
Will have a look, sounds like a build issue not picking up latest theme files.

**Comment by whalley** [comment]
@2BeeOrNot I can't reproduce this using the latest MacOS beta (2022-03-06).

**Comment by 2BeeOrNot** [comment]
Happens with 3-6 build for me. OK with builds before. Tried making new DB. Same results. Attached is a new test DB I created on macOS with 3-6 build. Changed theme to MMEX default. Renamed my themes folder so it wouldn't be used. Restarted MMEX. Same issue.

After I first reported this issue I tried it on my old Windows 7 PC. Same issue with portable build for 'fix(#4241) icon size fix' and newer builds. OK with older builds. Additionally I got an error on opening MMEX that an icon couldn't be added to the list.

[Testing Closed Accct.zip](https://github.com/moneymanagerex/moneymanagerex/files/8219030/Testing.Closed.Accct.zip)

**Comment by whalley** [comment]
Looks fine...

![CleanShot 2022-03-10 at 00 10 10](https://user-images.githubusercontent.com/487345/157560995-ad677c1d-9610-4951-b126-66bec9f66f35.png)

**Comment by 2BeeOrNot** [comment]
Why me? Why Mac and PC? Why is icon other than default icon the next icon except if I choose the last icon I get no icon?

I downloaded maxOS 3-6 version again. Deleted mmexini.db3 . Same results.

**Comment by 2BeeOrNot** [comment]
I've got in working on my old Windows 7 PC. Seems to be location of mmexini.db3 using portable version of MMEX ( AppData/Roaming vs. folder where MMEX portable installed) when I created new folder for latest 1.5.14 beta version while keeping folder of Mar 6 beta and folder for current release version.

macOS may be related. The Mac I use for looking at betas is not the one I use for live use. Any suggestions for looking at betas and having the release version installed too and location mmexini.db3?

**Comment by whalley** [comment]
> macOS may be related. The Mac I use for looking at betas is not the one I use for live use. Any suggestions for looking at betas and having the release version installed too and location mmexini.db3?

You consider using the command line invocation....
```
% /Applications/mmex.app/Contents/MacOS/mmex -h
Usage: mmex [-h] [-s] [-i <str>] [database file]
  -h, --help         	
  -s, --silent       	Do not show warning messages at startup.
  -i, --mmexini=<str>	where <str> is a path to mmexini.db3

To open a determined database(.mmb) file from a shortcut or command line, set the path to the database file as a parameter.

The file with the application settings mmexini.db3 can be used separately. Otherwise, it is taken from the home directory or the root folder of the application.
```

Here you can specify the dbfile and ini file locations.

**Comment by 2BeeOrNot** [comment]
I'll try that but I don't think it is related to my issue with the closed icon on macOS with latest beta. On my Macbook Pro I deleted:
mmexini.db3
mmex.app
org.moneymanagerex.mmex.plist
org.moneymanagerex.mmex folders
And still I get the acc_money icon for the icon of closed accounts. And selecting a icon for open accounts other than the default always gets me the next icon in the list.

Then I tried on a Macbook Air that never had MMEX installed. Installed latest beta. Same results. No custom themes installed so no changes to master.css or home_page.htt.

I give up. I changed the acc_money.svg icon to be the account closed icon in my theme. Now I have the account closed icon and I don't miss not having the acc_money icon since I am using the default icons. The mmexini.db3 was created in Users/<user name>/Library/Application Support/MoneyManagerEx

**Comment by whalley** [comment]
No really sure what else to try. Have re-built using latest code..

https://mmex.ipx.co.uk/

**Comment by 2BeeOrNot** [comment]
Latest macOS build has same problem for me.

On Windows it started with the fix icon size update. I have three builds: March 6, March 8 and March 11.
March 6 works OK. Both March 8 and March 11 give me this message when MMEX starts:
![MMEX 1514 Win7](https://user-images.githubusercontent.com/63317977/157987524-ac4f2228-6c3b-47f0-9b5e-cb86107d4674.png)

I noticed in the code below for this update the loan icon doesn't have a size:
![Loan Acct Code](https://user-images.githubusercontent.com/63317977/157987599-52ee4e05-0626-40c0-b8d7-0c65f9c0a74c.png)

If I setup a loan I get the account closed icon instead of the loan icon. Could this be the problem of my issues? The savings account below is closed.
![Loan Acct](https://user-images.githubusercontent.com/63317977/157987704-7a0955de-701e-4022-84b1-92e90387887e.png)

**Comment by whalley** [comment]
That is definitely an error, not sure if it fixes your issue... but maybe.  New beta uploaded.

**Comment by 2BeeOrNot** [comment]
Yeah! Seems to have fixed my issues with macOS and Windows too.
