### ISSUE TITLE
“Payee” Concept Misunderstanding?

### ISSUE THREAD

**Issue by OdinVex** [moneymanagerex/moneymanagerex#4297]
I've been reading the MMEX “help” to try and learn this software, but it seems that MMEX uses the term Payee contrary to its meaning. A Payee is the person or entity that ***receives*** payment. If someone gives us money, *we* are the Payee. If we give them money, *they* are the Payee.

Perhaps I'm just not following? Original text:

“In MMEX, the people that give us money or receive our money are regarded as the Payees of the system.”

**Comment by tactilis** [comment]
It's just convenient shorthand terminology.

If MMEX didn't define Payee in the way it says in the help, then the 'Payee' column heading would need to say 'Payee or Payer', which is very clumsy.

As the help says:

"“**In MMEX**, the people that give us money or receive our money **are _regarded_ as** the Payees of the system.”

Other money management applications follow the the same approach to naming:

![image](https://user-images.githubusercontent.com/4060092/163723386-fb4aebbb-8e57-4ad4-9bd2-f2e30478fd10.png)

**Comment by OdinVex** [comment]
I feel there must be a better word that Payee. Attempting to redefine such a common word doesn't make it so, it just confuses.

**Comment by tactilis** [comment]
> I feel there must be a better word that Payee.

Please feel free to suggest one. Make sure it works in other languages too.


> Attempting to redefine such a common word doesn't make it so, it just confuses.

The Help makes it very clear how Payee is used _in_ MMEX.  The same applies to (many) other money management applications.

**Comment by OdinVex** [comment]
> Please feel free to suggest one. Make sure it works in other languages too.

No singular word needs to work across multiple languages. There are words for things in one language not found in another.

> The Help makes it very clear how Payee is used _in_ MMEX. The same applies to (many) other money management applications.

The redefinition of such a common word is the issue, though. In my mind, I can't make the difference. It'd be like calling both the buyer and seller of a transaction as “buyers”. It makes no sense to me. Granted, that might be because I have an *actual payee*. I haven't seen any other money-management software using Payee to mean both. I'm in earnest, here.

**Comment by renato-mmex** [comment]
I would welcome a constructive proposal

**Comment by tactilis** [comment]
> No singular word needs to work across multiple languages

Sorry, I wasn't clear enough. What I meant was that whatever English term you suggest for Payee/Payer, needs to be translatable into multiple languages, otherwise you aren't solving the MMEX problem that you say exists.

> I haven't seen any other money-management software using Payee to mean both. I'm in earnest, here.

I showed you an example above. That was Ace Money.  Others apps use Payee in the same way.

> The redefinition of such a common word is the issue, though. In my mind, I can't make the difference.

Possibly MMEX and the other money manager apps that use Payee like this are not suitable for you. 

> I feel there must be a better word that Payee.

Again, all you have to do is propose a word that would be suitable for use everywhere MMEX currently uses 'Payee' and the developers will certainly consider its merits.

**Comment by OdinVex** [comment]
> > No singular word needs to work across multiple languages
> 
> Sorry, I wasn't clear enough. What I meant was that whatever English term you suggest for Payee/Payer, needs to be translatable into multiple languages, otherwise you aren't solving the MMEX problem that you say exists.
> 
> > I haven't seen any other money-management software using Payee to mean both. I'm in earnest, here.
> 
> I showed you an example above. That was Ace Money. Others apps use Payee in the same way.
> 
> > The redefinition of such a common word is the issue, though. In my mind, I can't make the difference.
> 
> Possibly MMEX and the other money manager apps that use Payee like this are not suitable for you.
> 
> > I feel there must be a better word that Payee.
> 
> Again, all you have to do is propose a word that would be suitable for use everywhere MMEX currently uses 'Payee' and the developers will certainly consider its merits.

Any term(s) used to replace wouldn't necessarily need to be translated into other languages. Some languages use a single context-derived word for something other languages might have more than one word for. The problem exists if one is aware of the English definition of “payee”. I never saw any “Ace Money”, there's a random image that could've come from anywhere, it isn't labeled, maybe it's a spreadsheet? I'm merely pointing out the definition doesn't suit the word's use. Although this isn't as constructive, it's still noteworthy. I don't have any proposed word(s) except perhaps Payer and Payee, which are used in law for transactions to describe.

**Comment by tactilis** [comment]
> I never saw any “Ace Money”, there's a random image that could've come from anywhere, it isn't labeled, it could have been a spreadsheet for all I could know.

My apologies, I was just posting a small image.

Here's a full screenshot of Ace Money showing the use of Payee for Withdrawals and Deposits (and Transfers), exactly as MMEX uses the term.

![image](https://user-images.githubusercontent.com/4060092/163781326-21205d70-9296-4553-90c8-0b18b313c125.png)
 
 
And here's MoneyLine:

![image](https://user-images.githubusercontent.com/4060092/163786431-fbbcc477-e103-4422-9aa8-e679d26029ba.png)
 
 
And Quicken:

![image](https://user-images.githubusercontent.com/4060092/163786497-a6bbd2e7-d616-49d3-bbe0-3863619566c0.png)
 
 
You say:
 
> I don't have any proposed word(s)

And that is exactly the point. Neither did the developers of MMEX have a single word that means "Payer _or_ Payee".

In all the years that MMEX has existed, there has been a _single_ column that shows where Withdrawals go to and where Deposits come from. That column needs a Name. Its name in MMEX is 'Payee', which MMEX defines as:

_“In MMEX, the people that give us money or receive our money are **regarded as the Payees of the system**.”_

You are objecting to this. Your objection has been heard and is understood.

You say _"I feel there must be a better word than Payee"_ but you haven't proposed a better word for use as the column heading and elsewhere in MMEX. So nothing can be changed by the developers because they don't have a better word either. 

Other applications have faced the same issue and have chosen the same solution.

The easiest thing to do is just _use_ MMEX and accept that the word 'Payee' is used in a flexible way. It's very clear from the Withdrawal and Deposit columns whether money is going out or coming in to an account. It's not hard. Just accept it. Thousands of users of MMEX are happy to do this.

If this is too much to accept, then you might be happier with a different application (but not Ace Money, MoneyLine, Quicken...)

**Comment by OdinVex** [comment]
> Here's a full screenshot of Ace Money showing the use of Payee for Withdrawals and Deposits (and Transfers), exactly as MMEX uses the term.

It looks like they only use it in one context, though, which is fine (the “From”). MMEX seems to use it in both, which is incorrect.
> You say: ...

It's called changed.

> ... which MMEX defines as ...

Right back at this again, you can't just redefine such a common term.

> ... you haven't proposed a better word ...

I did suggest Payer and Payee. Not one word. There is no singular word that I'm aware of that can mean both.

> ... Thousands of users of MMEX are happy to do this.

That was a fast poll, I missed it.

> If this is too much to accept, then you might be happier with a different application (but not Ace Money, MoneyLine, Quicken...)

The concept of the direction of transactional flow is beyond the scope of MMEX, got it, paper and pen.

**Comment by tactilis** [comment]
I've explained how MMEX works, and why it needs one word.

This is now a pointless discussion. 

I'm out.

**Comment by whalley** [comment]
Closing
