### ISSUE TITLE
lunasvg v2.3.1 now available

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#4302]
https://github.com/sammycage/lunasvg/releases/tag/v2.3.1

**Comment by whalley** [comment]
@vomikan Not going to get a chance to review this on MacOS for another week due to other commitments.

It should also be noted that wxWidgets from 3.1.6 includes native support for SVG handling via [nanoSVG](https://github.com/memononen/nanosvg/issues/201), see: https://docs.wxwidgets.org/trunk/classwx_bitmap_bundle.html. but as noted in https://github.com/moneymanagerex/moneymanagerex/issues/4301 there are issues with 3.1.6 on MacOS.

**Comment by vomikan** [comment]
Minor changes have been made in this library. This should not negatively affect the operation of the application on different platforms. We cannot replace this library in the near future. I think the update is appropriate.

**Comment by whalley** [comment]
I seem to be getting duotone image scaling issues with the latest lunasvg. See below

After lunasvg change
![CleanShot 2022-05-03 at 00 13 15](https://user-images.githubusercontent.com/487345/166340971-5ac06670-24c2-4948-8a41-c5228071fccf.png)

Prior to lunasvg change:

![CleanShot 2022-05-03 at 00 15 24](https://user-images.githubusercontent.com/487345/166341185-b928b2ec-4e93-4288-90ca-ae8f8a3dbed5.png)

**Comment by whalley** [comment]
Panic over.... Must have had something lying around. Did a clean build and it works fine.
