### ISSUE TITLE
Add credit limit to credit card accounts

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/moneymanagerex#451]
Credit card accounts usually involve a credit limit and it can be costly to hit this or go over. It would be useful to indicate how far is the credit on the credit card from this limit. This can be indicated visually.
For this there needs to be a limit value stored in the database.
If you agree, could you provide some hints in regards to where this would be stored so that we can also work on implementation for the Android version?
Cheers

**Comment by AlessandroLazzari** [comment]
:+1:

**Comment by stef145g** [comment]
:+1:  I like it. Hopefully we can work together and define the specifications first.

-------------------------------
Starting this discussion...
This would involve adding several fields to the Account table to expand the functionality.

**Proposal**
Provide a new table providing a 1 - 1 relationship, linking the credit record to the account record.

**New table Name:** CREDIT_V1
**Fields:**
CREDITID - integer ... primary Key
ACCOUNTID - integer  ... the associated account id.
MAXLIMIT - numeric ... Upper credit card limit.
DUEDATE - text (date) ... data at which extra charges could be added
INTERESTRATE - numeric ... working out interest charges if any.
AMOUNT: numeric ... useful for providing a fixed repayment amount if necessary.

**Comment by stef145g** [comment]
Suggestion of changing **ID** field names in a table as follows:
CREDITID ...... set to **ID** .... primary field.
ACCOUNTID .. set to **ID_ACCOUNT**
This would allow easy identification of links, especially if there are a many links in the table.
Old tables cannot be changed for obvious reasons, but suggested for new tables use.

**Comment by giuseppepaoletti** [comment]
Hi all,
sorry to say that in the past month I've had no time to dedicate to this 
project, due to work and family problems.
Regarding to advanced credit card information, I have started to develop 
a similar solution, but haven't done any commit for the above problems.
I've added a new table, named CREDITCARD_V1, with those fields:
CARDID integer primary key
ACCOUNTID integer NOT NULL UNIQUE (credit card account id)
HELDAT integer (bank account where card is helded and money will be 
withdrawed)
CARDTYPE integer (debit, credit (partial refund or revolving), credit 
(full refund))
RATE numeric (interest rate)
CARDLIMIT numeric (credit card limit)
Those are the fields added to account dialog properties:

New features are:
- warning message when credit card limit is reached
- automatic creation of a recurring transaction if "Auto Balance" is 
checked; if card is a credit card with partial refund, balance amount 
will be used, otherwise if it's a full refund, it will use the sum of 
all monthly transactions
- on homepage, credit card upcoming transaction have the total monthly 
amount

The only field that's missing is the DUEDATE, and it can be added.
What do you think?

Il 15/04/2015 02:40, Stefano ha scritto:

**Comment by MisterY** [comment]
Very good. A combination of fields from both suggestions would be great and offer more possibilities in the future. Minimum payment amount, due date, payment date, etc. These would allow for the features similar to what  @giuseppepaoletti listed. A recurring transaction used for credit card payment, that takes (or at least suggests) the full credit amount, or a minimum payment amount, would be a great feature.
The other, as I've mentioned, a progress-bar-style representation of the credit amount vs credit limit, woud be a great start.

Btw, isn't "HeldAt" institution already specified in the account information? Although, sometimes they are not the same, I agree. For example, I used to have a credit card issued by a small operator (28 Degrees), that was only a re-branded solution from GE Money, which operated the accounts. Well, these are two different situations, so the more information we have, the better.

**Comment by giuseppepaoletti** [comment]
Yes, "HeldAt" is already there, but only as a text field; with the 
account id we can automatically transfer monthly amount from bank 
account to credit card account.

Il 15/04/2015 09:11, Alen Siljak ha scritto:

**Comment by stef145g** [comment]
Excellent.
It appears that we have similar ideas, but @giuseppepaoletti is more advanced.
Since you already have a plan in mind, please reassign this to issue to yourself.

--------------
Comparing the 2, we have 4 similar fields differently named , and 2 unique fields from each. This leads to 2 fields being added to the existing created table.
DUEDATE - text (date) ... data at which extra charges could be added
AMOUNT: numeric ... useful for providing a fixed repayment amount if necessary.

This table could also be used to allow automatic Loan repayments to be repaid as fixed payments on the DUEDATE. This would complement my plan to provide a better solution for Stocks and Shares and for Assets and Loans. Ref: https://github.com/moneymanagerex/moneymanagerex/issues/336

As far as I am aware, the Minimum payment amount is usually a calculated field being 10% of the total amount. This leads to a possible new field being:
MINPAYMENTRATE: numeric ... minimum payment rate percentage.
... Allows the actual minimum payment to be calculated on the balance at the DUEDATE.
Dangers in paying the minimum amount that is that most times this is slightly below the interest rate.

Amounts other than a fixed payment amount would be calculated fields and therefore not stored.

**Comment by thehobbit78** [comment]
I think that in the next days I can make a commit of what I've already done, adding of course those two missing fields.

Il 15/04/2015 16:28, Stefano ha scritto:

Excellent.
It appears that we have similar ideas, but @giuseppepaoletti<https://github.com/giuseppepaoletti> is more advanced.
Since you already have a plan in mind, please reassign this to issue to yourself.

________________________________

Comparing the 2, we have 4 similar fields differently named , and 2 unique fields from each. This leads to 2 fields being added to the existing created table.
DUEDATE - text (date) ... data at which extra charges could be added
AMOUNT: numeric ... useful for providing a fixed repayment amount if necessary.

This table could also be used to allow automatic Loan repayments to be repaid as fixed payments on the DUEDATE. This would complement my plan to provide a better solution for Stocks and Shares and for Assets and Loans. Ref: #336<https://github.com/moneymanagerex/moneymanagerex/issues/336>

As far as I am aware, the Minimum payment amount is usually a calculated field being 10% of the total amount. This leads to a possible new field being:
MINPAYMENTRATE: numeric ... minimum payment rate percentage.
... Allows the actual minimum payment to be calculated on the balance at the DUEDATE.
Dangers in paying the minimum amount that is that most times this is slightly below the interest rate.

Amounts other than a fixed payment amount would be calculated fields and therefore not stored.

—
Reply to this email directly or view it on GitHub<https://github.com/moneymanagerex/moneymanagerex/issues/451#issuecomment-93422748>.


________________________________
Software Department
software@teseo.com

-------------------------------------------------------------------------------------------------------------
TESEO spa via Agnelli, 49 63023 FERMO (FM) ITALY
Tel. +39 0734 628818 -- Fax. +39 0734 628816

Disclaimer: This electronic mail transmission may contain legally privileged and/or confidential information. Do not read this if you are not the person(s) named. Any use, distribution, copying or disclosure by any other person is strictly prohibited. If you receive this transmission by mistake destroy the original transmission and its attachments without reading or saving in any manner.

**Comment by guanlisheng** [comment]
Could we reuse the initial value?

**Comment by stef145g** [comment]
@guanlisheng Sorry, but I don't understand your question.

**Comment by guanlisheng** [comment]
I meant use initial for credit limit purpose

**Comment by MisterY** [comment]
How would one know how far they are from the credit limit in that case?

**Comment by guanlisheng** [comment]
I don't think a credit card needs the initial value

**Comment by MisterY** [comment]
Here's my opinion.
On one hand, it would be missusing the field for a different purpose, which is potentially confusing.

But the more important thing is that we **do** need the initial value. No more but no less than in other type of accounts.
For example, I have a habit of exporting the transactions occasionally and resetting the initial balances to their real balances. Hijacking the initial amount field for Credit Card would prevent that feature from working in this type of account but not in the others. This could be quite confusing for other users, too.

Instead, why not add a new field like "Maximum Value", or something similar, that could be reused for all account types? For example, credit accounts would use it as a credit limit. (I hope we are to support other types of credit accounts in the future, like loans). Positive-balance-accounts could use it for similar reminders which, after the balance reaches them, they trigger a notification. Quicken has a similar feature, if I'm not mistaken.

As a general rule, I'd always go for adding features rather than removing them.

**Comment by vomikan** [comment]
Just an idea...
to add some functionality table credit_v1 has added (for example).
But may be better to create accounts_v2 table. Account_v2 may have more
addition fields like limit, loan percentage, image (logo) etc.


понедельник, 20 апреля 2015 г. пользователь Alen Siljak написал:

**Comment by AlessandroLazzari** [comment]
I connect to the comment by Nikolay. IMO there is no need to create new
entities, but perhaps it would be easier to modify the table ACCOUNTLIST_V1
by adding the information that we need?
​

**Comment by guanlisheng** [comment]
I think the existing column is enough.
For the confusion,  we can add comments to scheme and use the different function name in application to distinguish them for different accounts.

For the last rule, my goal is to reduce the under features. I have created some issues to disable the ability to choose the language since the more straightforward way is to determine it automatically.

LiSheng

**Comment by MisterY** [comment]
I wonder what are the benefits of removing the existing working features. As I've mentioned, I am actively using the initial balance on credit cards. Now you are suggesting to remove the feature. That makes for a defective application, in my view. 

As for the language selection, how would you decide which language the user wants to use?

**Comment by guanlisheng** [comment]
What's the meaning of the initial value for credit card? Normally there is no such concept.

Most of the end users should follow it's OS language setting while the maintenance cost is pretty high 

LiSheng

**Comment by MisterY** [comment]
:) 
The meaning of initial balance for credit card is the same as the meaning of initial balance for any other type of account. This is the starting balance of the account. 
Since there already is this concept in the application, I would expect it to work for any type of account. This is also one of the reasons why I like this software compared to some others - it allows me to make decisions and do the work for me. **Not** the other way around - that the software makes the decisions for me and I have to do all the work.

I'm not sure why the language setting got into this discussion and, after the latest explanation, I am not sure what it actually refers to. In Android we have localizations and they are extremely useful. People can change which language they want to have the application in.
I agree that the initial selection should depend on the system rather than be English by default. But it is still very useful to have the ability to switch languages. For example, I can also using Bosnian locale but there is no such setting on some platforms. 
However, let's stick to credit card limits only in this discussion. Thanks for the explanations.

**Comment by guanlisheng** [comment]
To be honest, I still think credit card should have zero initial balance 

LiSheng

**Comment by MisterY** [comment]
Fair enough but please don't implement it.

**Comment by stef145g** [comment]
All Credit Card accounts would start their life with a Zero balance in the real world. In the MMEX world the Credit Card account as for any account, would generally be initialised from an existing real world account.

When a user gets their credit card statement, there is a **Brought Forward** balance. A new MMEX user wanting to track their continuing account using MMEX would need to replicate this. This is achieved by recording the **Brought Forward** balance as the **Initial Balance** field.

A work around, such as recording the **Brought Forward** balance as a transaction would upset the reports as this is not an income or an expense. It cannot be done as a transfer because it requires another account. (Messy!!)

For this reason, the Initial Balance field in MMEX must exist for **all** accounts.

**Comment by gabriele-v** [comment]
Credit card implementation it's really poor, it needs also an auto transfer every month that goes ahead of limit. 

I think that we need another table to store this credit card settings, like limit, when reconcile, commissions, percentage etc..

**Comment by vomikan** [comment]
Just discovered ... Add additional column into DB is quite easy, for example:
~~~~~
ALTER TABLE accountlist_v1 ADD COLUMN Credit_limit number
~~~~~
If some new field will be added for new version of mmex it's not a problem for older release.

**Comment by gabriele-v** [comment]
Yes, but how to concile with existing model?
We need to review model to patch DB at startup, using database version as suggested by android developer..

**Comment by stef145g** [comment]
Updating an old database version at start-up can be done as this is already being done,
Ref: https://github.com/moneymanagerex/moneymanagerex/blob/master/src/mmframe.cpp#L1707
This would also suggest that MMEX version would need to be Version 2.x.x

The only thing we need to agree to is: what fields need to be added, to maintain a stable database version. We don't want to be continually adding fields to the database.

**Comment by stef145g** [comment]
This feature has now been set up using a 'json store'.

Extra account data is stored for each account in the table: INFOTABLE_V1 using json string variables.
The implementation contains: Credit Limit and Minimum value. The difference is that the Credit limit will be used as a negative value. Extra info under the Credit tab is not used at this stage.

Edit the account to set the initial values.

**Comment by stef145g** [comment]
New fields have been added to the account table:
, CREDITLIMIT numeric
, INTERESTRATE numeric
, PAYMENTDUEDATE text
, MINIMUMPAYMENT numeric

The field CREDITLIMIT is used and is set as a positive value, but is used as a negative value. 0 to disable it. This is used to warn the user if a payment will exceed the credit limit.
Example: If a Credit limit of $2000 is set, then when a withdrawal is made that the resulting balance will exceed $-2000, the user will be warned this transaction will exceed the credit limit.

The other fields are not used at this stage
The fields PAYMENTDUEDATE  and MINIMUMPAYMENT can be utilized to warn the user of pending activity on Credit cards.
Example:
A check could be made at start up similar to recurring transactions using the following logic:
If the Minimum Payment is not zero and a deposit is not registered within a 10 days of the payment due date then warn the user that the account could incur extra charges.

This could be discussed in another topic. Closing this at this point.

**Comment by MisterY** [comment]
Great work, thanks! I'll follow these guidelines in implementing the limit (and the debt progress bar) in the mobile app.
