### ISSUE TITLE
Cash account type

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/moneymanagerex#455]
This may have been discussed earlier. Is there a reason that there is no dedicated account type for cash accounts? I know that technically they are the same as checking accounts but in practice the difference is significant.
Especially when travelling, I would like to throw a glance at the balance of cash accounts in different currencies rather than mixing them with bank accounts from which I would get the funds at an ATM.

**Comment by vomikan** [comment]
This type shoul be.

**Comment by guanlisheng** [comment]
Agree that we should have such type

**Comment by MisterY** [comment]
The initial implementation of this feature could be rather simple - by just adding another account type. What other changes would you foresee?

We are getting more of requests about this from the users. Could the implementation be moved to one of the earlier versions?

**Comment by otheus** [comment]
LOL, I must be stupid, because this is the first "show stopper" I came across when using this otherwise nice-looking project.  Oh look! IT's been filed as a feature request! Oh look, it's been removed as a feature request and put on hold?

I don't know how YOU guys manage your money, but ... some of us actually still use cash and would like to track expenses as such. 

So, please treat my gripe as bumping up the signal on this very important "Feature" request.

**Comment by stef145g** [comment]
@otheus, What is the purpose of a grouping "Cash Account Type", and what specifications would you believe it should have?

To my understanding, an investment account such as a bond or term deposit accounts would be grouped under Term Accounts. Accounts such as wallet, would actually be a Bank/General account.

My wallet account is a cash account, where I make expenditures and transfer money from genuine bank accounts to my wallet. My overall balances are still correct because if I have a $1000 in my Savings account, $500 in my Cheque account, and $100 on me, I still know I have a total spending power of $1,600. If I add my credit card into this mix, and have a debit of $600 on it, I again know what my spending power is. If this money is in another currency, because I go elsewhere, my US_Wallet would be in the currency USD. Still, I know what my spending power is.

If I have multiple credit cards which I am using as loan accounts, then it would make sense to have a "Credit Card Account" grouping, because I would want to eventually pay off my credit loans, so I don't want it bundled into my general Bank accounts, because I would want to know my spending power.

So where would this account type fit in or have I missed the boat? More details please so we can understand your point of view.

**Comment by otheus** [comment]
I am using version 1.2.2 as provided by PAF (portable apps framework); application update marks it as "latest available".  I see no way of keeping track of cash that I have on hand and spend. The use-case you describe is similar to what I expect in general. When I withdraw money from an ATM or cash a cheque from my checking account, that should count as a transfer from that Cheque account to the Cash/Wallet account.  Non-transfer transactions should automatically be marked as "cleared", but splitting should still be possible for detailed categorization. 

But I see no such "wallet account". Under Navigation, I see "Bank Accounts", "Assets", "Recurring Transactions", "Budget Setup", "Reports", and "Help".   If I create a new Account, my choices are "Checking", "Term", "Investment", and "Credit Card".

**Comment by vomikan** [comment]
@Otheus

I've created account "My Bank" and second one "My Cash" (all accounts type
is Checking).
Then I transfer a lot of money at the same time from "My Bank" to "My
Cash". Then spend real money (cash) from account "My Cash" and categorize
it.

Regards,
Nikolay

2015-10-29 15:49 GMT+03:00 Otheus <notifications@github.com>:

**Comment by otheus** [comment]
Thanks @vomikan . I had taken an extra large dose of "Stupid pills" yesterday. 

I still highly recommend a "Cash account" that is like a "checking account" with automatically cleared transactions.

**Comment by MisterY** [comment]
I believe this feature is technically simple to implement and rather common in the finance applications. For example, Cash accounts do not have institutions, account number, interest rate, etc. Everything else is almost the same as for Bank accounts. Therefore I think adding the new type can be implemented quickly. 
Later we can see what practical issues may appear.

**Comment by MisterY** [comment]
Or, rather, let's pose another question - what is the benefit of *not* having the Cash account type?

**Comment by stef145g** [comment]
Assuming we can create an account type "Cash".
- How do we handle it as the account records would still be stored in the existing database table?
- Would this account type have less fields, thus we can reuse existing fields for new functionality?
- How is this handled on the Home page and the Navigation panel?
- Would there be balance separation?
- How does this affect other reports?
- Would some users interpret this as an investment account type, such as bonds? This was the reason for originally introducing the Term Account philosophy.
 
The benefit of not having the Cash account type as previously suggested, is that it keeps it simple.

If we introduce this classification to handle Gift Cards and rechargeable "Credit Cards", then it would make sense, but would tend to clash with the **Credit Card Account** classification, unless this classification is changed to **Credit Account**.

Account classifications are a way of grouping like type accounts together regardless of what the actually account is called. It all hinges on how MMEX is used as a tool to manage our money.
