### ISSUE TITLE
Improving the UX of the "Organize Categories" window — flat list of all categories

### ISSUE THREAD

**Issue by Korb** [moneymanagerex/moneymanagerex#4551]
Add an option to display all categories in one list, which is convenient for identifying repetitions.

**Comment by vomikan** [comment]
#4439

**Comment by Korb** [comment]
> [needs more info]
> Sorry, there is no response for a very long time.

I don't understand, what more information is required for this suggestion? Tell me what exactly needs to be explained in it - I will do it.

**Comment by vomikan** [comment]
What categories, in which list, what repetitions, in which dialog box?

**Comment by tactilis** [comment]
@Korb
> I don't understand, what more information is required for this suggestion? Tell me what exactly needs to be explained in it - I will do it.

The best thing to do when you are proposing a change is to:

1. State what the problems is, i.e. what difficulty the current behaviour causes you.
2. Show (maybe via a screenshot) the current behaviour so that it is clear to other people what is wrong.
3. Show (ideally via a mocked up screenshot, what the new behaviour should be) and where any options to enable the new behaviour would be set.

The developer may not implement the change exactly as suggested - but it given them a better idea of what is in your head.

You mention 3 things:

Add **[an option]** to display **[all categories in one list]**, which is **[convenient for identifying repetitions]**.

- It's not clear why you have repetitions. How is this possible in the hierarchical Category tree? Is there really a problem to be solved?

- Where would you like the 'one list' to be displayed?
 
- Where would you like the option to be that turns on the display of the 'one list'?

The point I'm trying to get across is that it's very easy to toss in a 'one line idea' for a new feature but it's hard for developers to create the software to solve the problem (especially if the problem is not clear). If you do a bit more work up front, then the chance of having the feature implemented is higher.
