### ISSUE TITLE
Store the time of transaction

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/moneymanagerex#457]
We had a suggestion from the users and I'm also wondering what is the view on this.
Thanks

**Comment by guanlisheng** [comment]
I think daily is enough

LiSheng

**Comment by guanlisheng** [comment]
I think daily level breakdown is enough

**Comment by caironboy** [comment]
I also vote for timestamp with all my 10 fingers :) Please, please, please.
May be as an option, so those that do not want it can turn it off?
Thank you!

**Comment by tylla** [comment]
I don't know how fix is that wontfix label, but I support the idea of storing full datetime/timestamp. (I was right at filing a feature request when github suggested this issue).
Rationale: storing a DATETIME instead of a DATE, it does not ask for too much storage while knowing the exact time of a transaction can help a lot in some circumstances, not to mention it will show the real order of transactions even if they were entered later in random order.

**Comment by tylla** [comment]
I don't mean to pester the developers (I am perfectly aware that you sacrifice your free time to work on this project, for which I am really-really thankful), but I would like to convince you to reconsider this feature request. 
I know that this would mean lots of changes all around the apps and into the database as well, (for which maybe I could give some help - with the added warning that the inner working of your apps are completely foreign to me).

I am right in the middle of migrating 7 years of transactions to MMEX from a program that uses UNIX timestamps to store transaction date and time. It literally hurts me to deliberately lose such amount of data.

**Comment by vomikan** [comment]
@tylla I've ansvered in case 2729
