### ISSUE TITLE
Version: 1.5.15 64-bit freezing

### ISSUE THREAD

**Issue by andybluenoes** [moneymanagerex/moneymanagerex#4625]
Just upgraded to thsi version, and it locks up (not responding) constantly when moving between accounts and sometimes transacations.

**Comment by howff** [comment]
Likewise for me, definitely a regression since 1.5.14. Just clicking between accounts in 1.5.15 takes many seconds. Reverting to 1.5.14 restores the instant update when changing account. Exact same database. (Windows 10 64-bit)

**Comment by andybluenoes** [comment]
> Likewise for me, definitely a regression since 1.5.14. Just clicking between accounts in 1.5.15 takes many seconds. Reverting to 1.5.14 restores the instant update when changing account. Exact same database. (Windows 10 64-bit)

Thanks for the tip, ive just rolled back and working fine again

**Comment by vomikan** [comment]
@whalley , I can reproduce this problem. If you open a file with a large number of payees, then when switching to any account, the transaction filter is activated, where wxcombobox is filled in. this process is really too slow. I practically can't open a file with 7700 payees.

```
void mmComboBox::Create()
{
    unsigned int i = 0;
    wxArrayString auto_complite;
    for (const auto& item : all_elements_)
    {
        auto_complite.Add(item.first);
        this->Insert(item.first, i++); //Comment out this line and everything will work quickly.
    }
    this->AutoComplete(auto_complite);
    if (auto_complite.GetCount() == 1)
        Select(0);
}
```

**Comment by vomikan** [comment]
@andybluenoes , @howff  could you please investigade fixed vertion? What is the performance in your opinion?

https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/43885767/job/ycasw2gpvhgghla0/artifacts

You can install the portable version from the zip archive in any folder. You don't have to reinstall the application.
Thank you in advance.

**Comment by whalley** [comment]
Fix works on OK on Mac. But I have found a few additional funnies when compared to v1.5.14.

- The sort order for the Accounts and Payees is case-sensitive now - Related to the use of the std:map for holding the data, need to add a comparison function for this. **(Low issue)**
- All accounts are displayed via mmComboBoxAccount previously only open accounts were displayed **(Low issue)**
- If I open a transaction and click on the drop-down for accounts I only see the one entry, I need to erase the field to see others listed (this seems to be Mac only) and is caused by the use of the new mmcomboboxes and use of combobox->SetValue(..) rather than combobox->ChangeValue(...) Payee handling seems fine as it already uses ChangeValue.  https://github.com/moneymanagerex/moneymanagerex/pull/4628 **(Medium issue)**

**Comment by vomikan** [comment]
@whalley All of the above is easy to fix. The last one is MAC specific.

![image](https://user-images.githubusercontent.com/6836805/174264411-dee6876c-be87-4722-b3f9-8ba6eb17cbc0.png)

**Comment by vomikan** [comment]
Our TransactionFilter turned out to be a slow interface. But when switching accounts, it is initialized every time, which leads to a slowdown in this process. We should try to avoid initializing the filter if it is not used in a particular account.

**Comment by vomikan** [comment]
Any UI is now stalled due to xwComboBox initialization.

![image](https://user-images.githubusercontent.com/6836805/174287336-536dc088-d4fb-4e94-87f2-e8310576dc69.png)

**Comment by vomikan** [comment]
With this patch, I'm seeing a significant performance boost.

Those who wish can see for themselves.
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/43896133/job/0d5as686e4da5l7v/artifacts

**Comment by tactilis** [comment]
> With this patch, I'm seeing a significant performance boost.

Confirmed  :+1:

**Comment by vomikan** [comment]
https://github.com/wxWidgets/wxWidgets/issues/13899
https://forums.wxwidgets.org/viewtopic.php?f=1&t=30196&sid=6a427fb07e30b7d54a6e0375b5727b1a&start=15

**Comment by vomikan** [comment]
I'm mastering the wxThread function. An interesting effect is obtained. The list items appear smoothly as they load. At the same time, the freezing becomes less annoying.

![image](https://user-images.githubusercontent.com/6836805/174457767-fa7ea973-87b5-472a-8626-cc0fa0a65858.png)


https://user-images.githubusercontent.com/6836805/174457738-df29f688-ac8c-45eb-858f-f935d7b8a7fe.mp4

**Comment by whalley** [comment]
@vomikan I had a look at the use of std:thread to populate the controls, however I don't see this working on MacOS, as I get a crash:
`mmex[47080:25463125] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'`

It appears that Apple’s UI frameworks can only be called from the main thread.  https://developer.apple.com/forums/thread/659010

**Comment by vomikan** [comment]
Using threads can greatly complicate the code. In general, this case has been solved.

**Comment by Loobzer** [comment]
A little post-script for you on this. You guys did an excellent job with this particular fix. Not only did you fix the new 1.5.15 performance issue when loading different accounts, you dramatically fixed the Payee list load as well which has been a long-standing annoyance. This latest version (1.5.16) is as smooth as butter. A big thank you and well done!

**Comment by PMaff** [comment]
> @whalley , I can reproduce this problem. If you open a file with a large number of payees, then when switching to any account, the transaction filter is activated, where wxcombobox is filled in. this process is really too slow. I practically can't open a file with 7700 payees.

Sorry for being late here, but do you have some test file with 7700 payees that I can try to import with the Linux version?
Also this kind of "performance testing" is surely a good way to make mmex more robust.
What about having some other performance testfiles for things like this?
The maximum that I get from my used DB is some 752 entries.

**Comment by vomikan** [comment]
I recomment to use any available DB then insert payees
```
with recursive cnt(x) as (
  values(1) union all select x + 1 from cnt where x < 1000
)
INSERT INTO PAYEE_V1 (PAYEENAME) 
select 'payee_'||x from cnt
```

**Comment by PMaff** [comment]
Ok, had to setup all that SQL stuff since I never did this before, but now I have:

![Performance](https://user-images.githubusercontent.com/93879362/177049579-d6d42d54-d589-49d6-a9fe-38a1d0b725b4.jpg)

but that really kept mmex busy when trying to enter payee, so 9000 was a bit too much.  ;-)
1000 is easier of course.
