### ISSUE TITLE
Secondary 'Sort By' Column

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#4690]
https://forum.moneymanagerex.org/viewtopic.php?t=10552

When sorting by transactions by 'Payee' in Account View, transactions are sorted by 'Payee', then seemingly by ID as a secondary value. It would be great if we could select the secondary sorting to be via Date (or any other value desired).

The issue with the current solution is that when future transactions are entered for the same payee, but then you add additional transactions in a shorter timeframe, there is no way to have them sort in ascending date ordered by AND payee, without deleting/recreating them in the desired order, to get ascending IDs.

**Comment by whalley** [comment]
How about having the secondary sort set to the last sorte column.
E.g. 
1. sort by Date
2. sort by Payee (secondary sort is now Date)
3. sort by ID (secondary sort is now Payee)
4. sort by Payee (secondary sort is now by ID)

Just a thought. Avoids any UI changes,

**Comment by tactilis** [comment]
> How about having the secondary sort set to the last sort column.

I have sometimes wished for this myself but I can see good and less good consequences of this.

1. At present, if you enter transactions manually as you actually make them or, more likely, import the transactions from a bank account, then simply clicking on the Date column to sort by Date>ID will always match the order of transactions as entered (i.e. same order as on your bank statement).

    If we implement 'last sort column becomes the secondary sort', then simply clicking on the Date column will not necessarily give the same order as in the bank. We are likely to get more people asking questions such as _"Why doesn't the MMEX balance match my bank balance"_, or _"Why can't MMEX add up the balances correctly"_, which we have often seen on the forum.

2. Because of the above, does it make sense to show visually which column is being used as the secondary sort?

3. In the case of click to sort by Date, then click to sort by Payee (for example), should the secondary sort by Date remember the order (ascending / descending) that the user had set before clicking on Payee? If so, and we provide a visual indicator of the secondary sort column, then should this show whether the sort is ascending / descending?

4. Following on from 3, if the user clicks on Payee again, should this just reverse the Payee order but leave the secondary date order as it was?

5. At present, the user selected sort column _and_ direction of sort is saved (in mmexini.db3 I presume) so that this is remembered for the next MMEX run. If this change is implemented, then we should also remember the user-selected secondary sort order.
  
   
 
>    
> Avoids any UI changes
 
Maybe.
To be debated.

**Comment by tactilis** [comment]
> The only thing that is needed is for the primary and secondary sorting icon to differ.

For example:
 
![image](https://user-images.githubusercontent.com/4060092/174867435-74b7e539-7d08-4993-85a1-76d2533516bf.png)

 
Would that work for all the themes?

**Comment by tactilis** [comment]
@vomikan
> In this case, you can sort by an unlimited number of columns.

I think that two columns (primary and a secondary) would be sufficient for 99% of people who want to sort their transactions. And with any more, it gets difficult to show the sorting order visually. 

And I would assert that it's only a fraction of users that need to sort at all; i.e. most people are happy with the standard Date > ID sort because that matches their bank statement.

In the forum, we've even encountered people who are unaware that clicking on a column header is a standard way of sorting tabular data in (most) apps.

**Comment by BanCrash** [comment]
Calibre for example uses the method that @whalley said on second comment and for me it's very useful. Never needed another more.

Searching on internet I've found someone that said that Calibre uses the last 3 columns used to sort instead only the 2 like on that example, but IMO only the last 2 would be enough.

**Comment by whalley** [comment]
Should now be able to sort data by multiple columns. I've not put a secondary sort marker on the view as I feel this may confuse casual users who just normally sort by ID or DATE. It should save/restore the secondary and primary sort order.

**Comment by tactilis** [comment]
Testing 1.5.21-Beta.1 commit: dac3e54 (2022-09-08)

I've checked the primary/secondary sort for several combinations of columnsin Bank transactions. All seems OK.

Does this enhancement  apply to Assets yet?

While trying to check this, I noticed that the Ascending/Descending sort marker for assets Dates is the wrong way round.

![image](https://user-images.githubusercontent.com/4060092/189109687-854c9bec-6253-4d2b-ac46-72b1b5654ec5.png)

**Comment by whalley** [comment]
> Does this enhancement apply to Assets yet?

No, I've only implemented it for the transactions view. Other views only support single column sorting.

> UPDATE: The wrong sort marker is used for all asset columns.

Can you raise and issue for that and we will look to fix.

**Comment by whalley** [comment]
> I've checked the primary/secondary sort for several combinations of columns in Bank transactions. All seems OK.

I think it should support multiple levels of sorting, not just two - though I think the benefits of greater that two are not too valuable. It's only that we save/recover the primary and secondary.

**Comment by tactilis** [comment]
>  I think the benefits of greater that two are not too valuable. It's only that we save/recover the primary and secondary.

Agreed and Noted.

**Comment by whalley** [comment]
As noted above....

The secondary sort is set to the last sorted column, we don't need any special  settings.
E.g.

- sort by Date
- sort by Payee (secondary sort is now Date)
- sort by ID (secondary sort is now Payee)
- sort by Payee (secondary sort is now by ID)
