### ISSUE TITLE
Setting the size of the mmComboBox dropdown

### ISSUE THREAD

**Issue by RusberOptic** [moneymanagerex/moneymanagerex#4770]
MMEX version:
 - [ ] 1.5.14
 - [ ] 1.5.15
 - [x] 1.5.16
 - [ ] 1.5.17 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
The button for choosing and working with categories has disappeared, an attempt to write categories as I need with three or four levels of attachments does not work in any window, nothing happens at all. Or gives the error "Wrong value" Return everything as it was, everything worked fine, and the person who invented this shit should not be allowed to program at all. I can't enter any transaction at all, what to do?

Исчезла кнопка выбора и работы с категориями, попытка написать категории как мне надо с тремя или четырьмя уровнями вложений не работает ни в одном окне, вообще ничего не происходит. Или выдает ошибку "Неверное значение" Верните все как было, все работало нормально, а человека, который это дерьмо придумал, вообще не подпускайте к программированию. Я не могу вообще ни одну транзакцию ввести, что делать? 

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. 
2. 
3. 

…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by tactilis** [comment]
> and the person who invented this shit should not be allowed to program at all

You are not likely to get much assistance if you make unhelpful and unjustified comments like that.
You clearly have no idea at all about the huge amount of work the person you are referring to has put into enhancing MMEX.

Yes, the updated Category handling has not gone as smoothly as it ideally should. It's a work in progress. Arguably it was released too early but more work is being done to streamline the new functionality.

It's hard to help you because it's not clear from your report which button is missing and from which dialog it has gone. And it's not clear what you mean by "I need with three or four levels of attachments does not work in any window, nothing happens at all."

Can I suggest that you try version 1.5.17 Beta1 and then report _exactly_ what problems you are having?

Provide _exact_ step by step instructions to explain the problem. Paste in screenshots if that helps describe the issue.  Only then we can advise you properly.

You can get 1.5.17 Beta 1 from here [https://ci.appveyor.com/project/moneymanagerex/moneymanagerex](https://ci.appveyor.com/project/moneymanagerex/moneymanagerex). Choose 64 bit or 32 bit as you wish and click on Artifacts to see the installation files. I suggest you install the portable version so you can install it in a folder separate from your version 1.5.16.

If you need any more help then please do ask, but please could you do so more politely.

**Comment by renato-mmex** [comment]
**The use of MMEX is voluntary and free of charge.**

If you absolutely want to have the latest version, you must also expect to have a problem at some point. In this case, you can easily revert to an older version, here is the link: https://moneymanagerex.org/docs/downloads/older/
Here, too, it is important to discuss your problems properly and to document them in a way that they can be understood.

I miss the respect for the volunteer programmers in your post, they have put a lot of time (free time) into this project over the last few months and would be happy to get some recognition for it instead of a beating.

Greetings from the volunteer forum moderator Renato

**Comment by tycariadus** [comment]
Re categories, they now appear as one long list and part of it is hidden by the column width; so I'd suggest this needs revisiting on the new release.

Thanks

Simon

**Comment by renato-mmex** [comment]
probably you would have to limit the input line to the possibilities of the display/selection window.

<img width="255" alt="image" src="https://user-images.githubusercontent.com/76920138/177000663-6ebf1169-ffa1-424f-ba65-2184a4dfcf12.png">
<img width="214" alt="image" src="https://user-images.githubusercontent.com/76920138/177000673-7d1c42aa-8533-44d5-821f-4ab492d77bff.png">

**Comment by tycariadus** [comment]
Noted but you used to be able to read them all before the upgrade?

**Comment by renato-mmex** [comment]
_**tycariadus** probably you would have to limit the input line to the possibilities of the display/selection window_

Here the same selection in the Version: 1.3.6 64-bit
<img width="296" alt="image" src="https://user-images.githubusercontent.com/76920138/177001703-80c1152d-1955-4c69-aa15-4977ea68bb2f.png">

Here, too, the field length is limited in the selection.
But maybe it would be better if the starter of the thread would document his problem better.
Probably misses that when entering a booking in the selection of the category can no longer open a new category.

**Comment by tactilis** [comment]
> Probably misses that when entering a booking in the selection of the category can no longer open a new category.

But you can do that.  Press Enter in the blank Category field and it opens the Organize Categories dialog from where you can add/edit the categories.

This is that it's not obvious that this capability exists - but it _is_ possible to do what is asked

**Comment by renato-mmex** [comment]
Thanks for the tip, only I too had not noticed this possibility.
Here we are again with the missing descriptions.

**Comment by vomikan** [comment]
@whalley, user @Lobster left a good review about our [work](https://github.com/moneymanagerex/moneymanagerex/issues/4625#issuecomment-1172991964), so I think our changes are great.
Regardless of the style of writing this issue, I think we can consider options for calculating the width of the wxComboBox after initialization. The same trick is used for day of the week in transation dialog.

**Comment by tactilis** [comment]
@vomikan 
> user @ lobster left a good review about our work so I think our changes are great.

FYI, it was @Loobzer   :+1:

**Comment by vomikan** [comment]
> > user @ lobster left a good review about our work so I think our changes are great.
> 
> FYI, it was @Loobzer 👍

Sorry. It was google translator who write "lobster" :)
@Loobzer, thank you!

**Comment by PMaff** [comment]
> Provide _exact_ step by step instructions to explain the problem. Paste in screenshots if that helps describe the issue. Only then we can advise you properly.

Sometimes also short screenfilms are helpful.
On Linux I use `simplescreenrecorder` for this, maybe there is a similar tool for Windows and Mac?

**Comment by tactilis** [comment]
@PMaff 
> Sometimes also short screenfilms are helpful.

Indeed they are.

For Windows, I use open source ShareX for grabbing screenshots and recording screen videos.
[https://getsharex.com/](https://getsharex.com/)

**Comment by whalley** [comment]
I use [CleanShot](https://cleanshot.com/) on Mac for which you have to pay but it comes as part of my [SetApp](https://setapp.com/) subscription

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/discussions/4834
