### ISSUE TITLE
Categories on MacOS just shows full list instead of tree view

### ISSUE THREAD

**Issue by sbassi31** [moneymanagerex/moneymanagerex#4890]
MMEX version:
 - [ ] 1.5.14
 - [ ] 1.5.15
 - [x] 1.5.16
 - [ ] 1.5.17 Beta
 - [x] Other (1.5.18)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [] Windows
 - [x] Mac OSX
 - [ ] Linux 

# Description of the bug

If you enter a 'NEW' transaction and would like to add a 'Category' the list shows the full list instead of the tree view. In essence the views between 'Organize Categories' and the view for categories inside creating (or edit) are different. The selection of a category for a transaction now requires you to scroll the full list.

![image](https://user-images.githubusercontent.com/110293960/181917446-960d12e5-b320-4b5a-937b-9d581bc648ab.png)

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Open a New transaction
2. Click the dropdown for categories
3. The full list will appear

…

Expected result:
View for Organize (under Tools) and selection in transactions should be identical.

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by tactilis** [comment]
Press the Enter key in the Category field when that field is blank and you will see the Organize Categories tree view.

**Comment by whalley** [comment]
Or type something like auto* to find all categories starting with auto, or *travel for anything contains travel

The new method allow you to find categories much quicker

**Comment by tactilis** [comment]
> Or type something like auto* to find all categories starting with auto, or *travel for anything contains travel
> The new method allow you to find categories much quicker

Unfortunately, not in @sbassi31's case, Mark. 

Look at the category names in the screenshot above, which translates as:

```
expenses taxes: provin ...
expenses daily life
expenses daily life: an ...
expenses daily life: be ...
expenses daily life: bo ...
expenses daily life: café
expenses daily life: cash
expenses daily life: co ...
expenses daily life: dr ...
expenses daily life: fa ...
expenses daily life: gsm
expenses daily life: ju ...
expenses daily life: ka ...
expenses daily life: kle ...
expenses daily life: on ...
expenses daily life: re ...
expenses daily life: sc ...
```
Just typing Uitg, for example, _will_ filter the list , but it's still going to be a pretty long one (but on positive note, @sbassi31 will be able to drag out the width of the filtered list to see the subcategory names).

The problem is that the text match for the filter is anchored at the start of the category string. It would be better if we matched anywhere in the category:subcategory string.

In addition, * wildcards don't work (on Windows at least) for category filtering.

**Comment by whalley** [comment]
Wildcards do work on MacOS

**Comment by vomikan** [comment]
I found another combo box. It is available in the file wxWidgets\samples\widgets\odcombobox.cpp

![image](https://user-images.githubusercontent.com/6836805/182002628-117dd1ec-3be6-4ec2-ae70-69eb01a4f542.png)

**Comment by whalley** [comment]
Should we perhaps consider introducing an option to have Category AND Sub-Category as two separate comboboxes ? The single box works good for my workflow but it seems that either due to large category names or ease of search that having two boxes may help...

**Comment by vomikan** [comment]
> Should we perhaps consider introducing an option to have Category AND Sub-Category as two separate comboboxes ? The single box works good for my workflow but it seems that either due to large category names or ease of search that having two boxes may help...

On the one hand, this is a reasonable offer. But on the other hand, the interface of the transaction dialog will become a little more complicated.

**Comment by whalley** [comment]
> On the one hand, this is a reasonable offer. But on the other hand, the interface of the transaction dialog will become a little more complicated.

Agreed.  I think perhaps just adding a 'Category' button alongside the 'Split Transaction' button will help replicate what we had previously for those that want to continue using the category dialog (perhaps the same for payee). Otherwise, we could expend a lot of effort here for minimal gain.  In terms of the size of the combobox field it is no worse than when we had the category button that had the category name truncated when selected.

**Comment by vomikan** [comment]
A fairly simple solution is to make a choice in the settings. The old style, where the button and the new style are combobox.

**Comment by tactilis** [comment]
> A fairly simple solution is to make a choice in the settings. The old style, where the button and the new style are combobox.

I disagree.
Proliferation of options is a bad idea. It's better to just make the UI work in an intuitive manner.

Please see this proposal: https://github.com/moneymanagerex/moneymanagerex/issues/4892
