### ISSUE TITLE
Unable to put dot (".") in Stock Symbol like "IOC.NS" 

### ISSUE THREAD

**Issue by vishweshmasurkar** [moneymanagerex/moneymanagerex#4986]
## So unable to use stocks Accounts it doest refresh stock price 

MMEX version:
 - [ ] 1.5.17
 - [ ] 1.5.18
 - [x] 1.5.19
 - [ ] 1.5.20 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [x] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by tactilis** [comment]
Seems to work for me in 1.5.19 and 1.5.20 Beta
 
![image](https://user-images.githubusercontent.com/4060092/187095221-e99756a8-ae21-4c4f-9fb7-ecc79ae1b804.png)
 
I get the 'normal' crash on Windows (i.e. we haven't tracked the bug it down yet) when I create the Stock, but when I restart MMEX the new entry is there. The dot in the IOC.NS name works and prices are downloaded OK.

@vishweshmasurkar Could you explain exactly what prevents you putting a dot in the stock symbol please?

**Comment by vishweshmasurkar** [comment]
# I get this when I put dot

<img width="810" alt="image" src="https://user-images.githubusercontent.com/48190241/187095482-873f27b2-c05d-404e-933f-e4ea0755976c.png">

**Comment by tactilis** [comment]
Sorry, my bad.

I entered IOC.NS in MMEX 1.5.20 Beta and then just tested the same database in 1.5.19 without trying to re-enter IOC.NS

I now agree that there is a bug.

It is due to the same as described here https://github.com/moneymanagerex/moneymanagerex/issues/4951

The bug is fixed in 1.5.20 Beta.

You could reinstall 1.5.18 for now (where the dot works) and then update to 1.5.20 when that version is released (it should not be too long).

**Comment by vishweshmasurkar** [comment]
Thank you so much
