### ISSUE TITLE
Provide Undo button in tools menu

### ISSUE THREAD

**Issue by arp2164** [moneymanagerex/moneymanagerex#4994]
# Description of the feature
Need to have a undo button.
Please describe your feature with details.
If you delete accidentally a transections or account,  there is no Undo settings button in edit or tools menu. Basically you lost data, there is no way to recover. When you close program it's gone.
I went with all menu and could not find anything that will recover or can some one tell me there is way before closing the program to recover?
Add screenshots, design images or other files which would help for
understanding the feature or for implementation.
Also add links when needed, for instance for implementation standards
or other relevant resources.

# Use cases

If not obvious, explain the use cases or problems to solve.

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/2963

**Comment by arp2164** [comment]
I checked #2963 but don't understand how to Undo ?
you mean deleted item goes to trash can? Well I did not see it. or this is future update.

**Comment by tactilis** [comment]
@arp2164 What @whalley is saying is that there is already a feature request for an Undo capability in MMEX and that it is covered by issue #2963, i.e. yours is not a new request.

#2963 is still an Open issue. It has not been implemented yet.

I'm sure you must realise, that it it is not as simple as just providing an "Undo button in tools menu". There is a huge amount of behind the scenes software that would need to be changed and extended to provide the infrastructure to track changes to the database as users enter and edit transactions. This all needs to be done before an Undo capability can be implemented. It's complicated.

**Comment by grumpy235** [comment]
@arp2164 
As @tactilis states this is not going to happen instantly or even I guess in the short term especially as there are currently only two key developers doing a splendid job. For the moment to provide some form of insurance you could make use of the already implemented backup feature. Options/others - set backup at start and set number of backups or the "Save database as..." under File.
Just a stop gap but better than nothing.
I have been using MMEX for getting on for 10 years now and financial software (Quicken) since the early '90s and have never really found the need for this feature not even sure if Quicken, a commercial product, had this feature and if I do screw things up then I just fall back to a backup and started over - maybe I have been lucky!

**Comment by arp2164** [comment]
I fully understand how much work is involved. Maybe it’s best to use backup file. It involves copying and pasting and changing extension from.bak to.mmb. 
‘earlier I mentioned this in separate request.
Thanks

**Comment by reddyshyam** [comment]
> I fully understand how much work is involved. Maybe it’s best to use backup file. It involves copying and pasting and changing extension from.bak to.mmb. ‘earlier I mentioned this in separate request. Thanks

Yes, totally! I do the same. I have set 'create backup on MMEX start' option, just in case I mess something up. Has come handy couple of times. So I believe, is the best way instead of 'on exit'.

![image](https://user-images.githubusercontent.com/12392746/187607208-421b5dae-d435-4b77-af87-75580ffe6485.png)

**Comment by tactilis** [comment]
@reddyshyam
> I have set 'create backup on MMEX start' option, just in case I mess something up

Depending on the way you use MMEX each day, it may be a good idea for you to also set 'Backup database on exit'.

As stated in the MMEX Help:

```
Options | Others Panel

Database Backup:

Sets the way the backups are performed when MMEX starts.

    Create a new backup when MMEX Start:
        This copies the database to a new file with today's date, when MMEX Starts.
        The file will not be over written when MMEX starts up again.
        When there are more that 4 backup files, the oldest file is deleted.

    Backup database on exit:
        When MMEX shuts down, the existing database will be copied to a backup database file for
        that day when changes to the database have been detected.
        When changes are made on the same day, the existing backup is over written.
        When there are more that 4 backup files, the oldest file is deleted.
```

The Help is a little out of date and could be improved by mentioning that the backup copies of the database are named:

```
    <database name>.mmb_start_<yyyy-mm-dd>.bak
    <database name>.mmb_update_<yyyy-mm-dd>.bak
```

It should also say:

```
    When there are more that 'Max Files' backup files, the oldest file is deleted.
```
rather than  explicitly saying 4 files.

However, the important issue to note is that the `_start_` backup file is a copy of your .mmb database when you _first_ start MMEX on a particular day. Even if you exit and restart MMEX, the  `_start_` .backup will not change. This backup is therefore a snapshot of the database at the _beginning_ of your use of MMEX on a particular day, no matter how many times you exit and re-start the application.

In contrast, the `_update_` backup file is a copy of your .mmb database when you exit MMEX (or when you stay in MMEX but open a different database). The backup file is updated with a copy of your database _every_ time you exit (or switch databases) if any transactions have been updated during the session.

You should consider the above information if you have made an error (maybe accidentally deleted 100s of transactions) and want to preserve a copy of a backup file _before_ you exit MMEX (otherwise you will overwrite the previous `_update_` file for that day and lose your transactions.

Best practice is to _copy_ your chosen .bak file to, for example, `<Database>_RECOVERED.mmb` while MMEX is still open and then open that file with MMEX.

**Comment by arp2164** [comment]
Yes I agree that start back up is better.
Or if you use close back up on exit then don’t close program just open your back up file and recover lost transaction.
Great help, I will keep it in my program notes.

**Comment by tactilis** [comment]
@arp2164
>Yes I agree that start back up is better.

But I **didn't** say that!
I'm afraid you seem to have have missed the point I was making (I may not have made it clearly enough).

I said:
> Depending on the way you use MMEX each day, it may be a good idea for you to _**also**_ set 'Backup database on exit'.

Consider this scenario (which all takes place on a single day) if you _only_ have the 'Backup on start' option set:

1. Start MMEX with `<database>.mmb`. A `_start_` backup will be made.
2. Manually enter 50 transactions, or edit them to reconcile them with your bank statement, or whatever... you've done a lot of work.
3. Look at some reports.
4. Exit MMEX. No `_update_` backup is made because you don't have that option turned on.
5. Later that day, start MMEX. No `_start_` backup is made; see my explanation in the post above.
6. Return to the account where you entered the transactions and accidentally delete all of them them, or maybe even accidentally delete the account! Oops!!

At this point you have **lost all the work** you did that day because you can only go back to the `_start_` backup MMEX made at the _beginning_ of the day.

If you had 'Backup database on exit' set, then at point 4. you would have an `_update_` backup containing your 50 newly entered or edited transactions.

So after you caused the disaster at point 6. you should:

7. Pause and think!
8. **Not** exit MMEX, because doing so would overwrite the `_update_` backup containing your transactions.
9. Immediately take a copy of your backups and put them in a separate folder for safe keeping.
10. Now you can exit MMEX (which will cause the `_update_` backup to be overwritten)
11. Go to your safe keeping folder and **copy** today's `_update_` backup file to `<database>_RECOVERED.mmb`
12. Open the RECOVERED database with MMEX to check that it contains your transactions (of course it does).
13. Close MMEX and rename `<database>_RECOVERED.mmb` to `<database>.mmb`
14. Be happy that MMEX has helpful backup options and that you understand how best to use them.

I hope that's clear now.

There are other scenarios you could easily think of. You can deal with most problems by understanding what MMEX offers you.

To return to your original topic... Yes, it would be great if MMEX had an Undo capability but it's _very_ complex to implement, and it isn't going to appear any time soon (or maybe never). So it's best to increase your chances of a successful disaster recovery by having 'Backup at start' **_and_** 'Backup at exit' turned on.

**Comment by arp2164** [comment]
Yes I misunderstood. Thanks for your detailed help. I had setup for backup on exiting, now I will also do backup on start.

**Comment by whalley** [comment]
> I had setup for backup on exiting, now I will also do backup on start.

You can never have too many backups....

**Comment by arp2164** [comment]
I use program two or three times a week. On same day I open the program once, rarely I have to open twice . 
so what’s good for me? Start only or start and exiting. I think start is good option for me because during the session I add few entries but accidentally deleted many entries then existing program, I lost deleted entries. So to use start backup file at least I have deleted many entries but have to enter few new ones.
Any advice will be appreciated.
Thanks

**Comment by reddyshyam** [comment]
> I use program two or three times a week. On same day I open the program once, rarely I have to open twice . so what’s good for me? Start only or start and exiting. I think start is good option for me because during the session I add few entries but accidentally deleted many entries then existing program, I lost deleted entries. So to use start backup file at least I have deleted many entries but have to enter few new ones. Any advice will be appreciated. Thanks

My recommendation is 'On Start'. As you said if anything goes wrong during the usage, we always have a safe backup. If all good when existing, then we dont really need the backup as on start we get a backup again.

**Comment by tactilis** [comment]
@reddyshyam

Just to clarify your words:
> My recommendation is 'On Start'. As you said if anything goes wrong during the usage, we always have a safe backup. If all good when existing, then we dont really need the backup _as on start **THE NEXT DAY** we get a backup again_.

If you happen to start MMEX a second (or subsequent) time the SAME DAY, then the `_start_` backup will not be made again.

In my view it is prudent to enable both 'on start' and 'on exit' backups. The backups take up little disk space and do not impact MMEX performance in any way - but do provide maximum flexibility in the unfortunate event that you have to recover from a disaster.

The number of '_start_` and `_update_` files is limited to the 'Max Files' setting, so they are self-managing.

That's all I have to say on this subject. @arp2164 You need decide for yourself what is best for you.

**Comment by arp2164** [comment]
Thanks all giving me your much appreciated input.
I will for my scenario keep start backup. Also from today I have started copying main data base file to external ssd and every week, I will do it by making sure that all data are there. So worst case scenario, I may have to add new transaction only.
Thanks again for your thoughts.

**Comment by reddyshyam** [comment]
Please close the issue if you are happy with the input. :)

**Comment by reddyshyam** [comment]
> @reddyshyam
> 
> Just to clarify your words:
> 
> > My recommendation is 'On Start'. As you said if anything goes wrong during the usage, we always have a safe backup. If all good when existing, then we dont really need the backup _as on start **THE NEXT DAY** we get a backup again_.
> 
> If you happen to start MMEX a second (or subsequent) time the SAME DAY, then the `_start_` backup will not be made again.
> 
> In my view it is prudent to enable both 'on start' and 'on exit' backups. The backups take up little disk space and do not impact MMEX performance in any way - but do provide maximum flexibility in the unfortunate event that you have to recover from a disaster.
> 
> The number of `_start_` and `_update_` files is limited to the 'Max Files' setting, so they are self-managing.
> 
> That's all I have to say on this subject. @arp2164 You need decide for yourself what is best for you.

Hi,

I appreciate your insight but the likeliness of opening the app multiple times a day and doing more than few transactions which cannot be re-done in worst case scenario (atleast in my case) is minimal. So I will take the chance. :) Thanks again for cautioning me.
