### ISSUE TITLE
How to recover a backup file

### ISSUE THREAD

**Issue by arp2164** [moneymanagerex/moneymanagerex#4995]
# Description of the feature
Recover back up file
Please describe your feature with details.
The program creates back up file in same folder as main data base folder. 
How do I use back up file to restore my data?
When you start program a window gives several options but there is no option to use or open back up file. 
If you use open data base folder it shows back up file with ext.bak but I can not choose because it's grayed out.
can some one tell me in detail how to use back up file for recovery?
Add screenshots, design images or other files which would help for
understanding the feature or for implementation.
Also add links when needed, for instance for implementation standards
or other relevant resources.

# Use cases

If not obvious, explain the use cases or problems to solve.

**Comment by whalley** [comment]
Go to the directory where the backups are stored.
Each backup file has an extension of .bak
For the backup you want to access just take a copy and change the extension to .mmb
Then open in MMEX

**Comment by tactilis** [comment]
The .bak backup files are simply copies of the .mmb database files with the file type changed.

The backup files can be created when MMEX starts and/or when MMEX is closed (See MMEX Options)

![image](https://user-images.githubusercontent.com/4060092/187276285-f356e8df-765d-4e28-810f-a57110c439cc.png)

Best practice is to make a copy of your .bak (naming it as you wish and changing .bak to .mmb). Then open it in MMEX

**Comment by arp2164** [comment]
wow so that's the way to restore a back up file.
Thanks For explanation.
I wish may be for future update there could be a simpler way to do it?

**Comment by tactilis** [comment]
> I wish may be for future update there could be a simpler way to do it?

Why is copying a backup file hard to do?
 
 
For info, the MMEX Help says:
___________________________________
**Options | Others Panel** 

Database Backup:

Sets the way the backups are performed when MMEX starts.

Create a new backup when MMEX Start:
This copies the database to a new file with today's date, when MMEX Starts. The file will not be over written when MMEX starts up again. When there are more that 4 backup files, the oldest file is deleted.

Backup database on exit:
When MMEX shuts down, the existing database will be copied to a backup database file for that day when changes to the database have been detected. When changes are made on the same day, the existing backup is over written. When there are more that 4 backup files, the oldest file is deleted.
___________________________________

![image](https://user-images.githubusercontent.com/4060092/187302442-56e7b051-4105-4796-ae0b-422f0090f10f.png)
 
 
The Help is a little out of date and could be improved by mentioning that the backup copies of the database are named .bak

It should also say that 'Max Files' number of copies are saved, rather than saying 4.

**Comment by arp2164** [comment]
tactilis,
No it’s not hard to copy and paste and change extension.
What I am saying that if program does backup then it should also do recover.
I am not complaining,in fact I am grateful to developer that such wonderful program giving free.

**Comment by whalley** [comment]
We have had instances in the past where people have accidentally opened backup files and then saved them as the latest DB, which was why we named the backups as *.bak to avoid the application being able to open them directly without explicit user action, i.e. renaming the file. 

> What I am saying that if program does backup then it should also do recover.
The application **does** support recovery but is via the mechanism described. As this is/should be a rare occurrence I think the mechanism is sufficient. Admittedly, we do need to better document the process.

**Comment by AdrianEugene** [comment]
> > I wish may be for future update there could be a simpler way to do it?
> 
> Why is copying a backup file hard to do?
> 
> tactilis, No it’s not hard to copy and paste and change extension. What I am saying that if program does backup then it should also do recover. I am not complaining,in fact I am grateful to developer that such wonderful program giving free.

--------------------
arp2164 - I totally agree with you.  You did not need a snarky reply.  That so often is the case when so-called experts have attitude with "newbies."  The copy and change extension is fine, but it is common sense that if backups are produced, one should not have to ask questions in a support forum.  That is what support forums are for.  Helping people.  Not snark.   I call BS.
