### ISSUE TITLE
Split Transaction Dialog grows too big

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#5005]
I'm experiencing a problem whereby if I enter many Splits on one transaction, the action buttons ("Add Split", "Remove Split", "OK", and "Cancel") disappear from the screen. Using the scroll bar does not help to reveal them. The only way out is to cancel using the red window control button on top left, and lose all entries.

Before the Splits window was changed - a few updates ago (sorry don't remember when the pop up was 'modernised' - I was able to add more.

https://forum.moneymanagerex.org/viewtopic.php?t=10671

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/187648077-b15d6a97-d334-4660-9f77-c8d9310351dd.png)

**Comment by vomikan** [comment]
Just a tip.
Use the keyboard shortcuts Alt+O (OK) and Alt+C (Cancel) to (save and) close the dialog.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4911

**Comment by whalley** [comment]
How about this as a more simplified version.

1. Have moved the header (Category/Amount) outside the scroll area so that it remains visible when scrolled
2. Presented fist 10 entries for use, adding more will scroll
3. Dialog fixed size in vertical direction

**Comment by whalley** [comment]
..just spotted a horizontal resize issue when entries added... can fix that if the basic approach is acceptable.

**Comment by whalley** [comment]
The 'Add Split' logic needs a little tweaking now that we display 10 rows of splits.

**Comment by vomikan** [comment]
Seems does not fixed yet.

![image](https://user-images.githubusercontent.com/6836805/187670855-287c9821-9bfe-49e2-9cb6-abc96adc6022.png)

**Comment by vomikan** [comment]
I like this fix. But I can't change vertical size of the dialog.
![image](https://user-images.githubusercontent.com/6836805/187674691-a5b5f4b3-8a34-443a-9b84-4885c96e5634.png)

![image](https://user-images.githubusercontent.com/6836805/187674777-cf0dbe3f-7897-422d-b6e0-ae55731e3843.png)

**Comment by whalley** [comment]
> Seems does not fixed yet.
> 
> ![image](https://user-images.githubusercontent.com/6836805/187670959-75f1adc7-2a97-467f-bd7e-2e91131a94fa.png) ![image](https://user-images.githubusercontent.com/6836805/187670855-287c9821-9bfe-49e2-9cb6-abc96adc6022.png)

Not sure what the issue is here. Is it the multiple splits with the same category? If so, then I think this is OK as there have been requests for notes per split so having splits with same category and different notes may be possible in the future.

**Comment by whalley** [comment]
> I like this fix. But I can't change vertical size of the dialog.

As noted when I committed the change "3. Dialog fixed size in vertical direction" -- I thought this would acceptable and avoids more complex layout handling. Unless you have a quick fix.

**Comment by vomikan** [comment]
I can't change the verticale size of the dialog
https://user-images.githubusercontent.com/6836805/187732957-b9bf3b97-28b5-4b50-a273-a5e84968858a.mp4

**Comment by whalley** [comment]
See note above.

> I like this fix. But I can't change vertical size of the dialog.

As noted when I committed the change "3. Dialog fixed size in vertical direction" -- I thought this would acceptable and avoids more complex layout handling. Unless you have a quick fix.

**Comment by whalley** [comment]
@tactilis - Martin, would be good if you could give this a bit of testing as I've changed some key logic and want to make sure I've not broken anything (you know how careless I can be!)

**Comment by tactilis** [comment]
> Martin, would be good if you could give this a bit of testing

Will do.

> you know how careless I can be!

No idea what you mean :wink:

**Comment by tactilis** [comment]
Testing 1.5.20-Beta.1 - commit: 0aaf72f (2022-08-31)

I have several (small) observations but it will have to wait until tomorrow for me to write them all up.

In the meantime, here are the first few:

___
1. Position of the Amount label is wrong when the scrollbar is displayed:

![image](https://user-images.githubusercontent.com/4060092/187780154-1024b994-7320-4d4c-a31e-b5e7521e964d.png)

Expected Result: Amount label should always be right aligned above it's field.

___

2. The dialog width can be reduced so that the Amount field becomes obscured and the Remove Split button is forced to shrink.

https://user-images.githubusercontent.com/4060092/187780914-1c610e02-1b4b-43eb-8d96-997163e2d51a.mp4

Expected Result: There should be a minimum width enforced so that the field obscuration and button shrinkage does not occur. 

___

3. When there are more rows containing data than can be displayed and the scrollbar is shown, then tabbing (or pressing Return when in Amount) to move focus to a row that is currently outside the visible area. Pressing down arrow when focus is in a Category field that is outside the visible area results in the combobox list being displayed. Very confusing.

https://user-images.githubusercontent.com/4060092/187787161-7a35e2e5-2eaa-4b06-a8cd-4075e3ebb6ad.mp4

Expected Result: The row with focus should always be scrolled into view. 
___

**Comment by whalley** [comment]
> 1. Position of the Amount label is wrong when the scrollbar is displayed

Agreed, I noticed this and know why this occurs, but way too much effort to fix. Will leave as-is.

> 2. The dialog width can be reduced so that the Amount field becomes obscured and the Remove Split button is forced to shrink.

Agreed, have set minimum width to avoid this.
 
> 3. When there are more rows containing data than can be displayed and the scrollbar is shown, then tabbing (or pressing Return when in an Amount field) to move focus to a row that is currently outside the visible area. Pressing down arrow when focus is in a Category field that is outside the visible area results in the combobox list being displayed. Very confusing.

Agreed, fixed.

**Comment by tactilis** [comment]
@whalley
> 2. Agreed, have set minimum width to avoid this.

Rather belatedly it occurs to me that there is now no reason to have the dialog width resizeable at all.

We no longer have vertical resizing because we now have a fixed number of rows on display with a scroll bar (and that arrangement works well), so why not fix the width too?

For comparison, we don't, allow resizing of the Edit Transaction dialog, and there are no complaints about that, so could we do it for Split Transactions?

This, I assume, would also allow you to put the Amount label in a fixed position above the field, regardless of whether the scrollbar is displayed.

Sorry if this undoes work that was previously done, but I now can't see any downsides to this dialog's size being fixed.

**Comment by whalley** [comment]
> We no longer have vertical resizing because we now have a fixed number of rows on display with a scroll bar (and that arrangement works well), so why not fix the width too?
> 
> For comparison, we don't, allow resizing of the Edit Transaction dialog, and there are no complaints about that, so could we do it for Split Transactions?

There have been complaints that the presentation of the category field is too small to see the full category name, this is why I left horizontal resizing. Perhaps we should, at some point, allow this also on the transaction dialog. I propose to leave the resizing as-is.

**Comment by tactilis** [comment]
@whalley
>  I propose to leave the resizing as-is.

Understood.

In which case please could you look at:

___
4. If the Total amount is a large value (Electricity and Gas are _so_ expensive now!), then, when the dialog is resized, it is still possible to force the Remove Split button to shrink.

![image](https://user-images.githubusercontent.com/4060092/187860881-61e3e650-fa7b-4c24-985d-8b3bcc53c0da.png)
 
Here I have set the Font Size option to Huge, but the same problem can occur with smaller font sizes if the total amount is large enough.

Note that this example is not as contrived as it may seem. We have seen (via the forum) somebody using MMEX for a building project(?) and having large value invoices that they were entering as a single transaction and then splitting.

Expected Result: The Remove Split button should be constrained to be the correct size for the text it contains and thus it should not permit the dialog to be resized smaller than a certain minimum width. Bonus points if you can prevent the horizontal scrollbar ever appearing too.

**Comment by tactilis** [comment]
Confirmed all fixed. Thanks.

I've one more observation related to splits but as it has nothing to do with the Split Transaction Dialog itself, I'll raise it as a separate issue.

**Comment by vomikan** [comment]
> What else do you think we need to change to perfect it?

Vertical size changing. I can't do it myself.

**Comment by tactilis** [comment]
Would have been nice to have the original idea of the dialog growing in height (up to a certain point) as splits are added, and then with a scrollbar after that.
 
But I honestly think it works well enough now:

- When a user looks at the UI, the functionality is obvious.
- There are no strange surprises when pressing buttons.
 -And it's speedy to use (tabbing or pressing Enter for a new split) so that you don't need to use the Add Split button if you don't want to.

**Comment by whalley** [comment]
> > What else do you think we need to change to perfect it?
> 
> Vertical size changing. I can't do it myself.

Yes, thought that might be it, but I've had enough making changes in this area for now. Might re-visit in future when I feel like a challenge :-)

**Comment by 429pm** [comment]
> Just a tip. Use the keyboard shortcuts Alt+O (OK) and Alt+C (Cancel) to (save and) close the dialog.

Cmd-O and Cmd-C in Mac OS :). Works a treat. Thanks for the tip.
