### ISSUE TITLE
Crash Report - Upgraded from v1.5.18 to v1.5.20

### ISSUE THREAD

**Issue by k13oharts** [moneymanagerex/moneymanagerex#5042]
MMEX version:
 - [ ] 1.5.17
 - [ ] 1.5.18
 - [ ] 1.5.19
 - [x] 1.5.20
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows 11 x64
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Launching v1.5.20 with last opened database keeps crashing 

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
1. Downloaded latest release mmex-1.5.20-win64.exe
2. Perform installation

Expected result:
* Software launches as expected

Actual result:
* Debug report "MoneyManagerEx" launches instead
* Keeps crashing on subsequent tries

# Additional information
* Rolling back to v1.5.18 works as normal after the MMEX Instance Check
* Tried using v1.5.19 but that had a bug with the reference number

If you have a backtrace for a crash or a warning, paste it here.
[MoneyManagerEx_dbgrpt-16400-20220904T190334.zip](https://github.com/moneymanagerex/moneymanagerex/files/9484939/MoneyManagerEx_dbgrpt-16400-20220904T190334.zip)

**Comment by tactilis** [comment]
@k13oharts Can you confirm that you are able to run 1.5.20 with a different database without problems?

Suggest that you:

1. Temporarily move your existing database to a different folder (so that MMEX can't find it).
2. Try running MMEX. Does it start? Can you  create a new database OK?

If you now File | Open Database...  and select your old database, does MMEX now crash?

**Comment by k13oharts** [comment]
> @k13oharts Can you confirm that you are able to run 1.5.20 with a different database without problems?
> 
> Suggest that you:
> 
>     1. Temporarily move your existing database to a different folder (so that MMEX can't find it).
Moved the file to the desktop and tried to run it. Crashed.
>     2. Try running MMEX. Does it start? Can you  create a new database OK?
Launching it by creating a new database file works well.
> 
> If you now File | Open Database... and select your old database, does MMEX now crash?
Loaded the file from the original location as well as the desktop.
Visually, the file opened and loaded the navigation tree both times.
The crash event would seem related to loading the Homepage?

Tested running the same file in 1.5.19. No issues.

[MoneyManagerEx_dbgrpt-21944-20220904T214218.zip](https://github.com/moneymanagerex/moneymanagerex/files/9485204/MoneyManagerEx_dbgrpt-21944-20220904T214218.zip)

**Comment by whalley** [comment]
@k13oharts Is it possible to share the database? It will be treated as confidential. If so, please zip and mail to: support@moneymanagerex.org. Once the issue is debugged I will delete your database. 

Alternatively, perhaps you can take a copy and redact any sensitive data from this and send that. Assuming of course that the redacted DB still crashes in v1.5.20.

**Comment by k13oharts** [comment]
> @k13oharts Is it possible to share the database? It will be treated as confidential. If so, please zip and mail to: [support@moneymanagerex.org](mailto:support@moneymanagerex.org). Once the issue is debugged I will delete your database.
Email with crash report and redacted/anonymized database sent.
> Alternatively, perhaps you can take a copy and redact any sensitive data from this and send that. Assuming of course that the redacted DB still crashes in v1.5.20.
Yes, it still crashes in v1.5.20 and trying on an alternate workstation: Win10 x64

**Comment by whalley** [comment]
Thank you. I have reproduced the crash.
![CleanShot 2022-09-05 at 08 45 51](https://user-images.githubusercontent.com/487345/188396052-96f8ea4c-4305-4c51-b2e7-b274047b1e6b.png)

This change in v1.5.20 would seem to be the related change: https://github.com/moneymanagerex/moneymanagerex/pull/4952/files

I'm not overly familiar with the stocks/shares processing - @vomikan / @Yurand -- are you able to investigate.

**Comment by vomikan** [comment]
> I'm not overly familiar with the stocks/shares processing

You need to add a check, if (share_entry) immediately after line 81.

**Comment by whalley** [comment]
Yes, that would have been my 'goto' suggestion, but was not sure if DB was corrupt as the SHAREINFO did not exist for the that 'CHECKINGID'.

**Comment by vomikan** [comment]
This code is an attempt to link accounts and investments so that money is linked to securities.
The connection goes through the name of the paper and the magic number.
The user can easily break this fragile connection by changing the name or deleting the account.
I personally have never opened an ASSET account. There is no time to deal with this case at the moment. I suggest simply to drown out the reference to an undefined object.

**Comment by Yurand** [comment]
I did this based on stockspanel.cpp ViewStockTransactions() function. So we need to add NULL check there as well. I will prepare PR

**Comment by whalley** [comment]
@k13oharts Can you please download and test using this v1.5.21 Beta build that hopefully fixes your issue: https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/44678827/job/wg4wyqdpec35wvfd/artifacts
