### ISSUE TITLE
Date Control Tooltip Suggestion

### ISSUE THREAD

**Issue by rmelillo76** [moneymanagerex/moneymanagerex#5051]
# Description of the feature

Please consider changing the text from "Retard or advance the date" to "Change the date" or "Move the date forward or backwards"

The word "Retard" can be considered offensive and derogatory towards someone with a mental disability.

![image](https://user-images.githubusercontent.com/95182117/188751433-af350624-eaa1-4028-8150-db18423389ec.png)

**Comment by tactilis** [comment]
> The word "Retard" can be considered offensive and derogatory towards someone with a mental disability.

What you say is true, but the word of itself is not offensive; its usage is context dependant and, in the context of a date button, the word retard cannot possibly be construed as being directed at a person.

However, I would advocate changing it because in this context to retard means:

_"to make slow; to delay the development or progress of (an action, process, etc.); to hinder or impede"_

and that (i.e making slow, delaying, or impeding) is not what the button does.

So, the tooltip could be modified to "Change the date" or "Previous/Next day".

Or, even better, the tooltip could be removed completely, because the functioning of the up/down arrows next to a **date field** and the **day name** is _so_ obvious that it doesn't need a tooltip at all.

At present, MMEX uses tooltips in a rather inconsistent manner; in some places there are tooltips where the purpose of the button or field is very obvious, while in other places, where some explanation would be helpful, no tooltip is provided. This could be addressed under a separate issue when time permits.

**Comment by whalley** [comment]
> Or, even better, the tooltip could be removed completely, because the functioning of the up/down arrows next to a date field and the day name is so obvious that it doesn't need a tooltip at all.

Agreed.

**Comment by rmelillo76** [comment]
@tactilis I agree with you, it is 100% context-dependent. And as you said, it is obvious how to use that control, so for multiple reasons it makes sense to simply remove the tooltip altogether. Thank you!

**Comment by vomikan** [comment]
I remind you that our default language is American. It can be translated into English.
https://crowdin.com/project/moneymanagerex/en-GB

**Comment by tactilis** [comment]
Testing 1.5.21-Beta.1 commit: dac3e54 (2022-09-08)

Confirmed fixed.
