### ISSUE TITLE
Add collections / lists of items

### ISSUE THREAD

**Issue by BanCrash** [moneymanagerex/moneymanagerex#5129]
# Description of the feature

Hi, maybe this is out of scope of MoneyManagerEx, but I was thinking on a feature that would be have the hability to create different items collections, not for tracking the general income / expenses, but to know how many money did you expend on a specific items collection.

For example, I can create a "Bluray" collection, where I'll place all my Bluray movies and tv shows, set how much I expended on each title, the total, etc, like a normal account but for this specific collection. Another collection would be "PC", to add all my pc components. Other for "Videogames", for the expenses on videogames... This will work like a tracking of items you have and how many did you have expended on each item and on each collection globally (1000 € in the PC, 200 € in videogames, etc).

Mockup:
Sidebar (ignore icons):
![imagen](https://user-images.githubusercontent.com/11770760/192111721-7cada1fe-7f70-4518-8d8d-60b1ea7430e4.png)

Collection list:
![imagen](https://user-images.githubusercontent.com/11770760/192112141-a8f2f53b-d7cb-4812-bf7d-085d01781936.png)

(sorry for the paint mockup)

I added the category of "still owned" for those objects that you didn't sell but you lost somewhere, but I think that could be a simply custom field.

# Use cases

Have a tracking of expenses on certain items. I was thinking of using category filters for that, but IMO with the categories you don't achieve the complete meaning of this.

# Alternative
I never used Assets account but I used it for the mockup and seeying it on the app I think that it could be used somehow for this. Maybe adding the ability to add custom assets types? Not sure though, like I've said I never used it.

Feel free to close this if this is out of scope of MMex

**Comment by whalley** [comment]
Have you considered using custom fields for this? E.g. 
![CleanShot 2022-09-29 at 23 42 36](https://user-images.githubusercontent.com/487345/193154890-79279808-bf71-4394-ad20-6aae79b52cff.png)

You can the setup a transaction report to report on the details
![CleanShot 2022-09-30 at 00 41 18](https://user-images.githubusercontent.com/487345/193160741-5c7254ad-cb1d-4006-a0f3-fc86f729a432.png)

![CleanShot 2022-09-30 at 00 38 53](https://user-images.githubusercontent.com/487345/193160573-5bca4ce2-3416-435b-af04-5b08481c7361.png)

![CleanShot 2022-09-30 at 00 42 26](https://user-images.githubusercontent.com/487345/193160707-f4e49fd0-714b-4779-b1c3-6cb1583d30cc.png)

Note, there is a current bug with custom fields in reports that I have spotted - https://github.com/moneymanagerex/moneymanagerex/issues/5145 which should be fixed in the next release.

**Comment by BanCrash** [comment]
@whalley yes I think that would be fine for me, thanks for the idea!

**Comment by whalley** [comment]
If it helps this is the demo database I used.
[collections.zip](https://github.com/moneymanagerex/moneymanagerex/files/9682584/collections.zip)

**Comment by BanCrash** [comment]
> If it helps this is the demo database I used. [collections.zip](https://github.com/moneymanagerex/moneymanagerex/files/9682584/collections.zip)

I'll check it out, thanks again!

**Comment by whalley** [comment]
Oops sorry, yes I've been using the latest beta version for this. If you don't want to try the beta then I can produce a downgraded DB version for you - let me know.

**Comment by BanCrash** [comment]
> Oops sorry, yes I've been using the latest beta version for this. If you don't want to try the beta then I can produce a downgraded DB version for you - let me know.

Don't worry, you already made enough work on this matter for helping me, I'll update to the beta to try it.
