### ISSUE TITLE
Transactions not entering in logical order

### ISSUE THREAD

**Issue by pozzino** [moneymanagerex/moneymanagerex#5134]
Entering several transactions with the same date.  Version: mmex-1.5.21-win64.exe
The transactions show up in the Account view with the original balance at the top and the final balance at the bottom of the entries. Sorting by ID and then Date puts the transactions in the correct order. Any further change of view or transaction entry puts the entries back to the incorrect order.

**Comment by whalley** [comment]
A fix will be available in next release. There have been a few reports around the sort order.
https://github.com/moneymanagerex/moneymanagerex/issues/5108
https://github.com/moneymanagerex/moneymanagerex/issues/4690
https://github.com/moneymanagerex/moneymanagerex/issues/5122

**Comment by Dandy64** [comment]
Is it possible to sort data separately on every screen? Let's say I am sorting by Date on my Bank Account, while on my Cash Account I prefer always to see sorting by Payee.

**Comment by whalley** [comment]
The ALL TRANSACTIONS view maintains a sort different from the other individual accounts, but there is no saving of individual account sort order.

**Comment by tactilis** [comment]
Assets and Recurring Transactions also have their own sort orders.

But otherwise, it's as @whalley says.

**Comment by tactilis** [comment]
@Dandy64
> Let's say I am sorting by Date on my Bank Account, while on my Cash Account I prefer always to see sorting by Payee.

I'm interested to understand the reason for your preference for keeping your Cash account _always_ sorted by payee?

How are you using this Cash account please?  Is it really representing cash-in-hand/in the wallet?  Ans are you therefore paying cash to your payees?

Do you not wish to know how the balance changes over time, which you obviously can't see if the account is always sorted by payee?

Understanding how MMEX is used (and why) helps guide future development.

**Comment by Dandy64** [comment]
> @Dandy64
> 
> > Let's say I am sorting by Date on my Bank Account, while on my Cash Account I prefer always to see sorting by Payee.
> 
> I'm interested to understand the reason for your preference for keeping your Cash account _always_ sorted by payee?
> 
> How are you using this Cash account please? Is it really representing cash-in-hand/in the wallet? Ans are you therefore paying cash to your payees?
> 
> Do you not wish to know how the balance changes over time, which you obviously can't see if the account is always sorted by payee?
> 
> Understanding how MMEX is used (and why) helps guide future development.
Thanks all for the quick answer. 
Well, the example with the Cash account _was not good_, sorry. 
Actually, I **always** use sorting by date. But recently I faced a weird problem with the sorting.
I have several accounts, but my main accounts are Bank and Creditcard. When I want to sort my Bank account transaction by date, I receive the wrong order. In order to make it correct, I need to sort it by transaction ID (I always kept it hidden before since I do not care about the ID), and just after that, I sort by date. In this case, I am getting the correct order.
However, if I open my Creditcard account, I see that the sorting order is not correct! So I need to play with ID and Date sorting again in order to get the correct order.
But if I go back to the Bank account, the sorting is wrong again.
So this is a reason why I would prefer to have and keep the sorting separate for every screen.
I am not sure if have explained the problem clearly enough...

**Comment by tactilis** [comment]
@Dandy64 
> Well, the example with the Cash account was not good, sorry.
Actually, I **always** use sorting by date.

Then your problem of 'wrong' transaction order will be fixed in the v1.6 release, which is coming soon. And you won't need to display or click on the the ID column. Sorting by Date, either ascending or descending, will always give the correct Date & ID sort order.

You could install 1.5.20 for now until 1.6 is out if the behaviour of 1.5.21 is a problem for you.
