### ISSUE TITLE
Balance

### ISSUE THREAD

**Issue by Hayling47** [moneymanagerex/moneymanagerex#5138]
MMEX version:
 - [ ] 1.5.19
 - [ ] 1.5.20
 - [x] 1.5.21
 - [ ] 1.5.22 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Account Balance NOT correct, highlighted "RED".
Add screenshot or other files if needed.
![image](https://user-images.githubusercontent.com/114566853/192724175-daca6f19-6b20-45fe-9cc9-539095b015c9.png)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [x] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by Hayling47** [comment]
Just noticed everything from item date 27/09/22 incorrect.

**Comment by tactilis** [comment]
This is due to the implementation of sorting of Primary and Secondary columns in 1.5.21, which led to unwanted behaviour when sorting by the Date column.

The fix will be in 1.5.22

Your Dates (primary) are sorted in descending order but your transaction IDs (secondary) for the same date are in ascending order.

The easiest thing to do is to reinstall 1.5.20 and use that until 1.5.22 is released.

Alternatively, you could install the Beta version of 1.5.22 that includes the fix:

https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/44894486/job/8at7didfxla94409/artifacts
