### ISSUE TITLE
Account balance 

### ISSUE THREAD

**Issue by tycariadus** [moneymanagerex/moneymanagerex#5139]
MMEX version:
 - [ ] 1.5.19
 - [ ] 1.5.20
 - [x] 1.5.21
 - [ ] 1.5.22 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
Balances of an account when transactions are dated the same day are calculated incorrectly.
Please describe your issue with details.
Add screenshot or other files if needed.
![image](https://user-images.githubusercontent.com/36563561/192830933-dcf29645-c204-465e-ad67-684a7fb18ef9.png)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by tactilis** [comment]
This is due to the implementation of sorting by Primary and Secondary columns in 1.5.21, which led to unwanted behaviour when sorting by the Date column.

The fix will be in 1.5.22

Your Dates (primary) are sorted in descending order but your transaction IDs (secondary) for the same date are in ascending order.

The easiest thing to do is to reinstall 1.5.20 and use that until 1.5.22 is released.

Alternatively, you could install the Beta version of 1.5.22 that includes the fix:

https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/44894486/job/8at7didfxla94409/artifacts

**Comment by tycariadus** [comment]
Thanks!

 

Simon

**Comment by Harleypete** [comment]
This bug is still active in version 1.6.2 as of today (08/01/2023). This currently means that balances on two of my accounts are incorrect.

**Comment by ovari** [comment]
@whalley should this issue be unpinned? Thank you

**Comment by whalley** [comment]
I suspect so 👍
