### ISSUE TITLE
Assets, "Initial Balance" is not displayed.

### ISSUE THREAD

**Issue by renato-mmex** [moneymanagerex/moneymanagerex#5174]
MMEX version:
 
 - [x] 1.5.22 Beta

Operating System:
 - [x] Windows

# Description of the bug

**In the main display, assets, "Initial Balance" is not displayed.**

Is the bug reproducible? 
 - [x] Always 
 
<img width="561" alt="image" src="https://user-images.githubusercontent.com/76920138/195314669-40ee38bf-f686-4d4b-9ff1-3dbadda11e02.png">
<img width="225" alt="image" src="https://user-images.githubusercontent.com/76920138/195314721-9a8f30c0-a5f0-474c-a2a2-4aef8f9685bd.png">
<img width="684" alt="image" src="https://user-images.githubusercontent.com/76920138/195314772-499ab8ba-7336-43c5-8f20-569bcb5df8e7.png">

**Comment by n-stein** [comment]
I'm not sure this is a bug. The widget is reporting the asset value, not the asset account balance. These things are not the same, at least not the way assets are currently implemented in MMEX.

I couldn't find any documentation on the asset functionality, so I've tried to piece it together from looking at the code and testing how it behaves in regards to normal and asset transactions. Maybe I am completely wrong and I hope someone will come along and correct me if that is the case, but here is what I've found: The asset account is merely a transaction facilitator. It gives you a place to hold transactions which raise & lower the asset's value which are not sourced from another account. Notably the way this works is that you withdrawal from the asset account to the asset to increase the asset value and deposit from the asset to the asset account to decrease the value. This means that the impact of an asset transaction on the asset value is exactly opposite the sign in the asset account (which admittedly is a bit confusing). Also note that asset transactions can be stored in any other account, so the asset account doesn't show all transactions which impact the asset's value. Share accounts work exactly the same way -- they allow you to move funds to/from stocks but the balance of the share account is not the value of the stock.

Here's what I see happening in this instance:

1. You initially set your asset value at 10k. This value is transitory -- it gets recalculated every time you create or change an asset transaction based on the sum of the withdrawals and deposits to/from the asset across all accounts (not just the asset account).
2. You then set the initial balance on your asset account to 10k. As stated above the balance of the asset account is independent of the asset value, so this 10k initial balance does not impact the value of the asset. You need to enter a 10k withdrawal asset transaction to move that 10k from the asset account to the asset -- this is why in the normal account creation flow immediately after creating the asset account the system prompts you for a withdrawal transaction for the initial asset value.
3. You then entered a 5k deposit asset transaction. Entering this transaction forced the value of the asset to be recalculated. Since you are missing the initial 10k withdrawal asset transaction the only asset transaction the system sees is your 5k deposit asset transaction. As stated above a deposit increases your asset account balance by 5k but reduces the asset value by 5k, leaving you with a -5k asset balance which is accurately reflected on the home screen.

Correct me if I'm wrong, but it looks like your intent was to enter a 15k automobile asset where 5k of the value comes from a gift and 10k comes from some other source. Here are a few ways you could set that up:

1. Set the initial asset value to 15k.
2. Set the asset account initial balance to 10k
3. Add a 15k withdrawal asset transaction to the asset account. This sets the asset value to 15k.
4. Add a normal 5k deposit transaction (not an asset transaction) to the asset account.

You would end up with something like this:
![image](https://user-images.githubusercontent.com/16599929/196489666-6274afa4-32a5-4601-98ce-c6b2d604892e.png)
![image](https://user-images.githubusercontent.com/16599929/196488261-84c94224-ca0d-45da-8e52-f44908a89153.png)

In reporting you would see a 15k expense (the purchase of the car) and 5k gift income for a total expense of 10k.
![image](https://user-images.githubusercontent.com/16599929/196489977-235dfe1b-5378-4f47-a645-1854bfe0f033.png)

If your initial 10k comes from your checking account, you could also set it up like this:
1. Set the initial asset value to 15k.
2. Set the initial asset account balance to 0.
3. Add a 10k withdrawal asset transaction to your checking account.
4. Add a normal 5k deposit transaction (not an asset transaction) to the asset account.
5. Add a 5k withdrawal asset transaction to the asset account

Again, you end with a 15k asset, this time with 10k coming from your checking account and 5k coming from a gift. Reporting is the same -- 5k income and 15k total expense (only this time the expense is split between two accounts).
![image](https://user-images.githubusercontent.com/16599929/196488172-e8ddb5fc-38d5-4836-b234-da94874b2854.png)
![image](https://user-images.githubusercontent.com/16599929/196488106-f0bc536d-257d-4097-99b5-b6d50ff38c08.png)
![image](https://user-images.githubusercontent.com/16599929/196488236-baa60da2-9d13-4d43-a7a2-0cfd7099a9ff.png)

I do think there is a bug in the summary reports -- they should be showing the asset value not the asset account balance. Currently your 15k car wouldn't show up in the summary report unless you put 30k in the asset account then transfer 15k to your car asset.

Hope this helps.

**Comment by tactilis** [comment]
Great detective work @n-stein. And thank you for writing it up here.

**Comment by whalley** [comment]
> Great detective work @n-stein. And thank you for writing it up here.

Yes, I've never dug into asset workings in any great detail as I don't use them. This is a good summary. I'll see if we can create a section on the main website to hold nuggets like this...

**Comment by n-stein** [comment]
> @n-stein Do you want to create a bug report for the summary reports

Done

**Comment by renato-mmex** [comment]
**I seem to have caused some confusion there.**
My example was only meant as a sample, not as a real booking.
.
My problem is: when I started with MMEX in 2009, for example, I had to record the initial values (house, car, etc.) of my valuables. To do this, I recorded an "Initial Balance" value, as I do with bank accounts. Since these values are not accounted for, I have been keeping an additional Excel listing for years and I would like to stop managing this.

**Comment by whalley** [comment]
@renato-mmex Would that 'initial value' not have been better set here?
![CleanShot 2022-10-19 at 09 57 43@2x](https://user-images.githubusercontent.com/487345/196645611-04c20f73-fabd-4cf6-b855-7a913ce2cd6e.png)

**Comment by renato-mmex** [comment]
In the latest version I can no longer edit an account:

<img width="274" alt="image" src="https://user-images.githubusercontent.com/76920138/196686887-e7830f07-6542-4268-813b-d00e8f9bd6b6.png">

<img width="526" alt="image" src="https://user-images.githubusercontent.com/76920138/196687299-4b0bca53-d0d9-445c-83c2-93b1859c1307.png">

**Comment by n-stein** [comment]
@whalley Agreed. The asset value field will set the initial value on the asset. But simply entering the initial value during asset creation doesn't create any checking transactions, so if you make a second asset transaction it will overwrite the value you enter here. You do need to submit the initial withdrawal asset transaction at the end of the asset creation flow to make that value stick.

**Comment by whalley** [comment]
> In the latest version I can no longer edit an account:
> 
Try the latest version. https://ci.appveyor.com/project/moneymanagerex/moneymanagerex

@n-stein did spot an error that may have been resolved here: https://github.com/moneymanagerex/moneymanagerex/issues/5191
