### ISSUE TITLE
Account Summary reports do not include asset values

### ISSUE THREAD

**Issue by n-stein** [moneymanagerex/moneymanagerex#5197]
MMEX version:
 - [X] 1.5.19
 - [X] 1.5.20
 - [X] 1.5.21
 - [X] 1.6.0 Beta 2

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

The summary reports show the balance of the asset account but do not include the value of the assets. This leads to assets not being reported accurately.

Asset value is 15k
![image](https://user-images.githubusercontent.com/16599929/196567385-f3f0927b-dede-4b91-b3aa-bbf4130c3bee.png)

Asset account balance is 0
![image](https://user-images.githubusercontent.com/16599929/196567450-0fecbd76-5418-43e8-9a66-a463db9a58be.png)

Monthly summary report shows net value of 0
![image](https://user-images.githubusercontent.com/16599929/196567610-21a6e4b3-ccf8-4089-a983-1078e848f289.png)

Yearly summary report shows net value of 0
![image](https://user-images.githubusercontent.com/16599929/196567597-31c1c89c-af76-41c2-ad32-5cf86a3f2774.png)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
Create an asset
Assign value to the asset by making a withdrawal asset transaction
Execute a summary report

Expected result:
The asset value is included in the summary report

Actual result:
The asset is not included in the summary report

# Additional information
Found during debug of #5174

**Comment by n-stein** [comment]
I'm trying to determine how to assign an asset value given a particular date and I'm getting hung up with the auto-depreciation/appreciation. How should these work in conjunction with changes in asset value due to asset transactions? Right now it simply assumes that the current asset value has been the same since the asset STARTDATE. However, what if my asset value has changed as a result of asset transactions since that time? Should the depreciated/appreciated value be a sum of the depreciated/appreciated amounts of each individual transaction?

Suppose I have a collector car which I set to appreciate at a rate of 5%. I initially purchase the car for $10,000. After 1 year the value is now $10,500. When I have owned the car for 2 years I apply a fresh coat of paint that increases the value by $2,000. According to current design the system will calculate the value of the car as $12,000 &#x00D7; 1.05<sup>2</sup> = $13,230, but the real value of the car is only $10,000 &#x00D7; 1.05<sup>2</sup> + $2000 = $13,025.

At year 5 then what is my car's value? Is it:

a. $12,000 &#x00D7; 1.05<sup>5</sup> = $15,315 (this is the current design)
b. $10,000 &#x00D7; 1.05<sup>5</sup> + $2000 &#x00D7; 1.05<sup>3</sup> = $15,078
c. something else?

**Comment by tactilis** [comment]
The answer is:  _"c. something else"_ because, in truth, you cannot say what the _real_ value of the car is, since it will depend on many factors and is only worth as much as someone will pay for it when it is up for sale.

However, in the context of the _estimate_ of appreciated (or depreciated) value of an asset in MMEX, I think the answer to your question _"Should the depreciated/appreciated value be a sum of the depreciated/appreciated amounts of each individual transaction?"_ is yes, that seems the most reasonable approach.

The problem you have highlighted is a bit like the differences in calculation between ROI and IRR, where ROI just considers the start and end values over a single timespan, whereas IRR takes account of the cash inflows (or outflows) over a number of time periods.  [https://www.investopedia.com/articles/investing/111715/return-investment-roi-vs-internal-rate-return-irr.asp](https://www.investopedia.com/articles/investing/111715/return-investment-roi-vs-internal-rate-return-irr.asp)

**Comment by n-stein** [comment]
PR #5341 adds Assets to the summary reports, positioned beside the "Stocks" column:

![image](https://user-images.githubusercontent.com/16599929/202544522-7c2acf49-173d-4fcd-9ec2-8c043118d4e4.png)

![image](https://user-images.githubusercontent.com/16599929/202544402-22dd9db3-d736-40b0-8bd6-90ddda36f81e.png)
