### ISSUE TITLE
Transaction Filter dialog loses its saved display location on the screen 

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#5215]
MMEX version:
 - [x] 1.6.0 Beta.2 64-bit Git commit: e80b1df (2022-10-23)

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

After repeatedly opening the Transaction Filter dialog and clicking OK, firstly from a Bank Account view, then from the All Transactions view, the dialog is erroneously displayed near the top left of the screen instead of where the user last positioned it.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Display the Bank Account Transaction Filter dialog and click OK.
2. Display the All Transactions Transaction Filter dialog and click OK.
3. Repeat these steps and observe that the dialog eventually appears near the top left of the screen instead of in the centre of the screen.

Expected result:

The dialog should always be displayed where the user last positioned it.

Actual result:

As shown in the video, the dialog is eventually displayed in the wrong location. Sometimes it does this after being displayed just a couple of times while swapping between Bank Account and All Transactions views. Sometimes it takes more attempts to make this happen.

https://user-images.githubusercontent.com/4060092/197417813-1b182e08-cac5-438b-9e2d-1bd38133e1a8.mp4

**Comment by whalley** [comment]
@tactilis I can't seem to reproduce, is this still happening?

**Comment by n-stein** [comment]
@whalley I can reproduce this in the current build. It seems to only apply to the "All Transactions" view, and only if the transaction filter is already applied in that view. Otherwise, the filter dialog opens in the center as expected.

I can reproduce with these steps:

1. Set the "All Transactions" view to "View with Transaction Filter..." and apply any filter. If it is not currently in this mode, it opens in the filter dialog in the screen center.
2. Navigate to any other account.
3. Navigate back to "All Transactions" and reselect "View with Transaction Filter". Now the filter dialog opens in the top left of the screen.

**Comment by n-stein** [comment]
Changing this line:

https://github.com/moneymanagerex/moneymanagerex/blob/cc2714975ebc3a539f95bdac2420e5fe484232cd/src/mmcheckingpanel.cpp#L112

to 

`m_trans_filter_dlg = new mmFilterTransactionsDialog(parent, m_AccountID, false, json);`

resolves the issue on my system.

**Comment by whalley** [comment]
@n-stein Thanks, yes I maanged to reproduce and can confirm that the change you mentioned does indeed fix it.
