### ISSUE TITLE
Keyboard control in date widget

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5216]
1. `New Transaction` window
2. Date field has focus
3. Press Alt+↓ opens date widget
4. Please allow pressing the arrow keys (↓↑←→) to move the date selected

![Date widget in New Transaction](https://user-images.githubusercontent.com/17465872/197418234-cb91b669-00e9-4de9-9b2b-40c53f1d317f.png)

What do you think?

Thank you

Linux Mint 21 Cinnamon
```
Money Manager Ex
Version: 1.6.0-Beta.2 64-bit
• Build on Oct 22 2022 03:26:47
• Database version: 15 • (aes128cbc)
```

**Comment by tactilis** [comment]
FYI, on Windows, the Arrow keys (move by day), Page up/down (move by month), and Home/End (move to start/end of month) work correctly.

**Comment by ovari** [comment]
Neither `Home`/`End` nor `Page Up`/`Page Down` work on GNU/Linux.

@tactilis do these (case insensitive) keys work in Windows:
1. `t`/`T` selects **T**oday
2. `y`/`Y` selects the _first_ day of the **Y**ear (relative to the currently selected date). If it is the first day of the year, then it selects the first day of the previous year
3. `r`/`R` selects the _last_ day of the yea**R** (relative to the currently selected date). If it is the last day of the year, then it selects the last day of the next year
4. `m`/`M` selects the _first_ day of the **M**onth (relative to the currently selected date). If it is the first day of the month, then it selects the first day of the previous month
5. `h`/`H` selects the _last_ day of the mont**H** (relative to the currently selected date). If it is the last day of the month, then it selects the last day of the next month

If the keys above don't work on Windows, should a new issue be created for them?

The above keys work in [Intuit](https://www.intuit.com/) and [Quicken](https://www.quicken.com/) and provide an enhanced user experience.

What do you think?

Thank you

**Comment by whalley** [comment]
> FYI, on Windows, the Arrow keys (move by day), Page up/down (move by month), and Home/End (move to start/end of month) work correctly.

Arrow keys work fine on MacOS also.

**Comment by tactilis** [comment]
> do these (case insensitive) keys work in Windows:
> 
>     1. t/T selects Today
>     2. y/Y selects the first day of the Year (relative to the currently selected date). If it is the first day of the year, then it selects the first day of the previous year
>     3. r/R selects the last day of the yeaR (relative to the currently selected date). If it is the last day of the year, then it selects the last day of the next year
>     4. m/M selects the first day of the Month (relative to the currently selected date). If it is the first day of the month, then it selects the first day of the previous month
>     5. h/H selects the last day of the montH (relative to the currently selected date). If it is the last day of the month, then it selects the last day of the next month

The keys you mention do nothing on Windows.

My thoughts:

- I have not come across calendar shortcuts like these in any app before (only arrow keys, page up/down and home/end).
- Relatively few people take time to learn or to make use of shortcuts - more people use the mouse than keyboard shortcuts (other than arrows, home/end and page up/down).
- There is already an easy way to modify the date using arrow keys, page up/down, and overtyping directly in the date field.

The video shows the use of these keys:

1. Day: Down/Up arrow to decrement/increment the day, then End/Home to jump to last/first day of the month.
2. Right arrow to move to the Month field.
3. Month: Down/Up arrow to decrement/increment the month, then End/Home to jump to last/first month of the year.
4. Right arrow to move to the Year field.
5. Year: Down/Up arrow to decrement/increment the year. End/Home are not useful because they jump min/max year (1601/9999).

In addition, at any point, while Day, Month, or Year is highlighted, you can just overtype the digits directly.
 
https://user-images.githubusercontent.com/4060092/197495990-fcd96c51-4ba6-4e2e-afe8-9c0011c4715a.mp4
 
> If the keys above don't work on Windows, should a new issue be created for them?

Personally I don't see that having these keys would provide significant benefit.

**Comment by whalley** [comment]
To be honest I'm not sure what control we have over this. Ihttps://docs.wxwidgets.org/trunk/classwx_date_picker_ctrl.html I suspect on Windows and Linux this is using native controls (on MacOS I had to write a specific control to simulate).

> Personally I don't see that having these keys would provide significant benefit.

Agreed.

**Comment by PMaff** [comment]
Late addon: I was looking at the samples from wxWidget 3.2.8 and the documentation.
Documentation says "The control can be edited using the keyboard" here:
https://docs.wxwidgets.org/3.3/classwx_date_picker_ctrl.html
but there is no description that turns this on explicitly on in code,
at least I did not find one.
It also says "depending on the styles used and the platform", which somehow confirms the
opinion of @whalley above.

I also tried the self compiled samples from wxWidget 3.2.8:
and there I can use STRG -> to select the next month and STRG arrow down to select
the next year.
STRG <- for previous month
STRG arrow up for previous year

I also tried the orage calendar on Ubuntu and this shows a tiny frame around the selected date,
if you use e.g. the down arrow of the numeric pad.
If you then type SPACE then this date is selected.

<img width="202" height="229" alt="Image" src="https://github.com/user-attachments/assets/77291a57-bc28-4d97-bae8-b2eb3ff5e658" />

I tried this in mmex and the only difference is that this frame is not displayed.
But this is also not displayed in the wxWidget sample ./samples/widgets/widgets .

**So keyboard is working in the date picker of mmex**, the only thing missing is this frame around the
date to see, which date is selected, if you use the up/down/left/right arrow keys of the
numeric pad.
Now it is a bit of guessing without this frame in mmex (wxWidget?).
