### ISSUE TITLE
Show notes of split transactions

### ISSUE THREAD

**Issue by Dandy64** [moneymanagerex/moneymanagerex#5251]
# Description of the feature

There is a new future - the possibility to add a note for every row of a split transaction.
It would be useful to copy all these notes to the main notes window of the transaction.

# Use cases

Let's say we have a split transaction:
Transaction 1 - $10, Note: A bottle of wine for me
Transaction 2 - $2, Note: A new toy for my cat

But these notes are invisible until I clicked on them (or Mouse Over).

At the same time, there is a main window of the transaction with the general notes area. I think it would be cool to see all the notes from the split together, something like that:
_______________________________
A bottle of wine for me - $10
A new toy for my cat - $2
_______________________________

**Comment by tactilis** [comment]
IMO, it's not a good idea **copy** the split notes to the transaction Notes.

Lots of what-ifs:

- What if you already have some transaction Notes - should the split notes be copied over them (i.e replacing them). Or should the split notes be appended to the transaction Notes?

- What if you edit the split notes after they have been _copied_ to the main Notes? Should they be copied again?

- What if you edit the main Notes (altering the split note text) and then edit the split?

Better perhaps just to:
1. On the Edit Transaction dialog, visually flag the fact that some split notes exist so that you know to hover over the split button to view the notes tooltip.
2. _Maybe_ **display** the split notes, following any main Notes, in the Notes column of the transaction list.

I think this achieves what you are asking for @Dandy64 but does not require notes to be copied.

**Comment by Dandy64** [comment]
Well, I can answer most of your what-ifs, but it looks like I do not need it. 
Your solution looks much better to me!

**Comment by whalley** [comment]
> 1. On the Edit Transaction dialog, visually flag the fact that some split notes exist so that you know to hover over the split button to view the notes tooltip.
> 2. Display the split notes, following any main Notes, in the Notes column of the transaction list

If we were to do (2) why do we need (1) ?

For (2) not sure what you are proposing. Are you suggesting adding a read-only field after the existing, editable, notes field?

**Comment by Dandy64** [comment]
> Are you suggesting adding a read-only field after the existing, editable, notes field?

As for as I understand, **tactilis** has suggested adding an additional _column_to the grid where we can see all the transactions. 
![image](https://user-images.githubusercontent.com/83161661/198865601-0927c245-9371-4b3e-bf41-80b02923d3eb.png)

**Comment by whalley** [comment]
Oh, I misread. Having read it again I see what was suggested.

Not convinced we need yet another column on the transaction list. We could append any split notes to the main transaction note I guess, but the space to display is obviously limited.

As for the "On the Edit Transaction dialog, visually flag the fact that some split notes exist so that you know to hover over the split button to view the notes tooltip." Not sure we need to clutter I with yet another marker, I think what we have should be sufficient in that it highlights a split transaction is present. We can however look to add the split notes to the tooltip when hovering).

**Comment by tactilis** [comment]
@Dandy64 
>  tactilis has suggested adding an additional column to the grid 

No, I didn't suggest this.

@whalley 
> Not convinced we need yet another column on the transaction list.

Agreed. We certainly do not need another column.

> We could append any split notes to the main transaction note I guess

Exactly that. I proposed:

> Display the split notes, following any main Notes, **in the Notes column** of the transaction list.
 
 
@whalley 
> but the space to display is obviously limited.

That doesn't matter. The point is that the user would be able to see that there are some split notes present, whereas, currently there is no indication of this.

Scenarios (if the change is implemented):

**1. No Transaction Notes / No split notes**
Notes column is blank in the transaction list
User knows there are no notes

**2. Some Transaction Notes / No split notes**
Notes column shows the Transaction Notes (up to the limit of the column width)
User knows there are some notes and gets to see some useful information in the transaction list.

**3. No Transaction Notes / Some split notes**
Notes column shows the split notes (up to the limit of the column width)
User knows there are some notes and gets to see some useful information in the transaction list.

**4. Some Transaction Notes / Some split notes**
Notes column shows the Transaction Notes +  the split notes (up to the limit of the column width)
User knows there are some notes and gets to see some useful information in the transaction list.

At the moment, scenarios 1 and 3 look the same - and even if you open the transaction dialog, you still don't know that there are any split notes _unless_ you hover over the split button (which was the original point of @Dandy64's request).

**Comment by tactilis** [comment]
@vomikan
I see you have added a special entry to the Frequently Used Notes button, which if selected, enters the split notes into the transaction's Notes field.
 
![image](https://user-images.githubusercontent.com/4060092/198888191-af28c149-df4b-4c1b-8e52-ffdb959f48a4.png)


I'm sorry, but I think this is a bad solution for the following reasons:

1. The Frequently Used Notes button is insensitive if the user has not entered any transaction Notes so far. In this case, the user would not be able to display your "Generate notes from split categories" menu entry.
 
![image](https://user-images.githubusercontent.com/4060092/198888600-44682cab-236a-4cc3-a4f2-6cbeabc946ec.png)


2. The implementation mixes together 2 different concepts: a) Displaying a list of frequently used notes, and b) copying the split notes into the Notes field. This is not good UI design.

3. Being hidden under the frequently used notes button, the function to "Generate notes from split categories" will not be discovered by many users.

4. Selecting "Generate notes from split categories" wipes out any transaction Notes that the user already had and _replaces_ them with the split notes. Not good.

6. The implementation requires the user to remember to click "Generate notes from split categories" to update the Notes if they add or amend a split note.


The reason that I have proposed here https://github.com/moneymanagerex/moneymanagerex/issues/5251#issuecomment-1296215313 simply _displaying_ the split notes after any transaction Notes **in the transaction list** column is that it just works. The user doesn't have to do anything.

It seems obvious to me that split notes are not 'special' in any way. In the past, if the user wanted to add notes to explain the breakdown of a split transaction, they had no choice but to enter details in the Notes field and they would be displayed in the Notes column of the transaction list.

Now, in v1.6.0, we have the ability to enter the notes in the _logical_ place (i.e. alongside each split). In this case, it still makes sense to display them in the Notes column of the transaction list (after any transaction Notes that the user may have also entered). I think I explained it clearly in the 4 scenarios in https://github.com/moneymanagerex/moneymanagerex/issues/5251#issuecomment-1296215313

**Comment by tactilis** [comment]
> Notes concatenation

Thanks @whalley (and to @vomikan for prompting me to more clearly justify the change)

Just one small thing:

If the transaction Notes field is empty, then there should be no leading space in the transaction list because Notes + split notes does not need a separator. 

The superfluous space messes up the column alignment.
 
![image](https://user-images.githubusercontent.com/4060092/198892432-83ba6e70-b9d4-479e-a431-7e7de16f7119.png)

**Comment by whalley** [comment]
> If the transaction Notes field is empty, then there should be no leading space in the transaction list because Notes + split notes does not need a separator.

I thought I had done that but forgot that the Default for the Trim() methid is to remove from right side! Fixed.
