### ISSUE TITLE
Rolling account balance still wrong

### ISSUE THREAD

**Issue by scubapaul** [moneymanagerex/moneymanagerex#5333]
MMEX version:
 - [ ] 1.5.20
 - [ ] 1.5.21
 - [x] 1.6.0
 - [ ] 1.6.1 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

The issue with the rolling account balance has not been rectified in version 1.6.0 despite claims that it has been. 
The balance at the end of a days transactions are correct but the individual transaction balances are out of order.
You can see from my example that at the end of 28/10/22 my balance is £22,162.50. The next transaction is a withdrawal of £35.89. The balance now shows as £22,282.61 when it should be £22,126.61.

# Reproduction
![20221115_143752](https://user-images.githubusercontent.com/111243664/201960412-486a0371-6946-4278-a006-7b9e845494e5.jpg)

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by scubapaul** [comment]
Slight correction. Balance after withdrawal should be £22,162.61

**Comment by tactilis** [comment]
What sort order is shown for you here (which columns and up or down triangles)?

![image](https://user-images.githubusercontent.com/4060092/201968559-b616c625-4f58-4a47-953a-4460e31089ce.png)

If you click on the Date column header to reverse the date order _and then_ click on it again to return to Date descending, does that fix the problem for you?

**Comment by scubapaul** [comment]
I don't know. Gone back to version 1.5.20.I know that in version 1.5.21 that didn't work.Paul.Sent from my Galaxy
-------- Original message --------From: Martin ***@***.***> Date: 15/11/2022  16:11  (GMT+00:00) To: moneymanagerex/moneymanagerex ***@***.***> Cc: scubapaul ***@***.***>, Author ***@***.***> Subject: Re: [moneymanagerex/moneymanagerex] Rolling account balance still wrong (Issue #5333) 
What sort order is shown for you here (which columns and up or down triangles)?

If you click on the Date column header to reverse the date order and then click on it again to return to Date descending, does that fix the problem for you?

**Comment by tactilis** [comment]
Please could you post your reply here [https://github.com/moneymanagerex/moneymanagerex/issues/5333](https://github.com/moneymanagerex/moneymanagerex/issues/5333) and not by email.

@scubapaul
> I don't know. Gone back to version 1.5.20.

To assist you requires some information that the photograph of your the screen did not show, i.e the column headings and the sort order.

Obviously, you can stay on 1.5.20 for as long as you wish but eventually, you may want to update to 1.6.x. It would be better if we solved the problem you are having now. Otherwise, there wasn't much point in you reporting it.

> I know that in version 1.5.21 that didn't work.

That's correct. There was a bug in 1.5.21, which was fixed in 1.6.0.

Please take a look at this report https://github.com/moneymanagerex/moneymanagerex/issues/5238 where the user was having the same problem that you are reporting. The problem was easily solved for them.

**Comment by scubapaul** [comment]
I have reloaded version 1.6.0 and clicked twice on the date column which now seems to have sorted this issue.

**Comment by tactilis** [comment]
@scubapaul
> I have reloaded version 1.6.0 and clicked twice on the date column which now seems to have sorted this issue.

That's good to hear.
