### ISSUE TITLE
Reconciled amount incorrect

### ISSUE THREAD

**Issue by howff** [moneymanagerex/moneymanagerex#5370]
MMEX version:
 - [ ] 1.5.21
 - [ ] 1.6.0
 - [x] 1.6.1
 - [ ] 1.6.2 Alpha
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

The reconciled amount is not recalculated when a transaction is deleted.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps: add transaction, reconcile it, delete it

Expected result: reconciled amount changes

Actual result: no change

**Comment by howff** [comment]
Do I need to fix my database or is it a calculated field that will be correct in the next version?

**Comment by whalley** [comment]
It's calculated. There was a bug where it was including the deleted transactions in the calculation. If you go to your deleted transactions and permanently delete them then everything should be calculated correctly.

**Comment by howff** [comment]
Thanks very much for the quick and easy fix :-)   (Shame I wasted 3 hours trying to find a mistake in my entries!)  Was this bug introduced recently?  mmex has been very trustworthy (for me) until now.

**Comment by whalley** [comment]
> Thanks very much for the quick and easy fix :-) (Shame I wasted 3 hours trying to find a mistake in my entries!) Was this bug introduced recently? mmex has been very trustworthy (for me) until now.

Yes, the ability to retain deleted transactions for a defined time was introduced in the last release, with this bug. If you go to settings, under the "Others" section you will see a  "Days to retain deleted transactions" - if you set this to ZERO then the transaction will be instantly deleted - you can do this for now if you wish.

**Comment by whalley** [comment]
> @whalley - we might want to consider putting the new Features/Enhancements before the Fixes as that will increase the chance of them being read.

Good idea.

**Comment by howff** [comment]
I'm happy to use the new version and report bugs, because I'm comfortable with github etc, unlike most users I guess.

In this case the issue is not whether or not I was aware of the Recycle Bin for Deleted transactions, because from my point of view the bug was in the calculation of the Reconciled total, and I actually thought it was database corruption. It took me a few hours to work out that I could replicate the problem on an older backup file by repeatedly deleting transactions.

**Comment by howff** [comment]
I would also like to express my thanks to the developers, and the rapid response to issues :-)

**Comment by tycariadus** [comment]
This issue does not seem to have gone away / been fixed.  We always permanently delete a deleted item and yet the reconciled balance is incorrect.  The balance in the balance column is correct.  Please advise - thanks.

Simon

**Comment by tactilis** [comment]
@tycariadus 
> We always permanently delete a deleted item and yet the reconciled balance is incorrect. The balance in the balance column is correct.

Please could you confirm:

1. Are you using version 1.6.1 or 1.6.2 Beta? See `Help | About`
 
 
2. Do you have this option set to zero?

![image](https://user-images.githubusercontent.com/4060092/205438564-f4b12ea9-1e1c-4533-a828-3fa1dade91d8.png)
 
 
3. That you have the transaction list sorted by Date (either ascending or descending)?

![image](https://user-images.githubusercontent.com/4060092/205438699-09537275-1d73-4f6e-9597-463452e30566.png)

4. That you do *not* have any Unreconciled transactions?
If you sort by the Status column, then you can quickly scroll to find any without an 'R' status. Alternatively, click `View with Transaction Filter` and filter on `Status: All Except Reconciled`

**Comment by tactilis** [comment]
@tycariadus 

Please could you reply directly on github here https://github.com/moneymanagerex/moneymanagerex/issues/5370 rather than by email. If you do that you will be able to paste screenshots, which may help us resolve your problem.

You said that _"the **reconciled** balance is incorrect"_  but you also wrote _"I do have a few unreconciled items"_.

The Account balance includes all transactions (except Void). The Reconciled balance excludes unreconciled transactions.

Here are three examples based on an account with an Opening Balance of £100 to which 3 transactions of £10, £20, and £30 has been added.

**1. All Unreconciled**
 
![image](https://user-images.githubusercontent.com/4060092/205440731-fc1c3304-9ea8-4ef9-83e4-fa15249aa500.png)
 
**2. All Reconciled**

![image](https://user-images.githubusercontent.com/4060092/205440747-4f42ee5c-ee25-4c29-bf1e-2c4b37d39537.png)
 
**3. Some Unreconciled**
 
![image](https://user-images.githubusercontent.com/4060092/205440982-06dc4ae1-1890-4c31-9ab3-632bbc0a3da8.png)
 

Do the balances shown in these examples help explain what you are seeing?

If not, could you paste screenshots showing the discrepancy that you have please.

**Comment by tycariadus** [comment]
It's similar to Account View 3, i.e. some unreconciled per the screenshot
![image](https://user-images.githubusercontent.com/36563561/205443377-9bf8501b-85ac-4de1-960c-a9cdd57e3cee.png)

**Comment by tactilis** [comment]
@tycariadus 

You say that _"It's similar to Account View 3, i.e. some unreconciled per the screenshot"_ but have you looked at the values in mr screenshot and understood why Account balance and Reconciled balance have the values that are displayed? These values are correct.

The Account balance and Reconciled balance will necessarily not be the same if some of the transactions are unreconciled.

Please could you sort your transactions by Date again, and then, based on the reconciled and unreconciled transactions that you have, could you please say what leads you to the conclusion that the Reconciled balance displayed is incorrect?

**Comment by tycariadus** [comment]
Yes Martin:

 

I looked at each example carefully and having been using this application
since 31 Dec 2017 I'm pretty sure I know how it works.  The reconciled
balance is the balance that should agree to my actual account / statement
and ever since the new release has had issues to do with items that were
deleted and the balance never changed.

 

Thanks

**Comment by tycariadus** [comment]
Hi Martin:

I've established that the days to delete is a setting per machine / pc and not in the database, so I have changed it on both pc's we open the file on and now it's fine - thanks!  Useful to let people know if they open the file on different machines using say OneDrive.

**Comment by tactilis** [comment]
@tycariadus 
> I've established that the days to delete is a setting per machine / pc and not in the database, so I have changed it on both pc's we open the file on and now it's fine - thanks! Useful to let people know if they open the file on different machines using say OneDrive.

I'm happy that you have found the answer.

You were seeing the effect of the deleted transactions bug, which is the subject of this issue. It affects 1.6.1 only. The fix has been made and will be included in the 1.6.2 release.

FYI, the Options settings are stored in the mmexini.db3 database (which will be local to your PC), not in your .mmb transaction database (of which you might have several depending on how you use MMEX).
