### ISSUE TITLE
Request for additional account types - Assets/Liabilities

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/moneymanagerex#544]
We have a user request. Please post your comments.
While we do have Assets, this seems a bit different. I assume the goal is to have a more accounting-oriented approach and is targetting businesses more than individuals. See below.

>At present, there are 4 account classes as per attached, namely:
1. Bank accounts
2. Credit card accounts
3. Investment accounts
4. Fixed deposit accounts

>I suggest adding 2 more classes, i. e.
1. Debtor (or Other assets 其它资产)
2. Creditor (or Other liabilities 其它负债)
They should be of similar nature as Bank and Credit card respectively.

**Comment by stef145g** [comment]
I basically agree.
I refer to my 2nd posting I made on a similar issue: **Savings Account missing** https://github.com/moneymanagerex/moneymanagerex/issues/542

A few months ago I posted a pull request that basically did a similar thing, which has since been withdrawn. It added subsections: Share Accounts, Asset Accounts, and Loan Accounts. I stopped working on this functionality to add further refinements for general use due to time commitments. Now it cannot be merged.

Loan Accounts were added to extend the Credit Card Accounts functionality. Asset Accounts had special features which allow transactions to link any other account, extending their potential functionality. Unfortunately, the Investment Accounts mentioned above are in essence, Stock Portfolio accounts, so Share Accounts were added to counter balance this, thus allowing the handling of dividends, purchase and sales of stock.

**Comment by guanlisheng** [comment]
@stef145g would we close this ?

**Comment by stef145g** [comment]
Although a Loan Account has been added, this needs further refinements, therefore leaving this open.

**Comment by vomikan** [comment]
Related issue: https://sourceforge.net/p/moneymanagerex/feature-requests/396/

**Comment by stef145g** [comment]
With the addition of the feature that an Asset is related to an Asset account, combined with Loan Accounts gives MMEX the ability to maintain assets and loans.
