### ISSUE TITLE
Disable different amounts for the transfers in the same currency

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/moneymanagerex#563]
Users report that the desktop application allows "Advanced" mode for transfers, where amounts in the same currency can differ.
This is either a bug or financial alchemy as I do not understand how is it possible to transfer funds by debiting €5 from one account and crediting only €3 to another. What would happen to the missing €2?
Thanks

**Comment by gabriele-v** [comment]
Consider example where your bank take 2€ for operation, personally I'll create two operations but there are some people that prefer to have all in one transaction.

**Comment by MisterY** [comment]
Whether some prefer it or not, the calculations will still be incorrect. The real solution to that is the support for split transfers. That way there would be one transaction that would include both the transfer and the bank charge. Let's not debilitate the program just because some find it easier that way. Who would remember that it was the bank that took those 2 Euros? There is no record of that and no accounting for the bank charge category. I think it is very wrong. A transfer is a transfer and we should not allow for the difference of 300 Euros because of mistyping, for example.

**Comment by guanlisheng** [comment]
@stef145g @vomikan any thought ?

**Comment by stef145g** [comment]
As a transfer is not accounted as income or expense, corrections to balances can be made using the Advanced Transfer feature such as currency transfers, or advanced circumstances.

Same currency transfers, would only be used by some user for special circumstances, such is the case where we need to record actual income and expense for tax purposes, but we don't want to record income or expenses that is either non taxable, or not real income or expense.

Transfers from special accounts of $0 to other accounts with the correct amount would come into play. This feature is made possible because a transfer can also be classified using a category, subcategory combination, to record non taxable income or expense, or balance adjustments for the reasons prescribed.

As for the previously mentioned bank operation's case, this would be recorded as 2 transactions. One as a transfer, the other as a debit.
