### ISSUE TITLE
Keyboard shortcuts `Import from CSV file`

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5640]
Please add keyboard shortcuts for:
1. Filename:
2. 0
3. 1
4. 2
5. 3
6. 4
7. 5
8. 6
9. 7
10. 8
11. 9
12. Account:
13. CSV Delimiter
14. Amount
15. From start:
16. From to:
17. Date Format:
18. Encoding:
19. Decimal Char
20. Colour (source string may be `Color`)

![Import from CSV file](https://user-images.githubusercontent.com/17465872/218224636-c8f24810-b129-4f63-bc3a-c4cbeaed37f2.png)

Thank you

**Comment by tactilis** [comment]
> Please add keyboard shortcuts for...

Keyboard shortcuts are not used as a way of jumping to a labelled field on a dialog.

ALT+character shortcuts are used to activate a command button. These buttons already have shortcuts.

**Comment by ovari** [comment]
> Keyboard shortcuts are not used as a way of jumping to a labelled field on a dialog.

Strange as other programs allow this, such as Thunderbird and LibreOffice.

![Thunderbird](https://user-images.githubusercontent.com/17465872/218278379-8e9f5610-be3b-4266-8ade-4636ae888a02.png)

![LibreOffice](https://user-images.githubusercontent.com/17465872/218278414-59511840-0ecd-4e66-a873-9ca14f0b7094.png)

Did you need other examples of other programs that allow keyboard accelerators to re-open this issue?

Thank you

**Comment by tactilis** [comment]
> Strange as other programs allow this, such as Thunderbird and LibreOffice.

Or more accurately:

"Strange as **_some_** other programs allow this..."

But most do not.

Some reasons for this:

1. On dialogs with lots of fields, it can be difficult to come up with sensible (unique) letters to act as the shortcuts.
2. The above problem is made even harder if you also have to translate the strings into different languages.
3. There is already a mechanism for moving from field to field (tab & Shift+tab)*, or of course by using the mouse.
4. The speed-up gained from using a keyboard shortcut is small if, as there often is, a need to enter values in several fields (i.e. tabbing is not significantly slower).


\* Note that there _is_ a specific problem with tab navigation on the `Import from CSV file` dialog; if you tab into the `CSV Delimiter` field, then it is currently not possible to tab out of it because it consumes all key presses. Maybe there is a way to fix that but I'm not sure how.
