### ISSUE TITLE
Transaction report charts

### ISSUE THREAD

**Issue by gabriele-v** [moneymanagerex/moneymanagerex#5685]
# Description of the feature
GRM reports are really good for power users, but I think that may be useful to have an option to add a charts to Transaction Report for "normal" users or even for power users like me if I don't need something heavily customized.

I'd imagine it like a 4 options:
- No Chart
- Bar Chart
- Line Chart
- Pie Chart

If "grouping" is enabled, it should consider the grouping item total, otherwise it should consider the single transaction.

Two other options of grouping should be added: group by month (it will be month+year obviously) and group by year 

# Use cases
- See the line chart of specific transactions over time (IE salary)
- See the line chart of grouped transactions over time (IE groceries or fuel grouped by month)
- See the pie chart of grouped transaction in specific time (IE a sort of category summary but with specific filters)

**Comment by gabriele-v** [comment]
@n-stein not sure about your next developments, but I think this may be really useful, actually GRM is too difficult and I had request from multiple friends for specific charts which actually are obtainable only through GRM but would be solved by the above new feature.

**Comment by whalley** [comment]
Not done any testing on it yet but one observation is that maybe the graph should be at the head of the report like all other standard reports.

**Comment by gabriele-v** [comment]
Yes, I've thought about it but it needs a rewrite of the code because actually group totals are calculated during the loop when generating HTML table.

**Comment by rmelillo76** [comment]
Nice work @gabriele-v !

Adding this javascript to the HTML may be a quick way to handle this, as it simply moves the chart to the top of the page:
This uses jQuery since it's already available to the report, but could probably be done using plain javascript too:

`$('.shadowGraph').insertAfter($('.shadowTitle'));`



![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/0b679f5b-936c-4d02-9844-f6b5e62b856a)


![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/2558815a-a27e-4866-a0f6-aeabe83e50e3)

**Comment by gabriele-v** [comment]
Nice trick @rmelillo76, I've sent a PR with the change

**Comment by whalley** [comment]
> Yes, hyperlink make sense but only if it's a trasaction, so group by not enabled, otherwise the key is not TRANSID but grouping item.

Oh, never tried it with 'Group By', I see what you mean. Leave as-is.

**Comment by rmelillo76** [comment]
Hi @gabriele-v 


I started to look at this and at first glance I thought Min and Max were being reversed in the example report below, but then I realized it's because the amounts are all withdrawals so the totals are both negative . But as a user, I would look at that I spent 164 on Fuel and 20 on Emissions, so 164 should be the max and 20 the min. Should we use absolute value to calculate instead - what do you think?

![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/d6d39607-94d7-4de3-8b12-2d64dc891943)

Also, the amounts are only showing whole dollars, not the cents in both the chart and the stats. I think we should show the full amount, just like the built-in reports with charts do.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/b4bdb4e2-483d-4b98-832f-36771c6b9503)

![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/5c67c228-c095-48d8-988d-d66a2f338802)

**Comment by gabriele-v** [comment]
Hello @rmelillo76,
regarding the maximum/mimimum I'm not sure about using the absolute value.
It may solve your case but will introduce other issues, consider for example if values are -5, +2, +7, in that case you will have minimum +2, which is not correct. Or if you have -5, +2, +3 you will have maximum +5. We may consider using absolute values only if all values are negative, but only in that specific case.

Regarding decimals you are right, it seems a bug and I'll fix it.

**Comment by whalley** [comment]
> We may consider using absolute values only if all values are negative, but only in that specific case

Think that could lead to confusion. The current behaviour seems clear to me.

**Comment by rmelillo76** [comment]
> > We may consider using absolute values only if all values are negative, but only in that specific case
> 
> Think that could lead to confusion. The current behaviour seems clear to me.

I agree now after giving it more thought.  Thank you both.

**Comment by gabriele-v** [comment]
@rmelillo76 I've sent a PR to fix decimal values, you should be able to test it soon.

**Comment by gabriele-v** [comment]
FYI looks like pie graph considers only the absolute value, so if I have a 20 and -20, the pie will be 50%-50%.
Obviously it doesn't make sense to create a pie with positive and negative values, but that's how it behaves.

**Comment by whalley** [comment]
> FYI looks like pie graph considers only the absolute value, so if I have a 20 and -20, the pie will be 50%-50%. Obviously it doesn't make sense to create a pie with positive and negative values, but that's how it behaves.

Yes, not sure what else you can do in this situation. A Pie chart is probably not the best display option, but that is up to the user to select.

**Comment by n-stein** [comment]
There's an old C-style cast on this line that is causing the Flatpak build to fail. It should be a static_cast.

https://github.com/moneymanagerex/moneymanagerex/blob/master/src%2Freports%2Ftransactions.cpp#L189

**Comment by gabriele-v** [comment]
Thank you @whalley
