### ISSUE TITLE
Titlebar display order: 1. database filename; 2. localized program name. `Recent Files` menu: 3. Add database directory

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#5709]
Please move the application name, underlined in red in the image below, to the end of string in the titlebar.

![MMEX Money Manager](https://user-images.githubusercontent.com/17465872/221378883-c279efe1-4f47-4b2b-8a4f-a90adc74141e.png)

For consistency with conventions used in other programs, such as:
1. [GNU Image Manipulation Program (GIMP)](https://www.gimp.org/)
![GIMP](https://user-images.githubusercontent.com/17465872/221378900-386bc751-8324-4d40-b445-333374ca4bb0.png)
2. [Betterbird](https://betterbird.eu/) a soft fork of [Mozilla Thunderbird](https://www.thunderbird.net/)
![Betterbird](https://user-images.githubusercontent.com/17465872/221378906-00a75dff-4874-49bd-b3aa-02821acb12da.png)
3. [LibreOffice](https://www.libreoffice.org/)
![LibreOffice Writer](https://user-images.githubusercontent.com/17465872/221378914-51dfb4c6-3099-42b0-a038-678c707b2d8a.png)
4. [Mozilla Firefox](https://www.mozilla.org/firefox/)
![Mozilla Firefox](https://user-images.githubusercontent.com/17465872/221378934-af1bb132-34c9-467a-a88b-6fdd7f21593e.png)

What do you think?

Thank you

**Comment by ovari** [comment]
Looking at the image from GitHub:
`Issues · moneymanagerex/moneymanagerex · GitHub - Mozilla Firefox`

Should the order be:
1. Database filename (underlined in blue)
2. Database directory (underlined in green)
3. Program name (underlined in red)

![image](https://user-images.githubusercontent.com/17465872/221379469-e65bd88a-b27b-42a0-ae26-7e962b647039.png)

Should MMEX write:
`test1.mmb - /home/ /Desktop/appdata/mmex - Money Manager Ex`

What do you think?

Thank you

**Comment by gabriele-v** [comment]
IMHO we should remove the full path, Windows (Excel, Paint) behaves as your examples, so it should be "test1.mmb - Money Manager Ex"

**Comment by tactilis** [comment]
Answering from a Windows perspective - but I assume similar considerations apply to Mac & Linux...

> What do you think?

I support a changing the title bar to:

`filename.mmb - Money Manager Ex`

This is consistent with many applications, including the ones @ovari has shown, plus for example:

![image](https://user-images.githubusercontent.com/4060092/221401896-4524cad1-2768-4ee3-a875-3bddbf73f44b.png)


The main reason for displaying the filename first is that it allows you to see what file is open when you hover the mouse over the taskbar icon. Comparing Word and MMEX, it's clear that the MMEX title is not very helpful:

![image](https://user-images.githubusercontent.com/4060092/221401636-d6d46502-f776-4dd0-9969-200cba10eef6.png)

<br>

It's even less helpful if you have multiple databases open, which I often do while testing MMEX, because you cannot tell which instance is which database:

![image](https://user-images.githubusercontent.com/4060092/221402579-ab1123ad-45be-4dea-9f8f-696feac8bd7e.png)

<br>

I do not support showing the directory path in the title bar in the manner @ovari  has suggested. It results in a 

The majority of MMEX users will have only a single database covering all their personal finances. They know where the file is located, so there's no need to show the directory path.

**Comment by ovari** [comment]
1. GIMP and GitHub have more than the other programs that were given as examples; however, if the directory is going to be removed from the title bar, can the directory then please be shown in the `Recent Files` menu?

![image](https://user-images.githubusercontent.com/17465872/221405319-becaf524-d98f-412c-980a-92ea9996a203.png)

2. Can the program name which is shown be the name that is displayed in the menu as it provides a better user experience.

![image](https://user-images.githubusercontent.com/17465872/221405545-50485276-8045-4ef5-ba46-fe91dcdaa052.png)

What do you think?

Thank you

**Comment by tactilis** [comment]
@ovari
>  if the directory is going to be removed from the title bar, can the directory then please be shown in the Recent Files menu?

I'm not sure I understand your logic here. What has addition of directory path to the Recent Files menu got to do with removal from the title bar? They are unrelated issues.

In any event, that menu _does_ show full paths:

![image](https://user-images.githubusercontent.com/4060092/221409383-16c8b8f6-de7c-482e-9746-c76209adf97a.png)

<br>

It shows full paths for any Recent database that is **_not_** in the same directory as the currently open database.

So for example, starting with the above, I opened one more database (_Test asset summary crash.mmb_) in my usual MMEX directory and _then_ opened a database that is on my Desktop. The Recent menu now shows:

![image](https://user-images.githubusercontent.com/4060092/221410041-f2d2eb5e-4d24-4b0c-bbd5-1d6da58a583e.png)

**Comment by ovari** [comment]
There are 2 spaces `  ` before ` [portable mode]`?

Should
`title = wxString::Format("%s - %s", title, (" [" + _("portable mode") + ']'));`
become
`title = wxString::Format("%s - %s", title, ("[" + _("portable mode") + ']'));`
?

Now that `MMEX` is at the end, should the `-` be removed between `MMEX` and `[portable mode]`?

Should
`title = wxString::Format("%s - %s", title, (" [" + _("portable mode") + ']'));`
become
`title = wxString::Format("%s %s", title, ("[" + _("portable mode") + ']'));`

https://github.com/whalley/moneymanagerex/commit/d741384f7717573db427980f553d8fb8144066f3#diff-80474aefffdd5e70886979cef3d8e5cf6d4c5129ed74ae6db1e117c11fa6ded4R2093

Thank you

**Comment by ovari** [comment]
Should the `- ` be removed from the titlebar in the following windows?

![image](https://user-images.githubusercontent.com/17465872/221808105-f3d1b4cb-6403-44fa-8d2d-9258d592c1e8.png)

![image](https://user-images.githubusercontent.com/17465872/221808131-d7e4f804-023f-4c28-87f1-12e532a6a854.png)

What do you think?

Thank you

**Comment by rmelillo76** [comment]
The version info in the title bar is now truncated due to the overall dialog's width being reduced. This is primarily caused by "Show this window next time Money Manager Ex starts" being refactored.

![image](https://user-images.githubusercontent.com/95182117/222020799-41f940fd-833e-477d-808e-ddeea8fb35fd.png)

**Comment by ovari** [comment]
Has the width been fixed or does it just work on GNU/Linux?

![image](https://user-images.githubusercontent.com/17465872/222085994-1445c459-d735-487c-a5d8-709b30c2e4dc.png)

Thank you

**Comment by n-stein** [comment]
Still super skinny on Windows. I'll look at it tomorrow unless someone else beats me to it.

**Comment by n-stein** [comment]
I adjusted the dialog size to keep the same margin on the buttons as before the change.
![image](https://user-images.githubusercontent.com/16599929/222572337-387c32af-cf17-4002-be79-930a0788dbab.png)
