### ISSUE TITLE
Deleted data

### ISSUE THREAD

**Issue by riseandshine2050** [moneymanagerex/moneymanagerex#5719]
Hi I use money manger software for financial transcations today when i was use by mistake all my imporatant data delete ho wi can recover that data please guide me

**Comment by tactilis** [comment]
@riseandshine2050 Sorry to hear about your accidental deletion of data of data.

Firstly in the folder where you keep your MMEX database (that's the .mmb file), do you have any .bak (backup) files with the same database name? If so, please _**copy**_ them to a new folder so that you don't accidentally delete them or overwrite them.

So we can assist you, please would you answer these questions:

1.  Can you say what mistake you made? Did you simply select all the transactions and delete them? Or did something else happen?

2. Which version of MMEX are you using? You can find the version from `Help | About`

3. In `Tools | Options`, what do you have set in the Database Options:

![image](https://user-images.githubusercontent.com/4060092/221888682-d66bfd38-d098-466e-9925-7bbcc3fcdff3.png)

**Comment by riseandshine2050** [comment]
something else happen SUDDENLY i did not know how i just change one account to another account
![image](https://user-images.githubusercontent.com/126583755/222945983-24d90b7d-449e-4d1c-812e-0de2ea9fefcf.png)

**Comment by tactilis** [comment]
@riseandshine2050:
> by mistake all my imporatant data delete
> ...
> something else happen SUDDENLY i did not know how i just change one account to another account

It is not clear to me what you mean by _"I just changed one account to another account"_

Some possibilities:

1. Have you opened the wrong .mmb database file?

2. Have you deleted an account?

3. Have you renamed an account to a different name?

4. Did you have a Closed account, which you have accidentally hidden by changing the Accounts Visible to show only Open accounts?

![image](https://user-images.githubusercontent.com/4060092/222956276-8c2a90f8-e1ec-42b7-8f86-2fbafc4230c2.png)


<br>

We can't help you unless you explain _exactly_ what is wrong.

Please provide answers to the **three** questions in https://github.com/moneymanagerex/moneymanagerex/issues/5719#issuecomment-1448345473 and confirm that you have preserved your database backup files as I suggested.

I see from your screenshot that you are using a fairly old version of MMEX. You should update to the latest version (1.6.3) - *but not until we have solved your missing data problem*.
