### ISSUE TITLE
Imported csv negative char not recognized as minus

### ISSUE THREAD

**Issue by boondoggle28** [moneymanagerex/moneymanagerex#5801]
I converted an excel file to scv through google drive and MM doesn't seem to recognize this "−" character as minus. What gives?

**Comment by tactilis** [comment]
> MM doesn't seem to recognize this "−" character as minus.

The character you have posted above is not a minus, it's an 'En dash'

![image](https://user-images.githubusercontent.com/4060092/230649797-b026453d-e9f1-4e39-be67-c55b4aed4b39.png)


"-"   Minus
"−"  Your character


Please could you upload your Excel file here (just a couple of rows containing the negative values will do). 

Note that you don't need to use Google Drive (or anything else) to produce a .csv file from Excel. Just save it from Excel and set the `Save as type` to CSV.

**Comment by boondoggle28** [comment]
I did suspect it was not the "right" character but my bank exports it like this and i don't have excel and that's why I need to convert it to CSV using google.
[test.csv](https://github.com/moneymanagerex/moneymanagerex/files/11180586/test.csv)
[test.xlsx](https://github.com/moneymanagerex/moneymanagerex/files/11180587/test.xlsx)

**Comment by tactilis** [comment]
Here are the rows from your .xlsx on top and the .csv below:

![image](https://user-images.githubusercontent.com/4060092/230666158-2b7bf7c0-3709-4d5f-b1d2-a338f59487e6.png)


Your .xlsx is OK. The "-" character _is_ a minus and MMEX can import values containing a comma as the 1000s separator.
You don't need to import the Balance column because MMEX calculates that from the transactions.

The .csv is not OK.
The 'minus' character isn't a minus.
The values have been reformatted to have comma as the decimal point (but MMEX can handle that).
However, although it now looks like it is reformatted as a space, the 1000s separator is actually a 'non-breaking space' character as you can see below:

![image](https://user-images.githubusercontent.com/4060092/230666446-62840427-4694-4d50-85d7-ebcff311d77e.png)

When you say you are using Google Drive to reformat the file, do you mean Google Sheets? How are you actually doing it?

And does your bank not provide a means of exporting as CSV?  Most do.

**Comment by tactilis** [comment]
I've just tried importing your .xlsx into Google Sheets then downloading the file as .csv
I get the same results as you. CSV export in Google Sheets is broken.

However, this online convertor works OK:  https://cloudconvert.com/xlsx-to-csv

Here's the converted .csv from Cloud Convert:

![image](https://user-images.githubusercontent.com/4060092/230679130-e5534194-6478-4537-9b20-da6b6a2a4397.png)

And here is the MMEX Import dialog with the file loaded:

![image](https://user-images.githubusercontent.com/4060092/230679424-6d0ec814-d2f9-4dcb-9f03-5fb97e716547.png)

Note that this version of the dialog is from MMEX version 1.6.4 Beta 4, which is not yet released.

The .csv also imports OK with MMEX version 1.6.3 but the layout of the fields will be different to that shown above.

**Comment by boondoggle28** [comment]
Thank you but yeah my banks are broken as well ;). To not add balance column i had to input the start value but that would be less automated. Regarding minus sign I simply replaced the character in the csv file with minus. I was thinking there maybe could be an option like "character in front of value means minus"? Right now i am struggling to find an easy way to group "payees". For example my bank adds dates to all the Spotify transactions. How to group them? I know that's another topic but since i couldn't find good info on that maybe i could get a heads up here?

**Comment by vomikan** [comment]
> maybe could be an option like "character in front of value means minus"?

I like it

**Comment by n-stein** [comment]
> Right now i am struggling to find an easy way to group \"payees\". For example my bank adds dates to all the Spotify transactions. How to group them?

1.6.4 adds the ability to pattern match a payee on import. You can edit your Spotify payee and add a match pattern like '*Spotify*', then on import select 'Pattern match payees' and it will automatically rename something like 'Purchase Spotify 2023-04-06' to 'Spotify'.

**Comment by tactilis** [comment]
@boondoggle28 
> To not add balance column i had to input the start value but that would be less automated.

MMEX calculates the balance starting with the Initial Balance for the account, then adds each deposit and subtracts each withdrawal.

You only enter the Initial Balance (i.e. the start value) once. You never have to do it again.

Right click on the account and select `Edit Account`:

![image](https://user-images.githubusercontent.com/4060092/230738702-eca68dd0-8a6a-4df0-b815-41bd7456d5d3.png)

**Comment by tactilis** [comment]
@boondoggle28 
> Thank you but yeah my banks are broken as well ;).

Please could show us an .xlsx file produced by your bank.

The test.xlsx you posted had the correct minus sign.
The .csv didn't because Google Sheets can't write CSV properly.

What is broken about your bank .xlsx please?

To my knowledge, **nobody** else has ever reported a bank that outputs the wrong minus character and, until we know for certain that your bank is actually doing this and it is  real problem, we should not start adding workarounds in MMEX.

**Comment by boondoggle28** [comment]
Oh sorry I was only jokingly ranting my bank. It was googles fault, this time. I don't think need to put an effort on this, just thought it was an easy enough to add an option but I understand it can clutter the gui. I also understand the initial balance is a one timer, however it can not beat not doing it at all. I´ll try the 1.6.4. Keep the good work up i really like what your doing and thank you quick and good help!

**Comment by tactilis** [comment]
Could you close the issue now please @boondoggle28
