### ISSUE TITLE
View Trans window for Stock transaction - make it larger/resizable please.

### ISSUE THREAD

**Issue by siowena** [moneymanagerex/moneymanagerex#5823]
# Description of the feature

The current window that displays stock transactions is small and not resizable. This give a confusing view when there have been a lot of transactions on a stock over time.

The window could be made wider and/or resizable so the fields on each transactions do not wrap and the data columns align with the headings.

# Use cases

Obviously if I want to see all transaction details I can (View menu->Navigation; scroll to/select the portfolio; select the stock in the navigation window and see all transactions.

Sometimes I just want to have a quick easy view to check some details without the full number of steps to see the stock account view. The popup window is ideal, but needs a little tidy-up.

<img width="269" alt="Screen Shot 2023-04-11 at 16 17 17" src="https://user-images.githubusercontent.com/44472390/231159999-e0d4f17e-41b4-4fc6-b1bf-8a62a8e20624.png">

**Comment by n-stein** [comment]
We can replace the text-based message box with something a bit more robust. How about this?

Old:
![image](https://user-images.githubusercontent.com/16599929/232092190-8641aa38-7fad-4b19-aa40-106754c9391a.png)

New:
![image](https://user-images.githubusercontent.com/16599929/232098087-0c497b8d-053d-459b-adaf-b5212a721b87.png)

**Comment by tactilis** [comment]
Is that just a mock-up?

Would you be able to right justify the values so that the decimal points line up?

**Comment by n-stein** [comment]
Not a mock-up, you can test it out in AppVeyor build [517](https://ci.appveyor.com/project/whalley/moneymanagerex/builds/46789244).

With Shares, Price, and Commission right-justified (Date and Lot still left-justified):

![image](https://user-images.githubusercontent.com/16599929/232104565-f4e65b6f-04a9-4cfe-bc1b-46fc916fd61f.png)

**Comment by n-stein** [comment]
Also updated to center the dialog.

**Comment by n-stein** [comment]
The first one is the current dialog, I didn't make any edits. That's how it appears on Windows, so it seems the text wrapping is a macOS issue. The new grid-style layout should work on both.

**Comment by n-stein** [comment]
Now enabled Ctrl+A and Ctrl+C to allow users to copy items from list to clipboard.

**Comment by russell-mcdaniel** [comment]
Just for bookkeeping purposes, is this the same or similar to #1752?

**Comment by n-stein** [comment]
> is this the same or similar to #1752?

Good find. Its similar, I would say it gets us about half way there. That issue calls for
>implementing a standard transaction panel with all editing, sorting, filtering capabilities.

This implements the transaction panel (i.e. grid) layout, but doesn't provide any editing, sorting, or filtering. We can add those capabilities under #1752.

**Comment by siowena** [comment]
My original request was to just unwrap the text lines on the tx panel. I didn't realize it was already like that on Windows and the wrapped text was a mac issue.
The grid works for me.
Are we making this complicated to have full editing (1752), why not just provide a right-click menu item to the share accounts where all the tx are stored (I'm not sure what happens with tx where there is no corresponding share account).
To edit/add actions on the shares (e.g. receipt of dividends/interest/charges/fees) that are specific to the stock I have to open Navigation panel (via View menu - I'm on a mac so mouse clicks) and then scroll to the Stock Portfolios and click the stock giving me the full share accounts. I can also see the Tx and click on them and get the stock entry screen.
Have two places to edit transactions - won't that increase maintenance and coding complexity and possibly cause higher effort in support?

**Comment by n-stein** [comment]
You make a good point about maintenance and complexity increases. 

However, I would argue that being able to edit transactions from this dialog would be useful because this is the only place in MMEX where we can see the shares and price of each transaction. The checking panel view of the share account only shows you the total amount of the transaction. 

If you are reconciling your stock transactions in the "View Stock Transactions" dialog and you notice that the number of shares for one of the transactions is wrong, you would have to:
1. Note the date of the transaction
2. Close the View Stock Transactions dialog
3. Open the share account for the stock you just viewed
4. Find all stock transactions for the date noted in step 1 (there may be more than one)
5. Determine which transaction has the incorrect share number & price. This may involve opening multiple transactions to find the correct one to edit.

Alternatively if we enable editing you could
1. Double-click on the offending line to open the share transaction dialog
2. Correct the share number and save. 

I think it improves the flow for the user without too much extra effort.

**Comment by siowena** [comment]
You have a good point about work flow.

My other suggestion was going to be to have additional columns to the share account view, but I'm assuming that would be a completely new list screen than just using the normal account list view. I didn't suggest again due to complexity/maintenance.

I'll let this thread complete as it's now fixed and look forward to the next release. Once released, I'll close this thread and other work can be done under #1752
