### ISSUE TITLE
Report Operations

### ISSUE THREAD

**Issue by MAPA2023** [moneymanagerex/moneymanagerex#5876]
MMEX version:
 - [ X ] 1.6.3 
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
The report of an account (ex cash) DOES NOT INCLUDE the initial balance set on the account. See attachments.

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

![stampa cassa](https://user-images.githubusercontent.com/128650264/235311748-2a2f9c3f-01e1-4765-a2e8-10bb5dbd758d.JPG)
![Cattura](https://user-images.githubusercontent.com/128650264/235311754-a7d5026d-47d0-49aa-8ab3-b94e3b67b503.JPG)
![REG](https://user-images.githubusercontent.com/128650264/235311755-bc390300-2d7c-4fa6-845b-4a6fd397a6b9.JPG)
![CASSA](https://user-images.githubusercontent.com/128650264/235311757-fc437191-7db7-4fcc-9597-79dfdc00de04.JPG)

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by tactilis** [comment]
This not a bug. MMEX is working as expected.

The report shows transactions. You have only one transaction of 50.00 on 29/04/2023.

Your account has an initial balance in MMEX of 100.00. This is not a transaction. MMEX has no knowledge of how that 100.00 arrived in the account.

If you want to show a transaction for an deposit of 100.00 into the account on 01/01/2023 then you need to set the initial balance of the account to 0.00 and create a transaction of 100.00 for that date because that models what actually happened in the real world.

**Comment by MAPA2023** [comment]
Oky many thanks Tactilis. What is the initial balance for?

**Comment by MAPA2023** [comment]
From my point of view, given that the "Initial Balance" field creates a correct balance in the transactions, so should the printing of that account without having to put an initial registration. It could be solved as in the figure for example. Where, if there is a value, it is reported otherwise, no.
![stampa cassa](https://user-images.githubusercontent.com/128650264/235363966-cd817d3c-d91a-4b55-a57d-b48d99fb6fff.JPG)

**Comment by MAPA2023** [comment]
Hi Martin,

a constructive idea could be to add the item "Initial balance" as shown in the figure and therefore also have the correct balance in that printout.

Max
________________________________
Da: Martin ***@***.***>
Inviato: sabato 29 aprile 2023 18:07
A: moneymanagerex/moneymanagerex ***@***.***>
Cc: MAPA2023 ***@***.***>; Author ***@***.***>
Oggetto: Re: [moneymanagerex/moneymanagerex] Report Operations (Issue #5876)


This not a bug. MMEX is working as expected.

The report shows transactions. You have only one transaction of 50.00 on 29/04/2023.

Your account has an initial balance in MMEX of 100.00. This is not a transaction. MMEX has no knowledge of how that 100.00 arrived in the account.

If you want to show a transaction for an deposit of 100.00 into the account on 01/01/2023 then you need to set the initial balance of the account to 0.00 and create a transaction of 100.00 for that date because that models what actually happened in the real world.

**Comment by MAPA2023** [comment]
Hi All, 

or a better idea could be this: always calculate the starting and ending balance according to the selected period based on the report. This option may also cause this printout to be an account statement. See the picture example
![Statement mod](https://user-images.githubusercontent.com/128650264/235365854-6ab37a55-879f-4c68-a921-646de4e16343.jpg)

**Comment by tactilis** [comment]
@MAPA2023
> What is the initial balance for?

Consider this scenario, which is very common:

- I opened a real world bank account 10 years ago.
- Over the years there have been thousands of transactions.
- On 1st January this year, I discover the wisdom of using personal accounting software and decide to install MMEX.
- I set up an account in MMEX to model my real world bank account.

Clearly I don't want to enter 10 years worth of transactions into MMEX, so I note the bank account balance at the start of 1st January and enter that figure into MMEX as the Initial Balance.

Note that I should _not_ create a deposit transaction for the initial balance figure because that will appear incorrectly as income. This isn't income; it's just a snapshot of the balance of my real world account at the date that I begin modelling it in MMEX.

In your case, I suggested at https://github.com/moneymanagerex/moneymanagerex/issues/5876#issuecomment-1528820266 that you set your account initial balance to 0.00 because, I assume, the 100.00 really was a deposit; perhaps the amount you paid into the account when you first opened it.

**Comment by tactilis** [comment]
@MAPA2023
> or a better idea could be this: always calculate the starting and ending balance according to the selected period based on the report. This option may also cause this printout to be an account statement. See the picture example

Showing a starting and ending balance would _only_ make sense in the limited case that the Transaction Filter was set to show data for just one account with no filtering of Payees, Categories, Transaction Type, etc.

If the report covers multiple accounts or filters the transactions, then the starting and ending balance would be meaningless.

**Comment by MAPA2023** [comment]
Hi Martin,

You are right ! I get the concept.

Which print do you recommend for having a statement with the balance.

For example, I think this is correct, right?


________________________________
Da: Martin ***@***.***>
Inviato: domenica 30 aprile 2023 20:50
A: moneymanagerex/moneymanagerex ***@***.***>
Cc: MAPA2023 ***@***.***>; Mention ***@***.***>
Oggetto: Re: [moneymanagerex/moneymanagerex] Report Operations (Issue #5876)


@MAPA2023<https://github.com/MAPA2023>

or a better idea could be this: always calculate the starting and ending balance according to the selected period based on the report. This option may also cause this printout to be an account statement. See the picture example

Showing a starting and ending balance would only make sense in the limited case that the Transaction Filter was set to show data for just one account with no filtering of Payees, Categories, Transaction Type, etc.

If the report covers multiple accounts or filters the transactions, then the starting and ending balance would be meaningless.

**Comment by tactilis** [comment]
> For example, I think this is correct, right?

If you reply by email, then any images you attach are not displayed here.

Please reply directly on github, as you did in your earlier posts, so that you can paste images.

Thanks

**Comment by MAPA2023** [comment]
![print](https://user-images.githubusercontent.com/128650264/235377771-b1cda2e3-8f6e-49dc-871c-c0b5a9f847eb.JPG)

**Comment by MAPA2023** [comment]
I am only making this last consideration: it might be interesting to have a printout of the account statement of a single account in order to see the movements of a period "printed" with the initial and final balance highlighted.

**Comment by vomikan** [comment]
> I am only making this last consideration: it might be interesting to have a printout of the account statement of a single account in order to see the movements of a period "printed" with the initial and final balance highlighted.

This can be done through GRM. It requires special skills, but you will get such a report in one click.

https://github.com/moneymanagerex/general-reports/tree/master/packages/Account/AccountBalances

**Comment by whalley** [comment]
Closing.
