### ISSUE TITLE
share update error

### ISSUE THREAD

**Issue by Heny67** [moneymanagerex/moneymanagerex#5890]
MMEX version:
 - [ ] 1.6.0
 - [ ] 1.6.1
 - [ ] 1.6.2
 - [x ] 1.6.3 
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

Shares cannot be updated due to an error.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information
Money Manager Ex
• Verzió: 1.6.3 64 bites
• Készítési időpont: jan. 31 2023, 03:26:11
• Adatbázis verziója: 17 (aes128cbc)
MMEX a következő támogatási termékeket használja:
• wxWidgets 3.1.7 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.6
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.14
• gettext 0.21
• apexcharts.js
Összeállítás a következőkkel:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.2.0
Fut a következőn:
• Ubuntu.22.04.jammy
• Ubuntu 22.04.2 LTS "jammy"
• Linux 5.19.0-41-generic x86_64
• (UTF-8)
• 0x0 0bit 96x96ppi
If you have a backtrace for a crash or a warning, paste it here.
![Névtelen](https://user-images.githubusercontent.com/80578702/236532037-cd88c3e0-744a-405d-8fb9-f65d1f915e00.png)

**Comment by renato-mmex** [comment]
t seems to be a general problem with updating the courses.
in any case, my courses are no longer updated since 3.5.2023.
There are other error messages in the forum:
https://forum.moneymanagerex.org/viewtopic.php?t=10842
https://forum.moneymanagerex.org/viewtopic.php?t=10837

**Comment by n-stein** [comment]
The Yahoo Finance v7 API is down right now, though v6 is still working. This happened a few weeks ago and was resolved within a few hours by Yahoo. See #5855.

**Comment by reddyshyam** [comment]
> The Yahoo Finance v7 API seems to be down right now, though v6 is still working. This happened a few weeks ago and was resolved within a few hours by Yahoo. See #5855.
> 
> Note that pulling quotes for a single symbol works ("Edit Stock Investment" then "Download Stock Price History") since it uses the v8 API.

Sorry @n-stein. Didn't understand what you are saying? Are you asking us to wait until Yahoo resolves it again (Just in in case of  https://github.com/moneymanagerex/moneymanagerex/issues/5855.) or the api used will be updated within app?

**Comment by renato-mmex** [comment]
I have done the update by hand.
<img width="485" alt="image" src="https://user-images.githubusercontent.com/76920138/236640958-2b99096c-cd7a-4034-9288-bbc6115e7c93.png">

**Comment by reddyshyam** [comment]
> I have done the update by hand. <img alt="image" width="485" src="https://user-images.githubusercontent.com/76920138/236640958-2b99096c-cd7a-4034-9288-bbc6115e7c93.png">

Thanks @renato-mmex. I have done this too following @n-stein's advise but even after this main stocks page isn't updated with the latest price which is more important to me to see the actual gain/loss of the stock.

Hope I made my case scenario clear.

**Comment by n-stein** [comment]
> even after this main stocks page isn't updated with the latest price

So the new price is downloaded but the stock panel isn't automatically updated to reflect the latest price?

**Comment by reddyshyam** [comment]
> > even after this main stocks page isn't updated with the latest price
> 
> So the new price is downloaded but the stock panel isn't automatically updated to reflect the latest price?

Hi @n-stein,

yes, that is correct.

**Comment by n-stein** [comment]
I'm not seeing this. When I update the rates via the "Download Stock Price History" the values are all updated automatically.

https://user-images.githubusercontent.com/16599929/236726820-0be8dc07-0524-4599-8615-121b5089d068.mp4

**Comment by reddyshyam** [comment]
> I'm not seeing this. When I update the rates via the "Download Stock Price History" the values are all updated automatically.
> 
>  mmex_xAxo7xiecE.mp4

Hi @n-stein,

Thanks for looking deep into this. Sorry, the functionality on app looks ok but looks like the update on history api is broken too. Even though it is not throwing error on history, the value isn't changing.

<img width="208" alt="image" src="https://user-images.githubusercontent.com/12392746/236729957-95016a62-1030-4d84-b004-d7ec30c5987a.png">

**Comment by Astermast3r** [comment]
Manual stock updates, such as the 5-day example above, should automatically update the last price reported as the "current stock price", but that doesn't happen...

**Comment by Heny67** [comment]
HI All!
When I update manually, some stocks are updated, but some are not.

**Comment by n-stein** [comment]
> Manual stock updates, such as the 5-day example above, should automatically update the last price reported as the "current value" (current stock price), but that doesn't happen...

@Astermast3r This sounds like a bug, but I'm not sure to which field you are referring. Can you share a screenshot showing the value which hasn't been updated properly?

These all seem to be updated properly:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/f316d947-c528-40fd-9db5-a95ad172ca4a)


![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/0d1d63ec-c14c-44b1-83a3-a8a4fac5ba59)

**Comment by n-stein** [comment]
> When I update manually, some stocks are updated, but some are not.

I think this could be due to the UK bank holiday on Monday May 8th. The LSE was not trading that day.

**Comment by Astermast3r** [comment]
In my experience, the manual update does not update the "Current Value" and "Curr. Share Price" items, which you have highlighted in yellow, I just now tried the ENEL.MI stock which has not updated since day 05 /05/2023. The above values have not changed since the update to May 9, 2023, even if the history is updated regularly.
![before](https://github.com/moneymanagerex/moneymanagerex/assets/125190132/b59a68b8-0b0d-4092-9d8f-f8ad222117cd)
![5days](https://github.com/moneymanagerex/moneymanagerex/assets/125190132/592fd2bd-fe32-40e9-857b-4991f176a5cb)
![after](https://github.com/moneymanagerex/moneymanagerex/assets/125190132/352d1804-fbe4-464d-a5e9-f179fb6cbc1c)

**Comment by vomikan** [comment]
Does it really work, maybe some nuances?

![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/126930bd-0314-464b-bf34-39ffbc121e4a)

**Comment by vomikan** [comment]
The commission is not taken into account at all.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/0d65228e-05ef-428e-9719-27e4b3e83557)

**Comment by n-stein** [comment]
> The commission is not taken into account at all.

Commission isn't part of current value -- you wouldn't get it back if you sold your shares right now. It's only counted in total cost to calculate gains/losses.

**Comment by Astermast3r** [comment]
I have found the mystery! the nuance is that you have to click the "Add" button at least a couple of times, if you press it once it doesn't update the current price, Ok, solved, thanks n-stein for your support.

**Comment by siowena** [comment]
I'm having this issue after moving countries. I've not had this problem before when visiting during holidays, but now I've moved the only difference is update my MAC O/S settings from UAE -> UK.

The toolbar button doesn't update the share prices on the stock history or stock values. Accessing individual stocks and using the "Download Stock Price History" does download the history except for the current date. 
It also does not update the current share price and values fields. Maybe this is because it's not pulling the current date?
Manually adding the current date does update the current share price and values fields.
If I use today on FAS.L I get 10th May but not the 11th May.  Before the move of country, it would always pull including the current date.
Yahoo site: http://finance.yahoo.com/echarts?s=FAS.L

<img width="1280" alt="Screenshot 2023-05-11 at 13 22 46" src="https://github.com/moneymanagerex/moneymanagerex/assets/44472390/56d07e71-a83b-4e3c-9f6b-d055646a6d0f">


MMX updated:

<img width="688" alt="Screenshot 2023-05-11 at 13 26 49" src="https://github.com/moneymanagerex/moneymanagerex/assets/44472390/1a5ef112-2c16-4f4f-970c-a42aa7c41b90">

**Comment by n-stein** [comment]
History download in the "Edit Stock Investment" dialog has skipped "Today" since 7 Feb 2020 (commit cf3d5bc7cb12ec0ca1ac4fd1b088f6ff1f49fb1f)

https://github.com/moneymanagerex/moneymanagerex/blob/770771661e57908032699d2501163ea0f49a887d/src/stockdialog.cpp#L829-L831

So far I have been unable to replicate the issue where the current share price and current value are not automatically updated to match the latest stock price. If you check out the clip I posted above, you can see those fields auto-update when I download the history. Are you doing something differently?

**Comment by Galdor83** [comment]
@n-stein from the 10th of May if I update the price of a share, as you did, I obtain always the same price, and it's wrong, very different from what is visible from every site, yahoo included, and this happen for all the share I own (VWCE.MI, VNGA80.MI, ...).

**Comment by n-stein** [comment]
Yahoo Finance seems to think the close price hasn't changed since March 24th:

https://finance.yahoo.com/quote/VWCE.MI/history?p=VWCE.MI

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/dd63e0be-d69b-486d-9006-a3f90e36df9b)

**Comment by siowena** [comment]
@n-stein Apologies for the late response. I've recorded updating my Amazon stock, as you can see there are two issues
- Date is 16th (approx 10:45pm) but the 16th prices does not download.
- Also once I use the Stock update - it downloads the history, but not the 16th. It doesn't update the stock price and total stock value until I hit Add twice.
- Note: none of these issues I experienced at Dec2022-Feb2023 when I visited UK on holiday (but they may have been 1.6.2) nor when I returned to UAE in the interim. I've now changed mac settings to UK region as I now back UK full-time and then I noticed these issues in update of stock-prices.

1st files shows the 16th missing, but also it's added the 15th but not updated the stock price/value fields.

https://github.com/moneymanagerex/moneymanagerex/assets/44472390/7d267077-1886-4960-9e78-6aa7b1b083c0

2nd file shows the stock price/value updating once I hit add button twice.

https://github.com/moneymanagerex/moneymanagerex/assets/44472390/e07f99e0-6c9a-425d-9387-9ef317cab280

**Comment by n-stein** [comment]
> Date is 16th (approx 10:45pm) but the 16th prices does not download.

I mentioned this up thread, but history download in the stock dialog always skips "Today" and has for the past two years. The refresh button on the panel or via Get Rates does pull the current price.

> It doesn't update the stock price and total stock value until I hit Add twice.

Hmm, this is different from what happens on my system. I see your date setting is different, could be related. Let me look into it a bit more.

**Comment by siowena** [comment]
The refresh button on the panel is giving the Invalid Cookie error others are experiencing.

The Tools -> Download Rates doesn't on mine download the 17th May (it's 13:01) and only to the 16th even though the 17th is available on the Yahoo site.

To try and understand why it may be different to yours, I've created an new empty DB with GBP as the base, added one Investment BARC.L updated the history in a variety of ways, but it is behaving as per my other DB.

<img width="912" alt="Screenshot 2023-05-17 at 13 04 45" src="https://github.com/moneymanagerex/moneymanagerex/assets/44472390/e96f4644-4508-4da2-a5fe-ca62081d17cd">

**Comment by n-stein** [comment]
> The Tools -> Download Rates doesn't on mine download the 17th May (it's 13:01) and only to the 16th even though the 17th is available on the Yahoo site.

This is expected. Tools -> Download Rates uses the same v7 API that the button on the stocks panel does (the one throwing the "Invalid Cookie" error, this one just doesn't display the error dialog), so it won't work if you are using any version other than 1.6.4 Beta 5 built on/after 2023-05-08.

**Comment by n-stein** [comment]
> So far I have been unable to replicate the issue where the current share price and current value are not automatically updated to match the latest stock price. If you check out the clip I posted above, you can see those fields auto-update when I download the history.

Sorry everyone, I forgot I fixed this already in #5759 (commit 748ffa52647788fa8f41ce160b8dfb69d35319cb), that's why I can't replicate the issue.... There are so many fixes in 1.6.4 I lost track. My sincere apologies for wasting your time diagnosing an issue that was already remedied.

In that case I don't think there are any outstanding issues here. 

1. Current price download from Yahoo works after fixes in #5894
2. `Curr. Share Price` and `Current Value` on "Edit Stock Investment" dialog update properly due to fixes in #5759
3. Historical price download works the same as it always has
