### ISSUE TITLE
Possibility to associate a "Name" (Payee) to 2 "Assett accounts" type

### ISSUE THREAD

**Issue by MAPA2023** [moneymanagerex/moneymanagerex#5914]

**Comment by MAPA2023** [comment]
Another good way

![Transaction 2](https://github.com/moneymanagerex/moneymanagerex/assets/128650264/58f3d1a8-7f39-4636-836e-f996240d2e2c)

**Comment by MAPA2023** [comment]
ex
![Transaction 3](https://github.com/moneymanagerex/moneymanagerex/assets/128650264/45d0967d-a2a0-4353-bd5c-cd2f678578bc)

ex on other program
![238689622-28729ce2-1641-4098-9966-570cb7c8e33c](https://github.com/moneymanagerex/moneymanagerex/assets/128650264/da455285-5884-420e-93a1-382a9389f7d8)

**Comment by tactilis** [comment]
Note that there is more information about this feature request from @MAPA2023 in Discussion: https://github.com/moneymanagerex/moneymanagerex/discussions/5912, including the part of the proposal that was subsequently removed from the first post of _this_ issue (please don't keep editing earlier comments @MAPA2023 because it makes the issue harder for other people to follow).

I suggest that _this_ issue is closed and that discussion of the feature continue in https://github.com/moneymanagerex/moneymanagerex/discussions/5912

**Comment by MAPA2023** [comment]
GO TO 5912
