### ISSUE TITLE
Editing multiple transfer transactions

### ISSUE THREAD

**Issue by regs01** [moneymanagerex/moneymanagerex#5981]
When editing multiple transfer transactions you can edit transfer to, but not from. Payee is grayed out.
<img width="251" alt="mmex_2023-06-04_19-00-52" src="https://github.com/moneymanagerex/moneymanagerex/assets/10468217/e1004289-34fa-42ba-a4a1-9dbcc2814aee">

**Comment by tactilis** [comment]
> When editing multiple transfer transactions you can edit transfer to, but not from.

That is by design. You should be editing the Transfer transactions in the From account.

There was a long discussion about the rules for multi-editing Transfers in the original issue here https://github.com/moneymanagerex/moneymanagerex/issues/3897

<br>

 > Payee is grayed out.

That is by design. Transfer transactions do not have a Payee. They have a To account.
