### ISSUE TITLE
Possibility to associate a "Name" (Payee) related to 2 "Assett accounts" type - v. 1.6.5. requested #5912

### ISSUE THREAD

**Issue by MAPA2023** [moneymanagerex/moneymanagerex#5985]
# Description of the feature

I need the possibility to associate a "Payee" on tow "Asset Account" (Ex. Bank to Deposit). 

Add screenshots, design images or other files which would help for
understanding the feature or for implementation.

![Transaction 2](https://github.com/moneymanagerex/moneymanagerex/assets/128650264/ff8330a2-84fd-44ab-b819-c45594ef9c71)

# Use cases
A recurring example is the need to have an account in which to park money (both incoming and outgoing) for future services that have not yet been defined. Or the possibility of recording a revenue or cost on the correct date (e.g. a receipt or invoice) but being able to manage the payment later. Obviously all By associating the "Payee"

**Comment by tactilis** [comment]
@MAPA2023 Why have you created _another_ issue about this topic?

This is the 3rd issue that you have created about the same feature request in the space of 3 weeks; the other two being #5914 and #5912.

All three issues are currently Open.

The most extensive discussion is in #5912. Please could any further discussion take place there, otherwise information gets spread over multiple issues and is hard for anyone to follow.

Please could we close #5914 and _this_ issue #5985 and continue any discussion in #5912.

**Comment by MAPA2023** [comment]
CLOSE RELATED TO 5912
