### ISSUE TITLE
Column width on Payee field

### ISSUE THREAD

**Issue by nyc1199** [moneymanagerex/moneymanagerex#6029]
MMEX version:
 - [  ] 1.6.0
 - [ ] 1.6.1
 - [x] 1.6.2
 - [ ] 1.6.3 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
Yes
Expected result:
same
Actual result: not good

# Additional information
I am having an issue with the data imported from my bank .cvs
Your program column width needs to be longer because I am missing the last letters of the payee field.
How can I make the column width longer ?
Thank you

If you have a backtrace for a crash or a warning, paste it here.

**Comment by tactilis** [comment]
> Your program column width needs to be longer because I am missing the last letters of the payee field.

Do you mean that you cannot see the full payee name?

If so, you just need to resize the column width:

https://github.com/moneymanagerex/moneymanagerex/assets/4060092/8c8f405c-fff5-44e4-88db-342765bf6381

If that isn't the problem that you are having, then please could you explain in more detail.

**Comment by nyc1199** [comment]
Thank you for replying
I already tried your video
Below, This a transaction from a CVS file from my bank.
DEBIT,12/06/2021,"Online Payment 13171107135 To CONSOLIDATED EDISON 12/06"

This attachment is clip as shown in MoneyManager EX
You can see the name of the payee column chopping off the last 15 letter of the name of the payee ( NSOLIDATED EDISON)
See attachment.
![Screenshot 2023-06-18 074930](https://github.com/moneymanagerex/moneymanagerex/assets/71199929/a8cdff0c-bdae-4d21-91a4-7d9a6c977e27).

I am a newbie at this, trying to learn more.  Thank you

**Comment by tactilis** [comment]
I've added your text "Online Payment 1315 To CONSOLIDATED EDISON 12/06" to one of my test CSV files and have imported it successfully using MMEX 1.6.2, which is the version you have indicated that you are using.

Here's the Import dialog:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/51afe172-5555-4e10-b4f5-a0a06547fbcd)

And here's the transaction:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/94ea0c6a-8517-4dcb-9e00-834084aec3a2)

<br>
<br>

I have also imported the CSV file into MMEX 1.6.4 Beta 8. The official release of 1.6.4 should occur very soon now and will contain a new feature called "Payee matching" as part of the Import process.

The reason that this is significant is that your text "Online Payment 1315 To _**CONSOLIDATED EDISON**_ 12/06"
contains more than just a payee name. The payee is CONSOLIDATED EDISON as shown in bold. The rest of the text is extra information that will presumably be different each time you make a payment to that company.

With Payee matching, you can set up a pattern that will match characters in the CSV file to a specific Payee.

Here I have created a Payee called 'Consolidated Edison Power Co' and matched it with any text that contains:

"*\<any number of leading characters>*CONSOLIDATED EDISON*\<any number of trailing characters>*"

I've also defined a default Category of Bills:Electricity for that Payee that will be automatically applied during Import.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/908ad17e-09f1-4b20-8713-f271ef3a537a)

Here's the 1.6.4 Import dialog:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/224cde93-e4a5-478d-b672-d25cf7bc8f37)

Showing the Payee pattern match:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/e1203c58-d392-4554-8e78-0898747250bd)

And the imported transaction. Note the Payee name and the Category:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/8152fe3b-6d10-47df-b2b0-4e12a45dd9c4)

<br>
<br>

So MMEX works with long payee names and 1.6.4 will offer you additional capabilities, however, we are still left with the fact that the payee name was truncated when you did the Import.

I suspect that there is a problem in your CSV file.

Would you be happy to email it to me at _martin (at) tactilis (dot) co (dot) uk_ and I will see what is wrong. I'll delete the file after examining it. I'll report the findings here.

**Comment by nyc1199** [comment]
I am trying to use WEB APP to download statement from bank.
I have the URL but I am missing the GUID .
I called the bank and they said they have any 
Also, The online statement to download are in PDF format, will

**Comment by tactilis** [comment]
@nyc1199
> I am trying to use WEB APP to download statement from bank.
> I have the URL but I am missing the GUID .
> I called the bank and they said they have any
> Also, The online statement to download are in PDF format, will

MMEX Web App does not download data from banks. Contacting the bank for help pointless.

What you have written above has nothing to do with the problem you reported in _this_ issue, which was to do with you finding that the Payee column was being truncated on import from a CSV file.

I demonstrated that MMEX _can_ handle long payee names, both in version 1.6.2 and in 1.6.4. I took the time to explain in detail how you could import your data. I offered to help by taking a look at your CSV file. You didn't bother replying.

Are you still having problems importing data from CSV files?

**Comment by nyc1199** [comment]
I am sorry, I am new to all this programing forum. I appreciate your help..
I was away from PC and didn't have the time to address this 

Yes I am having issues with my downloaded bank statements.
First - my bank can only download to a PDF file, so that why  I want to do a direct connect download with MMEX. with WEB APP
Second - The CVS file was converted somehow from a PDF file , I don't remember how because I am trying to get MMEX working with the least about of steps. I also was worry about my security.

Let start at the beginning
    Unzip the latest version in a folder on your webserver or upload files through FTP.
    Rename htaccess.txt to .htaccess (on Windows type .htaccess. or use the Command Prompt and "rename" command).
I  did renamed  htaccess.txt  to htaccess.htaccess.
    Enable PDO_SQLite if disabled.
    Open your browser to the folder URL.--- to www.chase 
    Fill in a username and password and review the settings.-- the was no field for this input.
How do I get bank data into program?
Again thank you all your help

**Comment by tactilis** [comment]
> First - my bank can only download to a PDF file
> Second - The CVS file was converted somehow from a PDF file

Extracting data from a PDF to produce a CSV is always going to a problematic.

Are you absolutely certain that your bank can only download to a PDF file? It's very unusual for a bank not to provide a means of downloading transaction data as CSV or QIF, or sometimes XML or OFX.

What bank do you use please (I guess Chase, based on your later statement above)?
And what is the account type?

<br>

>  so that why I want to do a direct connect download with MMEX.

I understand - but MMEX does not have a means of connecting to banks to download data.

The WebApp is a simple web interface that you can access from a mobile device to input transactions on the go, and then, at a later point, upload them to the MMEX desktop application.

You can read about it here: https://webapp.moneymanagerex.org/ - see the Home, Setup, and How it Works pages.

<br>

> Let start at the beginning
> ...

Your explanation of your actions is based on an incorrect understanding of what the MMEX Web App does.

So, let's concentrate on finding out how to get data from Chase.

A quick Google of: _Chase bank csv file_  gives loads of info about how to do it. See for example: https://www.tillerhq.com/how-to-export-chase-bank-statements-into-excel-and-google-sheets/

They support many formats, including CSV. It looks simple.

Once you have a CSV file, we can help with setting up Import into MMEX.

**Comment by nyc1199** [comment]
Ok... Thanks for the instructiuon.. I have the CVS file
What is next ?

**Comment by tactilis** [comment]
> Ok... Thanks for the instructiuon.. I have the CVS file

It's a **CSV** file. **C**omma **S**eparated **V**alues

It just a text file with commas (or sometimes tab characters) separating the data fields.

<br>

> What is next ?

@nyc1199 
What is next is a certain amount of exploration, discovery and self-guidance on your part.

We can help out when you have problems or questions, but we can't spoon-feed you each step.

<br>

If I were approaching this problem, I would:

1. Upgrade to the latest release: MMEX 1.6.4

2. Make sure I knew how to enter transactions manually and view them in MMEX. I'd make sure I knew how to manage Payees and Categories, etc. In other words, I'd ensure I'm proficient in the basic use of MMEX before importing from the bank.

3. Create a new database (maybe call it Test) to experiment on and test the importing of transactions. That way, if things don't go as planned, I won't mess up my main database.

_Tip_: Make sure you set the Opening Date on the test account to _before_ the earliest transaction date in your CSV file. Any transactions earlier than the Opening Date won't imported:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/0a09baf2-0faa-48be-b924-1056bfe37bd0)

4. _Optional_: I'd open the .csv file in a text editor (for example Notepad) so I gain an appreciation of what it contains.

5. In my Test database, I'd have a go at importing from the CSV file, making sure I match up the columns that MMEX will import with the _relevant_ columns in the file. I'd save the settings as a Preset, so I didn't have to re-enter them the next time I want to do the Import.

6. I'd check the transactions to ensure that the import worked correctly. If not, I'd highlight all the transactions in the account and delete them so I could try the Import again with changed settings based on what I'd learned.

7. Once that was all OK and I felt comfortable with the Import process, I'd read the comment above https://github.com/moneymanagerex/moneymanagerex/issues/6029#issuecomment-1596164744 and learn about Pattern matching Payees matching and assigning Categories.

8. Once happy with that, I'd export the next batch of transactions from my bank and import those into MMEX. I'd want to make sure that I set the date range when viewing the transactions online in my Chase account before downloading the CSV file so that for each new Import I don't end up with duplicated transactions in MMEX. Alternatively, I would just open the downloaded CSV in Notepad and make sure that I delete any lines for dates of transactions that I had already imported.

9. Now that I understand the process and have a simple workflow established, I'd do it for real on my main database and be pleased that I took the time to get things right.

<br>

Happy to answer questions if you get stuck. If you approach things step-by-step and observe what you are doing, then I'm sure you can work it out.

**Comment by nyc1199** [comment]
Thank you again.
I have some homework to do now.
I can import the CVS file into MMEX , but its the colunns are not matching.
I will work on it and get back to to you in a couple days.

**Comment by tactilis** [comment]
> I can import the CVS file into MMEX , but its the columns are not matching.

Since each bank produces a different format of CSV file, you as the user, have to set up the columns. That's what this panel is for:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/d6c57778-cdb8-409a-bf09-5ddb70e8f27c)


You get a preview of the columns you have defined and the corresponding data:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/366efd55-28d1-4bef-9dae-669dc8d480c1)
