### ISSUE TITLE
IUSE.L rate

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#6030]
Hi All!
The date is fine for me, but the prices are not correct. I looked at several stocks and the same error.

Ubuntu mate 22.04

![Névtelen](https://github.com/moneymanagerex/moneymanagerex/assets/80578702/a7a50e99-3363-4754-8deb-e87cd51457b5)

**Comment by n-stein** [comment]
Copying what I wrote in the other issue, I think this is the issue, or at least a contributing factor:

https://github.com/moneymanagerex/moneymanagerex/blob/master/src/stockdialog.cpp#L483

When the user clicks the save button whatever value is in the current price field gets applied to whatever date is in the history date text box. So if you click a line in the history panel and click save it will overwrite that line with the current price. This is why you see the same value repeated multiple times, it is overwriting on the save click. 

We should use Today date instead of the value from the history date control when the user clicks save.

**Comment by n-stein** [comment]
Switched to use current date for "Save" button press.
