### ISSUE TITLE
Stock updates URL using bad/illegal format or missing url

### ISSUE THREAD

**Issue by swjpanton** [moneymanagerex/moneymanagerex#6048]
MMEX version:
1.6.4 Mac OS version

![screenshot 1](https://github.com/moneymanagerex/moneymanagerex/assets/107315794/35ee2bbb-760c-467e-971e-5ed436c10a3d)

Is the bug reproducible? 
 - [x] Always 

Is there a solution to this for MaOs versions

**Comment by vomikan** [comment]
#6040

**Comment by tactilis** [comment]
@swjpanton 
Please could you check previous issues before raising new ones.

You raised **_exactly_** the same problem of 'URL using bad/illegal format or missing url' just **_2 days ago_** in https://github.com/moneymanagerex/moneymanagerex/issues/6041. You were informed then that your report was a duplicate of #6040.

@vomikan has just had to tell you that again. And then close your duplicate-duplicate issue.

Each time you raise duplicate issues, you make more work for other people.

Please read #6040. The bug is not fixed.

Thanks

**Comment by swjpanton** [comment]
The reason I issue the same request is the references gives are not understood and closed without explanation sonwhen they refer to windows and my system is mac then it tells me the issue is not solved. Its confusing when a reply is generic and not specific nor relevant to ones own operating system.Sent from my iPhoneOn 24 Jun 2023, at 19:06, Martin ***@***.***> wrote:﻿
@swjpanton
Please could you check previous issues before raising new ones.
You raised exactly the same problem of 'URL using bad/illegal format or missing url' just 2 days ago in #6041. You were informed then that your report was a duplicate of #6040.
@vomikan has just had to tell you that again. And then close your duplicate-duplicate issue.
Each time you raise duplicate issues, you make more work for other people.
Please read #6040. The bug is not fixed.
Thanks

**Comment by tactilis** [comment]
> the references given are not understood and closed without explanation.
>
> Its confusing when a reply is generic and not specific nor relevant to ones own operating system.

Because this is not a support forum. It is the place that MMEX developers discuss new features, solve existing bugs, and coordinate the development of MMEX.

The discussion here is necessarily technical.
