### ISSUE TITLE
database upgrade to version17 failed [ 1.6.4. ] Datebase upgraded?

### ISSUE THREAD

**Issue by Zharghoost** [moneymanagerex/moneymanagerex#6056]
Hi
I upgraded to 1.6.4. Went to open my database only to be told database not compatible. I ran downgrade_db_13_7_v4 as I thought this was what was necessary, [not that technically savvy] 
![mmex](https://github.com/moneymanagerex/moneymanagerex/assets/137896436/5c8f0714-8fb3-4a80-bdba-1ad2e209ae29)
This is all I get now. In a silly move I tried to open my backup which is now is the same state. Also all my .bak files all have the same date and file size and not working. I ask is my a database history? Or is there a way to salvage this situation?  either going forward or reverting to an older version of MMEX?

**Comment by renato-mmex** [comment]
a list of the database files would be helpful.
Here is information about such a problem: https://forum.moneymanagerex.org/viewtopic.php?t=10864

**Comment by Zharghoost** [comment]
> a list of the database files would be helpful. Here is information about such a problem: https://forum.moneymanagerex.org/viewtopic.php?t=10864

Hi, I Think this what you are asking for
![mmex 01](https://github.com/moneymanagerex/moneymanagerex/assets/137896436/e15e0cda-538e-4ad6-85f1-fbf4e1cb08dc)
All bak files were changed date, time, size to the same, which was not what I expected. Hoping I can get my working Database to open as my backup and bak files are now all the same.

**Comment by renato-mmex** [comment]
I miss the .mmb without upgrade
Apparently they were working with an ancient MMEX version before the upgrade to 1.6.4.

**Comment by n-stein** [comment]
@Zharghoost Your backup files are all the same because you upgraded MMEX from database version 7 to version 18 and MMEX saves a backup for each update. Don't worry, they should all have the same data.

You have a custom view in your DB called "cumulative". This view is unsupported in any recent version of MMEX. You have two options: delete the cumulative view or recreate the allData view. I would highly recommend deleting the "cumulative" view unless you use it for custom reports.

Please try this:

1. Copy `Money Manager UK.mmb_upgrade_v16_2023-06-27` and save it to a new name such as `Money Manager UK upgrade.mmb`. Make sure the filename ends in mmb.

2. Run MMEX and select this database. When presented with the "MMEX database upgrade to version 17 failed!" message, you should then get a message that looks like this:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/7c827c4c-1cca-4e0e-9601-cf73bb4588db)

3. Click "Yes" then choose _one_ of these files depending on what you need:

* If you do NOT need the cumulative view, use 
[drop_cumulative_view.zip](https://github.com/moneymanagerex/moneymanagerex/files/11888089/drop_cumulative_view.zip)

* If you DO need the cumulative view, use 
[recreate_allData.zip](https://github.com/moneymanagerex/moneymanagerex/files/11888090/recreate_allData.zip)

The update should be applied and you can reopen the database. Upgrade should then be successful.
