### ISSUE TITLE
Do not show the space where `Show Money Tips` is shown if option is disabled

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#6070]
1. Turn off `Show Money Tips`
![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/f36b907a-2b10-4248-bcec-5a1ea26da477)
2. Restart MMEX
3. Please remove the space where the money tips show so that more transactions can be seen on the screen and the buttons (New, Edit, Delete, Duplication, ...) are at the bottom of the screen.
![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/76452573-c527-483f-b5ff-0e364c8c0974)

What do you think?

Thank you

```
Money Manager Ex
• Version: 1.6.5-Beta.1 64-bit
• Built on: Jul 1 2023 03:27:17
• Database version: 18 (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.1.7 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.6
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.14
• gettext 0.21
• apexcharts.js
Built with:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.2.0
Running on:
• Ubuntu.22.04.jammy
• Linux Mint 21.1 "vera"
• Linux 5.15.0-76-generic x86_64
• (UTF-8)
• 0x0 0bit 192x192ppi
```

**Comment by renato-mmex** [comment]
Since I use a larger screen, this blank line does not bother me.

**Comment by rmelillo76** [comment]
The panel is necessary in order to display additional transaction details when items are selected, not just tips. For example:

- Selecting multiple transactions:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/a433fc49-1c24-40d6-adb5-a68a88867a37)

- Displaying notes for a single transaction:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/77576ca9-29cf-4eb0-a478-e6f9b33695bd)

**Comment by ovari** [comment]
Should the height of the panel be zero if there is no information to show?

**Comment by tactilis** [comment]
> Should the height of the panel be zero if there is no information to show?

I'd say no.

Visually, it would be unpleasant if the panel changed from zero height to (say) its current height because you selected multiple transactions and as a consequence the transaction you were looking at are now hidden, or had to scroll to keep them visible.

You can get a sense of what this looks like by maximising the MMEX window and then pressing Shift+F11 to toggle between normal and fullscreen view. Doesn't look great.

IMO, the suggestion adds complexity where there isn't really a problem to solve.

**Comment by rmelillo76** [comment]
@ovari I suppose you could consider raising an enhancement request to add an option to show/hide the details pane within the View menu. I personally would always keep it enabled, but like other preferences, such as showing, or hiding the toolbar and viewing MMEX in full screen, this could be a user preference.

I agree with  @tactilis that changing the height dynamically is not a good user experience.

**Comment by tactilis** [comment]
> I personally would always keep it enabled

Agreed. It would be strange to hide the panel.

Adding user preferences to suit everyone's ideas is never a good approach.

Joel Spolsky (the creator of StackOverflow, Trello and much more) summed it up well:

> Every time you provide an option, you’re asking the user to make a decision. That means they will have to think about something and decide about it. It’s not necessarily a bad thing, but, in general, you should always try to minimize the number of decisions that people have to make.

The full article is worth reading https://www.joelonsoftware.com/2000/04/12/choices/. It's an old piece but it still applies.

Designers should strive to make software that does the right thing for the majority of users and consider very carefully whether they really do need to complicate things to satisfy the 'advanced' user.
