### ISSUE TITLE
Add 2 weeks or 14 days to dashboard

### ISSUE THREAD

**Issue by PKCMVA** [moneymanagerex/moneymanagerex#6072]
Hi,  About 6 months ago I sent an email about adding "2 Weeks" or "14 Days" available in Dashboard\Income vs Expenses drop down list.

Was wondering if you could give me an update on this change anytime soon in future updates.

Thanks

**Comment by tactilis** [comment]
To whom did you send the email?  There is no change at present.

The best thing to do is add the details of your Feature Request here in _this_ issue.

And please could you clarify whether you really mean `Dashboard | Income vs Expenses`, because there is no date dropdown on the Dashboard.

Or do you perhaps mean `Reports | Income vs Expenses | Monthly` and are referring to the `Period` dropdown?

Or do you mean something else?

**Comment by tactilis** [comment]
> Or do you mean something else?

Ah, got it. You mean in the Options:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/f2a1e801-62f3-4af1-8e20-1cd9d193d760)

**Comment by tactilis** [comment]
What is the use case for having `Last 14 Days` please? Why is that a significant benefit compared to `Last 30 Days`?

**Comment by PKCMVA** [comment]
> > Or do you mean something else?
> 
> Ah, got it. You mean in the Options:
> 
> ![image](https://user-images.githubusercontent.com/4060092/250291057-f2a1e801-62f3-4af1-8e20-1cd9d193d760.png)

Yes this is the area I was hoping to see the change.  The reason for the 2 weeks or 14 days is pension and or unemployment payments are fortnightly.  People using the app including myself would find this very helpful when listing payments and expenses during this time period.

**Comment by tactilis** [comment]
@PKCMVA
>  People using the app including myself I think would find this very helpful **when listing payments and expenses during that time period**.

Can I just check that you really do mean the information that is displayed on the Dashboard since that shows just the totals for income & expenses in the specified period; i.e it doesn't **_list_** the actual "_payments and expenses_" or show them categorised in any way.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/799a73ae-0ecd-4bbe-ab19-476230983aeb)

**Comment by PKCMVA** [comment]
> @PKCMVA
> 
> > People using the app including myself I think would find this very helpful **when listing payments and expenses during that time period**.
> 
> Can I just check that you really do mean the information that is displayed on the Dashboard since that shows just the totals for income & expenses in the specified period; i.e it doesn't **_list_** the actual "_payments and expenses_" or show them categorised in any way.
> 
> ![image](https://user-images.githubusercontent.com/4060092/250367090-799a73ae-0ecd-4bbe-ab19-476230983aeb.png)

Yes, My idea was that if I could set the above window to 14 days or 2 weeks to match my income, it would work closely in conjunction with the Upcoming Transactions window which is 15 days.
When opening the app I'll see the current income /expenses balance for the fortnight which gives me feedback on spending during the current 2 weeks, and the upcoming transaction window gives me a quick reference showing me if I need to transfer money before the 2 weeks are up.

**Comment by n-stein** [comment]
I can just add '14' or make it user configurable like this:

![mmex_Nyfp2MnCtf](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/65a99f42-9d71-467a-bccf-a8ef1dd923ee)

**Comment by tactilis** [comment]
> I can just add 'Last 14 Days' or make it user configurable

My thoughts:

If the number of days was configurable it would satisfy @PKCMVA's request and anybody else who wanted a specific number of days.

I think the option would read better as `Last N Days`, rather than X.

If configurable , then there would be no point in retaining `Last 30 days`, `Last 90 days` and `Last 365 days`.

How are these stored in the DB? Would there need to be an upgrade script that converted any use of `Last 30/90/365 Days` to a setting of `Last N Days`?

**Comment by n-stein** [comment]
> If configurable , then there would be no point in retaining Last 30 days, Last 90 days and Last 365 days.

These are not truly day offsets, they are configured as month offsets. 30 days is actually -1 month, 90 is -3 and 365 is -12. For example, if today is 2023-03-01, `Last 30 Days` range is 2023-02-02 to 2023-03-01 which is only 28 days. If we change to `Last N Days`, it will be 2023-01-31 to 2023-03-01, i.e. a true last 30 days.
 
> How are these stored in the DB? Would there need to be an upgrade script that converted any use of `Last 30/90/365 Days` to a setting of `Last N Days`?

Currently only the 0-based index of the selection in the choice box is stored in HOMEPAGE_INCEXP_RANGE. We would indeed need an upgrade script, but it would be simple. I think this would do it:

```
UPDATE INFOTABLE_V1 SET INFOVALUE = '30' WHERE INFONAME = 'HOMEPAGE_INCEXP_DAYS' AND INFOVALUE = '3';
UPDATE INFOTABLE_V1 SET INFOVALUE = '90' WHERE INFONAME = 'HOMEPAGE_INCEXP_DAYS' AND INFOVALUE = '4';
UPDATE INFOTABLE_V1 SET INFOVALUE = '365' WHERE INFONAME = 'HOMEPAGE_INCEXP_DAYS' AND INFOVALUE = '14';
UPDATE INFOTABLE_V1 SET INFOVALUE = '12' WHERE INFONAME = 'HOMEPAGE_INCEXP_RANGE' AND (INFOVALUE = '3' OR INFOVALUE = '4' OR INFOVALUE = '14');
```

**Comment by PKCMVA** [comment]
> I can just add 'Last 14 Days' or make it user configurable like this:
> 
> ![mmex_Nyfp2MnCtf](https://user-images.githubusercontent.com/16599929/252774167-65a99f42-9d71-467a-bccf-a8ef1dd923ee.gif)

Yes, looking at your example above, that would be exactly what I was looking for if you could consider adding/changing.

**Comment by tactilis** [comment]
@n-stein
> These are not truly day offsets, they are configured as month offsets. 30 days is actually -1 month, 90 is -3 and 365 is -12. For example, if today is 2023-03-01, Last 30 Days range is 2023-02-02 to 2023-03-01 which is only 28 days.

Ah, yes of course. As you say, 'Last 30 (and 90) Days' are actually 'From a date one _month_ (3 _months_) ago until today', which is completely different from the 'fixed' 14 day duration that has been requested.

We should leave 'Last 30/90 Days' unchanged because they are also used in the Transaction and Report Filters:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/80dd3c79-7e9c-4cb3-a7de-91efef075641)
 
![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/3627c1f0-1bf8-43b5-8b12-205042ec5298)

In 2022, a user reported an error in the 'Last Month / Last 30 Days' date calculation https://github.com/moneymanagerex/moneymanagerex/issues/4155, so it's clear that some people do use these particular settings.

<br>

So, I think the best option for the dashboard is to add `Last N Days` as you proposed.

However, the title shown on the Dashboard would then be confusing because it wouldn't be clear whether the text `Last 30/90 Days` referred to the 1 month/3 month period or the 'fixed' Last N Days with N set to 30/90.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/c09ba188-b783-45a4-8d6b-048b88711295)


<br>

So, I propose that we clarify _exactly_ what the options do:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/780f6d7a-4d59-4bd0-8b47-b679827a9f7e)
 
![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/06c4f999-625d-4fe9-9fb1-3f808746d8aa)
 
![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/b1a63c09-fa58-4a23-80a2-11339bfffe71)

**Comment by n-stein** [comment]
Since we are discussing the accuracy of the selection titles, I think the `Last Month`, `Last 3 Months`, and `Last 12 Months` are a bit confusing since the word 'Last' is being used differently between them.

For reference, today's date is 2023-07-12, Here is what the date ranges are calculated as:

```
Current Month = 2023-07-01 to 2023-07-31
Current Month to Date = 2023-07-01 to 2023-07-12
Last Month = 2023-06-01 to 2023-06-30
Last 30 Days = 2023-06-13 to 2023-07-12
Last 90 Days = 2023-04-13 to 2023-07-12
Last 3 Months = 2023-05-01 to 2023-07-31
Last 12 Months = 2022-08-01 to 2023-07-31
Current Year = 2023-01-01 to 2023-12-31
Current Year to Date = 2023-01-01 to 2023-07-12
Last Year = 2022-01-01 to 2022-12-31
Current Financial Year = 2023-07-01 to 2024-06-30
Current Financial Year to Date = 2023-07-01 to 2023-07-12
Last Financial Year = 2022-07-01 to 2023-06-30
Over Time = 1900-01-01 to 9999-12-30
Last 365 Days = 2022-07-13 to 2023-07-12
Last 14 Days = 2023-06-29 to 2023-07-12
```
The option for `Last Month` is `2023-06-01 to 2023-06-30`, so in this case it is understood that 'Last' == 'Prior'. But then `Last 3 Months` is not the 'Prior 3 Months' range `2023-04-01 to 2023-06-30`, but is actually 'Prior 2 Months Through Current Month'. In this case we are using 'Last' == 'Latest' instead of 'Last' == 'Prior'.

Maybe we should explicitly call them `Latest 3 Months` and `Latest 12 Months`?

**Comment by tactilis** [comment]
All noted.

I suggest:

- Last Month ==> Previous Month  _(which is nicely grouped with the Current Month entries above)_
- Last Year ==> Previous Year _(ditto for the Current Year entries above)_
- Last Financial Year ==> Previous Financial Year _(ditto for the Current Financial Year entries above)_

I agree with your suggestion of:

- Last 3 Months ==> Latest 3 Months
- Last 12 Months ==> Latest 12 Months

This gives us a consistent naming convention for the adjectives in bold:

- **Current** XXX == The _whole_ of this XXX  (unless it is qualified by "to Date")
- **Previous** XXX == The one before the current XXX
- **Last** NN XXXs == The most recent NN XXXs _up to today's date_
- **Latest** N XXXs == The most recent N XXXs, including the _whole_ of the current XXX

So your example becomes:

```
Current Month = 2023-07-01 to 2023-07-31
Current Month to Date = 2023-07-01 to 2023-07-12
Previous Month = 2023-06-01 to 2023-06-30
Last 30 Days = 2023-06-13 to 2023-07-12
Last 90 Days = 2023-04-13 to 2023-07-12
Latest 3 Months = 2023-05-01 to 2023-07-31
Latest 12 Months = 2022-08-01 to 2023-07-31
Current Year = 2023-01-01 to 2023-12-31
Current Year to Date = 2023-01-01 to 2023-07-12
Previous Year = 2022-01-01 to 2022-12-31
Current Financial Year = 2023-07-01 to 2024-06-30
Current Financial Year to Date = 2023-07-01 to 2023-07-12
Previous Financial Year = 2022-07-01 to 2023-06-30
Over Time = 1900-01-01 to 9999-12-30
Last 365 Days = 2022-07-13 to 2023-07-12
Last 14 Days = 2023-06-29 to 2023-07-12
```

The only slight oddity is that `Last 30/90 Days` is adjusted for the lengths of the month(s) that are spanned. As these two items are grouped with the other Month related items, I'd be inclined to leave them as they are* _provided_ you are going to add `Last 14 Days` as shown and _not_ make the number of days user enterable.

* We can always include an example list like the above in the Help when we eventually get around to updating it.

**Comment by n-stein** [comment]
Perhaps `Last 30 Days` could be `Since 1 Month Ago` and `Last 90 Days` could be `Since 3 Moths Ago`?

Or we could base it off the current day: `Since the 13th of June` or `Since the 13th of Last Month`?

**Comment by tactilis** [comment]
> Perhaps Last 30 Days could be Since 1 Month Ago and Last 90 Days could be Since 3 Months Ago?

Yes. Like it. Very clear.

> Or we could base it off the current day: Since the 13th of June or Since the 13th of Last Month?

Don't like this. The user has to know what today's date is (I often don't!) to make sense of what the menu entry is trying to telling them.

**Comment by n-stein** [comment]
So to recap:

```
Current Month = 2023-07-01 to 2023-07-31
Current Month to Date = 2023-07-01 to 2023-07-12
Previous Month = 2023-06-01 to 2023-06-30
Since 1 Month Ago = 2023-06-13 to 2023-07-12
Since 3 Months Ago = 2023-04-13 to 2023-07-12
Latest 3 Months = 2023-05-01 to 2023-07-31
Latest 12 Months = 2022-08-01 to 2023-07-31
Current Year = 2023-01-01 to 2023-12-31
Current Year to Date = 2023-01-01 to 2023-07-12
Previous Year = 2022-01-01 to 2022-12-31
Current Financial Year = 2023-07-01 to 2024-06-30
Current Financial Year to Date = 2023-07-01 to 2023-07-12
Previous Financial Year = 2022-07-01 to 2023-06-30
Over Time = 1900-01-01 to 9999-12-30
Since 1 Year Ago = 2022-07-13 to 2023-07-12
Last N Days = 2023-06-29 to 2023-07-12 (N = 14)
```
Agreed?

**Comment by n-stein** [comment]
> * N = 1 means 'Today only'

Correct

> * N = 0, -1, -2 ... are invalid user entries

To alleviate any issues I've switched to a wxSpinCtrl with a min value of 1.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/a7eb2e64-3bef-4ae5-b6f9-e994f3b4ca19)

> * max is the value of `Today - 1900-01-01` i.e. currently 45118. If you allow a user to (foolishly) enter N greater than this, then the start date will be earlier than the start date we use for `Over Time`. Alternately, just limit N to 4 digits; I can't see that this would inconvenience anyone `Last 9999 Days` takes us back to Feb 1996

I had set max to today's MJD value, but that allows you to go back to 1858-11-17. Now changed the max to `Today - 1900-01-01`.

**Comment by n-stein** [comment]
Hmm. I didn't notice these have similar names:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/32b6293e-faf3-49fc-8746-ed39de482b39)

The only difference is `Since 30 days ago` and `Since 90 days ago` have an end date of `9999-12-31`. Perhaps we should be using `Since 1 Month Ago` and `Since 3 Months Ago` for those and use something like `1 Month Ago to Date` and `3 Months Ago to Date` for the ones which end on `Today`

**Comment by tactilis** [comment]
> Perhaps we should be using `Since 1 Month Ago` and `Since 3 Months Ago` for those and use something like `1 Month Ago to Date` and `3 Months Ago to Date` for the ones which end on `Today`.

Seems OK. Makes the period explicit, whereas there was before it was open to interpretation.

**Comment by ovari** [comment]
If today = 2023-07-20
Financial Year starts on 1st July
Date of earliest transaction = 1992-07-18

Dates | from | to | Image
--|--|--|--
Current Month | 2023-07-01 | 2023-07-31
Current Quarter | 2023-07-01 | 2023-09-30
Current Year | 2023-07-01 | 2023-06-30
Month to date | 2023-07-01 | 2023-07-20 | ![Month do date](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/a81ef42b-a73c-4cc3-b81a-ef41a2d1b262)
Quarter to date | 2023-07-01 | 2023-07-20
Year to date | 2023-07-01 | 2023-07-20
Earliest to date | 1992-07-18 | 2023-07-20
Last Month | 2023-06-01 | 2023-06-30
Last Quarter | 2023-04-01 | 2023-06-30
Last Year | 2022-07-01 | 2023-06-30
Last 12 Months | 2022-07-21 | 2023-07-20
Custom Date | Type or use Date picker | Type or use Date picker | ![Custom Date](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/f154e7f8-c2ef-41bb-8166-c8a695051815)

**Comment by n-stein** [comment]
I think this one can be closed as fixed
