### ISSUE TITLE
MMEX transactions not importing correctly

### ISSUE THREAD

**Issue by Ian53OBE** [moneymanagerex/moneymanagerex#6112]
>As of about 4 weeks ago, possibly after the most recent update,  MMEX imported transactions from a CSV file all show as withdrawals instead of properly distinguishing between deposits and withdrawals. 
> Please do not remove information attached below this text.

<hr> • Version: 1.6.4 64-bit<br>
 • Built: Jun 20 2023 20:16:42<br>
 • db 18 (aes128cbc)<br>
 • git 6b4cc698f (2023-06-20)<br>
 • master<br>
<br>
Libs:<br>
 • wxWidgets 3.2.1 (wxMac 12.6)<br>
 • wxSQLite3 4.9.1 (SQLite 3.40.0)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.87.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.45.1<br>
 • gettext 0.21.1<br>
 • apexcharts.js<br>
<br>
Built with:<br>
 • CMake 3.26.4<br>
 • GNU Make 3.81<br>
 • Clang Apple LLVM 14.0.3 (clang-1403.0.22.14.1)<br>
<br>
OS:<br>
 • macOS Monterey Version 12.6.7 (Build 21G651)<br>
 •  English (United Kingdom) (Western (Mac OS Roman))<br>
 • 1440x900 32bit 72x72ppi

**Comment by tactilis** [comment]
@Ian53OBE
This is probably easily resolved.

Please could you post a screenshot of the Import CSV screen set up in the way you are importing the transactions. Please make sure in the Preview area at the bottom of the screen you have scrolled the data lines so we can see at least 1 transaction that should be a deposit and one that should be a withdrawal.

Please paste the screenshot directly in the comment box here [https://github.com/moneymanagerex/moneymanagerex/issues/6112](https://github.com/moneymanagerex/moneymanagerex/issues/6112) rather than replying to a github email because screenshots/attachments get stripped off the emails.

Thanks

**Comment by Ian53OBE** [comment]
![Screenshot 2023-07-15 at 15 52 48](https://github.com/moneymanagerex/moneymanagerex/assets/139635837/e07fecac-c975-4aef-a74e-2f08af4432bd)

**Comment by Ian53OBE** [comment]
Just done.
🤞

**Comment by tactilis** [comment]
Thanks Ian.

BTW, there's no need to send a 'Just done' email afterwards. Just use the comment box in the issue.


You have made a small error in setting up the fields to be imported.

Although your bank has a 'Type' column in the CSV, this does not serve the same purpose as `Type` in the MMEX list of fields.

MMEX uses `Type`, if necessary, to determine if a transaction is a deposit or a withdrawal in the case that a bank doesn't distinguish between them using a positive or negative value for Amount. The text in the 'Type' field tells MMEX how to interpret the value.

But that doesn't apply in your CSV. Your bank's Type just shows whether the transaction is a BACS receipt/payment, a Point of Sale payment, a Direct Debit payment, etc.

You need to:
- Remove the MMEX `Type` field and replace it with `Don't care`
- Set the `Amount` dropdown to `Positive values are deposits` 

The `Balance` field could also be removed because MMEX _always_ calculates the balance from the sequence of deposit and withdrawal amounts. 

You might like to save the revised settings as a named Preset and tick the box saying `Load this Preset when Account is...`, which will save you having to set up the import details every time.
 
<br>

Once you have this working, you may like to explore the new Payee and Category matching capabilities introduced in 1.6.4. You can read about it in the last few comments here: https://github.com/moneymanagerex/moneymanagerex/issues/6057#issuecomment-1611087601 and here: https://github.com/moneymanagerex/moneymanagerex/issues/3148. The second of these discusses the development of the capability, so it's fairly long but the first few posts give you an idea about what it is for.

If you need any help, please ask.

**Comment by Ian53OBE** [comment]
Many thanks Martin, worked a treat.
I have been using MMEX for some time and not had this problem before. 
It seems to have started after the last update so something about that must have changed the settings.
I will keep the note as a reminder in case it happens again.

My stock prices haven't updated from Yahoo for a few months now. I saw others reported a problem but cant find the solution that was advised. Can you point me to it or do I report a new issue?

Once again thanks

Ian

**Comment by tactilis** [comment]
> It seems to have started after the last update so something about that must have changed the settings.

But it appears from your screenshot that you didn't have any settings saved as a Preset. I'm presuming that you have been manually setting it up each time.

Glad that import is working for you now.

**Comment by tactilis** [comment]
> My stock prices haven't updated from Yahoo for a few months now. I saw others reported a problem but cant find the solution that was advised. Can you point me to it or do I report a new issue?

The gory details are here: https://github.com/moneymanagerex/moneymanagerex/issues/6040

The upshot is that the problem _is_ fixed in MMEX 1.6.4 provided that you are not connecting to Yahoo from a GDPR country (UK & Europe). So, if you use a VPN with an endpoint in the US, then it will work.

Further fixes have been made for UK/Europe and will be included in the next release, which will be MMEX 1.7. This release is still a little way off.

If you wish, you can install the latest beta version of 1.7 from here https://link.ipx.co.uk/mmex-mac-betas which does include the fix. It's pretty stable but note that there is some development work in progress for a new feature called Tags, which you can just ignore for now.

Note that moving to 1.7 will automatically upgrade your .mmb database, so you won't be able to open it again in 1.6.4
Make a backup copy of your 1.6.4 compatible .mmb database before moving to 1.7

**Comment by n-stein** [comment]
> I have been using MMEX for some time and not had this problem before. It seems to have started after the last update so something about that must have changed the settings.

This is because prior to 1.6.4 the "Positive if Type has..." feature did not work correctly, and in prior versions the incorrect logic just happened to be working in your favor. I fixed it in #5772.

**Comment by tactilis** [comment]
@n-stein
> This is because prior to 1.6.4 the "Positive if Type has..." feature did not work correctly, and in prior versions the incorrect logic just happened to be working in your favor. 

Ah yes, I now recall you fixing that.

<br>

In any case @Ian53OBE, you should not be using Type for the reason I mentioned above in https://github.com/moneymanagerex/moneymanagerex/issues/6112#issuecomment-1636808870

**Comment by Ian53OBE** [comment]
Once again thanks but think I will wait for the update if there isn't a simple fix I can do. 
Most prices are down since the last update so I can avoid the bad news!
FYI though, I have found that although a request to update all prices wont work, if I click on a stock for details and then click on the icon to download recent prices they come through and update the stock values. So I can update but only one stock at a time. Strange if it is a GDPR issue. I mention in case it helps.

Regards

**Comment by vomikan** [comment]
CLOSE: question

REASON: OP's problem/question has been resolved.
