### ISSUE TITLE
Capturing tags in split transactions is not intuitive

### ISSUE THREAD

**Issue by luisdev** [moneymanagerex/moneymanagerex#6122]
MMEX version:
 - [x] 1.7.0-Beta. 1 64-bit

Operating System:
 - [x] Windows 10 22H2

# Description of the bug
Following on from my comments in https://github.com/moneymanagerex/moneymanagerex/issues/5439:

I struggled to work out how to capture tags on the Split Transaction window. And I'm still trying to get used to it.
How do select tags when navigating to the Tags field with your mouse?

Is it possible to make the tag selection field a drop-down list instead, like this:

![Split_Transaction](https://github.com/moneymanagerex/moneymanagerex/assets/1124791/c2a10efd-356b-46e3-a143-af799fd0642a)

**Comment by tactilis** [comment]
You either start typing a tag name and get a filtered list.
Or press Return to get Organize Tags.

**Comment by luisdev** [comment]
Thanks

> Because you can have multiple tags in the field, it doesn't really make sense to have a combobox dropdown.

I've seen combo-boxes that allow you to select multiple items on them in lots of applications.

![images](https://github.com/moneymanagerex/moneymanagerex/assets/1124791/05d014c8-eb09-4995-ab51-b4ebe699ab21)

I really think there is a strong case for being able to select multiple tags from the combobox dropdown. And because you can have multiple tags in the field you should be able to select them all at once.

**Comment by n-stein** [comment]
Something like this?

![mmex_soOl0knIjH](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/19493fde-fc5d-4a55-a924-142cc068e9a6)

**Comment by tactilis** [comment]
> Because you can have multiple tags in the field, it doesn't really make sense to have a combobox dropdown.

I retract my comment 😄 

The dropdown with check boxes looks good. However, given that you have had to add a button (which is not the same as a combobox dropdown) at the end of the text field, I'm wondering whether we could just employ that button to display the Organize Tags dialog rather than the dropdown checklist.

Advantages:
1. Familiar Organize dialog, which already has the ability to scroll and do check-box multi-select
2. Organize dialog allows searching
3. Provides a simple and obvious means of displaying the Organize dialog without the user having to know that they have to press Return/Enter to do so

The 3rd point is IMO the most compelling from a UI usability point of view. I have been thinking about how we can solve the problem of people not knowing about the fact they have to make a 'mystery' key press of Return/Enter at the _blank_ Category field to see the familiar _**hierarchical**_ Organize Categories dialog, which is much more navigable than the combobox dropdown.

This enhancement suggestion is one step towards aiding discovery of Return/Enter https://github.com/moneymanagerex/moneymanagerex/issues/6061 but it would be even better if the Category and Payee fields could operate more like the Tags field with an embedded button at the end which displays the Organize dialog instead of the huge linear list of categories when the current 'v' button is clicked. 

I think we have one chance, with Tags leading the way, to improve this area of poor UI discoverability in MMEX.

If this is a possibility I could mock up some screenshots if needed.

I'd welcome your thoughts.

**Comment by luisdev** [comment]
> Something like this?
> 
Yes. 👍

**Comment by n-stein** [comment]
> given that you have had to add a button (which is not the same as a combobox dropdown) at the end of the text field

I can use a natively drawn wxComboBox button instead. For some reason Windows draws it with the standard button background when calling wxNativeRenderer::DrawComboBoxDropButton but draws it with the wxSYS_COLOUR_LISTBOX background in the normal wxComboBox. Haven't figured out how to change it yet...

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/bf0dee54-f933-4943-8be4-873b54d4ef03)

> to see the familiar _**hierarchical**_ Organize Categories dialog, which is much more navigable than the combobox dropdown.

Showing Organize Categories is not the only option there. We could use a wxComboCtrl instead of a wxCombBox and populate the dropdown with the wxTreeCtrl:

![mmex_Gd9C8l3NW3](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/efc4b1a4-4d68-48fa-8752-6141f515abce)

**Comment by tactilis** [comment]
> Showing Organize Categories is not the only option there. We could use a wxComboCtrl instead of a wxCombBox and populate the dropdown with the wxTreeCtrl

The tree control improves readability and user comprehension hugely compared to the current monolithic category list.

It also helps people who have raised a problem with their long/deeply nested category names since they are no longer presented with:
`My very long category name:With a fairly long subcategory name:Followed by a further level of categorization`

So I'm 👍 for this.

<br>

It still doesn't help with the discoverability of `Press Return/Enter to Organize' but we could always add a hint to the field's tooltip. And if #6061 can be achieved at some point it will increase the chance of users finding this feature themselves.

**Comment by luisdev** [comment]
> However, given that you have had to add a button (which is not the same as a combobox dropdown) at the end of the text field,

I'm not sure what you mean here. Which text field? The Tags list? That's a list, not a text field.

**Comment by tactilis** [comment]
> I'm not sure what you mean here. Which text field? The Tags list? That's a list, not a text field.

Yes Tags.
It's based on a wxStyledTextCtrl.

But this is all overtaken by events (see the comments above)

**Comment by luisdev** [comment]
> Something like this?
> 
YES.

**Comment by n-stein** [comment]
> It's based on a wxStyledTextCtrl (or at least, was initially).

It's still basically a wxStyledTextCtrl, it's just now embedded in a wxPanel next to a wxButton that opens a wxPopupTransientWindow filled with a wxScrolledWindow that houses a wxCheckListBox.
