### ISSUE TITLE
New Transaction: Tags field: `Shift`+`Tab`, border with/without focus

### ISSUE THREAD

**Issue by ovari** [moneymanagerex/moneymanagerex#6142]
@n-stein perhaps some more tweaks for the Tags feature?

1. New Transaction
2. Press `Tab` until in `Tags` field
3. Press and hold `Shift` and press `Tab`
4. Bug: Focus alternates between the `Tags` and `Number` fields, instead of going in the opposite direction
5. Bug: The border of the Tags field seems different to the other fields when it doesn't have focus
6. Bug: The border of the Tags field doesn't have a blue border when it does have the focus. (however, `Notes` field doesn't have a blue border when it has focus either)

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/aba425f1-6bdd-431c-915d-aec6fce67c06)

![image](https://github.com/moneymanagerex/moneymanagerex/assets/17465872/7fa19164-d48e-4772-9e65-c2f187aa8453)

Thank you

```
Money Manager Ex
• Version: 1.7.0-Beta.1 64-bit
• Built on: Jul 25 2023 03:27:55
• Database version: 19 (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.1.7 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.6
• libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.14
• gettext 0.21
• apexcharts.js
Built with:
• CMake 3.22.1
• GNU Make 4.3
• GCC 11.2.0
Running on:
• Ubuntu.22.04.jammy
• Linux Mint 21.2 "victoria"
• Linux 5.15.0-78-generic x86_64
• (UTF-8)
• 0x0 0bit 96x96ppi
```

**Comment by n-stein** [comment]
>Bug: The border of the Tags field doesn't have a blue border when it does have the focus.

This is tough because wxWidgets doesn't have context sensitive window decorations for things like wxRichTextCtrl or wxStyledTextCtrl which it provides for the standard items such as wxTextCtrl and wxComboBox. We would have to come up with a platform-dependent solution to redraw the borders ourselves using the window device context.

**Comment by tactilis** [comment]
> This is tough because wxWidgets doesn't have context sensitive window decorations for things like wxRichTextCtrl or wxStyledTextCtrl which it provides for the standard items such as wxTextCtrl and wxComboBox. We would have to come up with a platform-dependent solution to redraw the borders ourselves using the window device context.

I'd suggest that it is left as it is then because:

1. It's a minor consistency/cosmetic UI issue. You know which field has focus due to the presence of the text cursor.
2. There are bigger fish to fry that, IMO, are more worthy of the personal time you are devoting to MMEX development.

**Comment by n-stein** [comment]
> Bug: Focus alternates between the Tags and Number fields, instead of going in the opposite direction
> Bug: The border of the Tags field seems different to the other fields when it doesn't have focus

These are both fixed.

**Comment by tactilis** [comment]
> These are both fixed.

Nearly.

If I Tab forward through the fields, focus goes:

- Category
- Split button
- Tags
- Number

as expected.


But if I Shift+Tab backward through the fields, focus goes:


- Number
- **Tags down arrow**
- Tags
- Split button
- Category

which is not quite as expected.

**Comment by n-stein** [comment]
> Nearly.

Got it, I've fixed the reverse Shift+Tab to skip the Tags down arrow.

> Also, is it possible to suppress the border and focus ring around the Tags down arrow? Not sure how feasible this is.

Maybe I can do you one better. I've implemented some custom context awareness on Windows including the subtle emphasis on mouse hover and highlighting on activation. I also blended the button into the text control until hovered or pressed, similar to the native combobox. On Windows 10 it's almost indistinguishable:

![mmex_khMStsaDfs](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/8664862b-677b-4f88-a298-1055e8d67c09)

@tactilis can you please check how this looks on Windows 11?

The Linux tag control doesn't have the context sensitive border (yet) but I did update the appearance to look more native:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/7bdb33bb-6941-42fe-9e91-e20fe067053d)

**Comment by tactilis** [comment]
> I've fixed the reverse Shift+Tab to skip the Tags down arrow.

Tested. All good.

> Maybe I can do you one better. I've implemented some custom context awareness on Windows including the subtle emphasis on mouse hover and highlighting on activation. I also blended the button into the text control until hovered or pressed, similar to the native combobox. On Windows 10 it's almost indistinguishable

That is superb. A huge improvement. Thank you.

<br>

I noticed a few tiny niggles on Windows 11:

1. The dropdown arrow moves up a few pixels when that part of the control is hovered over. But if that is not fixable then we can certainly live with it.
 
https://github.com/moneymanagerex/moneymanagerex/assets/4060092/cf3fcce8-a73c-4c4f-b226-6e55946655c4

2. The dropdown arrow appears to be redrawn when perhaps it is not necessary. You can see it flicker sometimes when you type a space at the end of a tag.

https://github.com/moneymanagerex/moneymanagerex/assets/4060092/58200cfa-89ef-492d-b30b-2aab506e2e6d


3. While testing, I did just once see the arrow and surrounding rectangle not get redrawn after I switched to another app and then back to MMEX. It was shown as a white area. I've not been able to reproduce this yet but will try to pin down the circumstances in which it occurs.

**Comment by n-stein** [comment]
> 1\. The dropdown arrow moves up a few pixels when that part of the control is hovered over. But if that is not fixable then we can certainly live with it.

Interesting, Windows 10 and 11 were rendering it differently. I've made a tweak that might fix this. I also turned off antialiasing so the drop arrow isn't blurry anymore. See if that helps.

> 2\. The dropdown arrow appears to be redrawn when perhaps it is not necessary. You can see it flicker sometimes when you type a space at the end of a tag.

I disabled background erasing on the repaint which should help with flickering as the control isn't erased prior to being redrawn.

> 3\. While testing, I did just once see the arrow and surrounding rectangle not get redrawn after I switched to another app and then back to MMEX. It was shown as a white area. I've not been able to reproduce this yet but will try to pin down the circumstances in which it occurs.

This was happening only the first time the Alt key was pressed in a dialog (when the accelerator hints are displayed). While redrawing the controls to display the accelerator hints wxWidgets wasn't applying the custom painting for the button. I've forced it to repaint the control when the user presses the alt key.

**Comment by tactilis** [comment]
Thanks.

Testing:
• Version: 1.7.0-Beta.1 64-bit
• Built on: Aug 11 2023 07:15:42
• Database version: 19 (aes128cbc)
• Git commit: fbbfc33 (2023-08-11)

Good news...
- The arrow is no longer blurry. It looks consistent with the combobox arrows now.
- The Alt key blanking of the button is fixed, although it does get redrawn repeatedly if Alt is kept held down. I don't see this as a big issue though

Unfortunately...

1. The arrow still jumps when the button gets focus
 
https://github.com/moneymanagerex/moneymanagerex/assets/4060092/4ac29f65-7dd3-4ccc-b088-da446a6dacb3
 
 <br>

2. The arrow flickers even more frequently than it did previously when the tag field has focus. This however, stops while I'm screen recording, so I can't show this.

However I can record the flickering that occurs when typing. Here I am holding down the space key:

https://github.com/moneymanagerex/moneymanagerex/assets/4060092/1d21429a-0995-440f-9c55-b9f630a4a931
 
That flickering is similar to, but a bit faster than, the flickering that occurs when the field has focus but the user is not typing.

**Comment by n-stein** [comment]
> The Alt key blanking of the button is fixed, although it does get redrawn repeatedly if Alt is kept held down. I don't see this as a big issue though

I've changed this to only repaint the first time ALT is pressed in a dialog (when the accelerator hints are shown). There is a slight flicker on my machine when it happens, but it only happens once and most likely during an Alt+Tab so the user won't even see it.

> 1. The arrow still jumps when the button gets focus

Doh! It was working for me because I had my font set to "enlarged" while you were using "normal". I've adjusted the code and it works with any setting now.

> 2. The arrow flickers even more frequently than it did previously when the tag field has focus. This however, stops while I'm screen recording, so I can't show this.

I've removed the button refresh from the textctrl paint method by implementing clipping regions, so this should cut down on the number of times the button is cleared and redrawn. This should resolve flicker issues.

Finally, I made a few minor adjustments to get the control closer to native in its disabled state (white background, grey arrow):
![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/50fc3db9-5c66-41c4-a697-0bec9b7cf450)

The dropdown button also now correctly closes the popup window, I forget what issue that was mentioned in.

**Comment by tactilis** [comment]
Confirmed that all the above are fixed.  Looking good.

**Comment by tactilis** [comment]
Testing:
• Version: 1.7.0-Beta.1 64-bit
• Built on: Aug 11 2023 20:39:34
• Database version: 19 (aes128cbc)
• Git commit: 808ca54 (2023-08-11)

Some odd behaviour when filtering tags.

I created 3 Tags:
Cat
Tag
Travel

If I type any letter in the Tag field, then the filtered list is displayed as expected. For example:

a
[Cat]
[Tag]
[Travel]

g
[Tag]

c
[Cat]

But if I (accidentally) use Alt as a modifier, then I still get a filtered list but the character typed does not appear in the Tags field.

Alt+a
[Cat]
[Tag]
[Travel]

Alt+g
[Tag]

Alt+c
NO LIST DISPLAYED because Alt+c = Cancel button (which no longer works)

The Alt+letter combinations should not have any effect in the Tags field. Alt+c and Alt+O should activate Cancel / OK
Alt+c

**Comment by tactilis** [comment]
If I type a letter in the Tags field, I now have to double click the tag name in the filtered list to select that tag.

It should be selected by a single click (like in the combobox lists)

**Comment by n-stein** [comment]
> But if I (accidentally) use Alt as a modifier, then I still get a filtered list but the character typed does not appear in the Tags field.

Fixed.

> The Alt+letter combinations should not have any effect in the Tags field. Alt+c and Alt+O should activate Cancel / OK Alt+c

Alt+O works, but I tested as far back as 1.6.1 and Alt + C doesn't close the dialog, so this isn't related to the tags change. Will investigate this.

**Comment by tactilis** [comment]
> Alt+O works, but I tested as far back as 1.6.1 and Alt + C doesn't close the dialog, so this isn't related to the tags change. Will investigate this.

I made the wrong assumption that because Alt+c was not producing the filtered tags list _and_ that the C in Cancel was underlined, it was a case of cause and effect. My bad for not investigating the behaviour fully.

As it happens, although I am a keyboard shortcut user, I never use Alt+c to Cancel.
ESC (or double ESC if a field has focus) is my normal way of cancelling the dialog.

**Comment by ovari** [comment]
1. Shift + Tab FIXED
2. Border with/without focus WONTFIX

Thank you
