### ISSUE TITLE
Non riesco a vedere le schermate di visualizzazione dei vari conti

### ISSUE THREAD

**Issue by Guidomagno** [moneymanagerex/moneymanagerex#6175]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.
Buonasera, nei vari conti da alcuni giorni non riesco a vedere la schermata di visualizzazione (non vedo le righe del conto)
Importante: non so quale versione posseggo, non riesco a vederlo da nessuna parte

Screenshot di uno dei conti, prima vedevo tutte le righe
![image](https://github.com/moneymanagerex/moneymanagerex/assets/142315184/a9ad28d0-4352-4f2f-841f-8fa09ff60536)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by tactilis** [comment]
Auto-translation to English:

---
**I can't see the display screens of the various accounts**

Good evening, in the various accounts for a few days I can't see the display screen (I don't see the account lines)
Important: I don't know which version I own, I can't see it anywhere

Screenshot of one of the accounts, before I saw all the lines
---

From the screenshot, it looks as though you are using an ancient version of MMEX.

Go to the `Help` (Guida) menu and select `About`

Please copy and paste here the version information I have highlighted.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/4060092/d34e1f35-e6e0-4a42-8d73-097f13b3735c)

**Comment by Guidomagno** [comment]
Good monring

Thank you

Version 0.9.9.0.

Regards

**Comment by tactilis** [comment]
> Version 0.9.9.0.

The version you are using is from 2012.

There have been about 50 new releases of MMEX since then with 1000s of bug fixes and additions of new functionality.

Did you download it 12 years ago and never update it? Or did you download the old version from somewhere it more recently?


We cannot support such ancient software.
It _may_ be possible  to upgrade your database to be compatible with the latest release, which is version 1.6.4.

Someone will be along soon to confirm whether this is possible.

**Comment by Guidomagno** [comment]
Good evening
I downloaded this versione in 2016 and never updated It
Regards


Il sab 19 ago 2023, 00:07 Martin ***@***.***> ha scritto:

**Comment by tactilis** [comment]
> I downloaded this versione in 2016 and never updated It

Not sure why you downloaded 0.9.9 in 2016 because that version was already several years out of date then.
The release versions of MMEX in 2016 were 1.2.x and then 1.3.0

<br>

Anyhow, we need to upgrade you to 1.6.4 now so that we can provide support.

I've located an old installer for 0.9.9 and created a test database. Unfortunately, the database upgrade mechanism does not work all the way up to the 1.6.4 database standard.

Would you be willing to email your .mmb file to me so that the problem can be resolved and have it converted to a compatible standard? The database will be treated in confidence and then deleted afterwards.

If you are OK to do this, the email address is martin [at] tactilis [dot] co [dot] uk


Using MMEX 0.9.9 is a pretty unpleasant from a user interface point of view. You will find 1.6.4 an improvement in so many ways.

**Comment by whalley** [comment]
Closing as no further updates from originator.
