### ISSUE TITLE
General Manager Reports

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#6185]
The context menu appears only in a very small area. It is necessary to click on the root word. Not very intuitive.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/3af3b6e0-676a-473d-bf83-f29e43faf066)

**Comment by luisdev** [comment]
I'm trying to test this in Money Manager Ex:
• Version: 1.7.0-Beta.1 64-bit
• Built on: Oct 3 2023 09:58:24
• Database version: 19 (aes128cbc)

• English (South Africa) (windows-1252)
• Windows 10 (build 19045), 64-bit edition
• English (South Africa) (windows-1252)

But I'm not sure what the problem is. Can you explain the problem further?

**Comment by n-stein** [comment]
> Can you explain the problem further?

I believe the ask is to be able to access the context menu by right clicking anywhere in the left panel. Currently you have to right click directly on a tree item.
