### ISSUE TITLE
No error message shown when unable to move transactions from one account to another with an invalid account creation data

### ISSUE THREAD

**Issue by Shrinks99** [moneymanagerex/moneymanagerex#6338]
MMEX version:
 - [x] 1.6.4

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [x] Mac OSX (tested)
 - [ ] Linux 

# Description of the bug

When moving one or more transactions to another account that was opened after the transaction was created using the right click `Move Transaction` feature, the app will not give the user any visible feedback when it fails to move the transaction.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

- Create two accounts, one opened on the current date, and another opened a month in the past
- Create a transaction in the past account, right after the account was opened (or similar date)
- Attempt to move that transaction to the account created on the current date by right clicking and using the context menu `Move Transaction` option.
- Select the current date account
- Nothing should happen and the user isn't notified as to why

Expected result:

An error message stating that the account date is not reconcilable with the transaction date

Actual result:

The user is given no information.

This error is helpfully present if you try to try to complete this same action through the `Edit Transaction` dialog.

<img width="478" alt="Screenshot 2023-12-01 at 4 46 44 PM" src="https://github.com/moneymanagerex/moneymanagerex/assets/5672810/6dce6843-9d73-457d-ba64-3fdc7090eeaa">

# Additional information

A warning popup appears before a second confirmation dialog for no reason when using the context menu `Move Transaction` function.  This serves little purpose, as the next step of this process sees the user making a selection and confirming.  Essentially there's a double confirmation step that doesn't need to be here and can be removed to streamline this process without losing the check that the user is sure they want to move this transaction.

**Comment by whalley** [comment]
Thanks for reporting and the clear description. I can reproduce.

**Comment by whalley** [comment]
Having checked, there are a number of instances when the transaction cannot be moved - if the account is locked, it is a transfer (or related to a share account), or the date is earlier than the account opening date. You can of course also move multiple transactions in one operation.

The behaviour of silently ignoring any moves that cannot be done is consistent with the logic when editing multiple transactions, which also edits what it can but ignores transactions that it cannot.

I suggest we pop a dialog up reporting the number of successful and unsuccessful transfers if any could not be done with a general explanation that one or more of the transactions could not be moved/edited due to the transaction detail. Whilst this does not fully explain the reasoning it would get messy, and require a bit of work, if we reported the exact transactions and reasons.

Not ideal, but at least gives the user a notification that something could not be actioned.

**Comment by Shrinks99** [comment]
In an ideal world I might recommend a toast pop up of some kind that over a dialog?

'''
10 Transactions moved successfully.

8 Couldn't be moved.

[More Info]
'''

Clicking on more info might open a more detailed dialog with the exact reasons for each?

Unsure if you have the components for that, but this way we can reduce the number of user interactions required while retaining the same data?

**Comment by Shrinks99** [comment]
> Only appears if any are not moved.

Seems like a good compromize! :)

**Comment by whalley** [comment]
Fixed: https://github.com/moneymanagerex/moneymanagerex/pull/6351/commits/12440a86e6abc82b0ff4270f2176f4426abd7f70
