### ISSUE TITLE
error update db17

### ISSUE THREAD

**Issue by nekely** [moneymanagerex/moneymanagerex#6451]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [x ] 1.6.2

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

I get this message when trying to open my DB in versions higher than 1.6.1

![Captura de pantalla 2024-01-11 125212](https://github.com/moneymanagerex/moneymanagerex/assets/74736293/6281bed5-27ae-4c63-bfcd-9b97c4583495)

**Comment by vomikan** [comment]
This issue the same https://github.com/moneymanagerex/moneymanagerex/issues/1951

**Comment by nekely** [comment]
thanks, 
it worked for me

**Comment by n-stein** [comment]
Hmm, I thought I had fixed this issue with some clever SQL in the v17 upgrade script... seems it isn't working as intended. If you wouldn't mind, could you send a sanitized copy of your v16 database (the upgrade should have created a backup of it, just open it with 1.6.1 and delete all transactions) so that we can see where it went wrong?
