### ISSUE TITLE
Opération récurente ferme l'application

### ISSUE THREAD

**Issue by Salsaqueen51** [moneymanagerex/moneymanagerex#6560]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.
J'ai plusieurs bases dans l'application et une seule pose le problème suivant: 
Lorsque je suis dans les "opérations récurrentes" et que je veux en inclure une dans le compte associé l'application se ferme systématiquement. 
![image](https://github.com/moneymanagerex/moneymanagerex/assets/162434299/fa5398cf-d0cf-4c32-b80f-7b2a3f9c20d7)

Lorsque je lance de nouveau l'application j'ai le message d'erreur qui m'indique que l'application est déjà ouverte... 
![image](https://github.com/moneymanagerex/moneymanagerex/assets/162434299/c9cb3d4a-4a05-4077-9d0a-c3a6c1ceac6d)

J'ai été cherché la mise à jour (avant j'avais la version 1.5.0, je crois) mais le bug est toujours présent. 

Merci pour votre aide. 

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by n-stein** [comment]
There is a known issue in 1.7.0 with recurring transactions that exceed the credit limit you have set for the account. It has been fixed in 1.7.1. Try the beta.

La version 1.7.0 présente un problème connu concernant les transactions récurrentes qui dépassent la limite de crédit que vous avez définie pour le compte. Ce problème a été corrigé dans la version 1.7.1. Essayez la version bêta.

https://ci.appveyor.com/project/whalley/moneymanagerex/builds/49327749/job/hijsbgny22i3a5a9/artifacts
