### ISSUE TITLE
can not type Dot in % Rate Inputbox of Asset dialog 

### ISSUE THREAD

**Issue by DevelopmentAnything** [moneymanagerex/moneymanagerex#6618]
MMEX version:
 - [ ] 1.6.4
 - [ ] 1.7.0
 - [x] 1.7.1 RC1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows 11
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/6ddab5cc-b663-4060-ae9e-f2ef7482ac04)
can not type Dot in % Rate Inputbox of Asset dialog 

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. click Assets (navigation Tree)
2. open New/Edit Asset dialog

![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/de0d484d-b11a-46df-bf2a-80d89370b61b)

3. typing number with dot (19.2)

Expected result:

insert '.' (dot)

19.2

Actual result:

can not type Dot.
19

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

v1.6.4 ~ v1.7.0 no problem.
but, v1.7.1 beta~RC have problem.

**Comment by n-stein** [comment]
What is your locale set in Options?

**Comment by DevelopmentAnything** [comment]
> What is your locale set in Options?

ko_KR
is %Rate related to locale?

**Comment by n-stein** [comment]
> % value should not be affected by the locale setting.

Any numeric field is dependent on locale because many locales do not use `.` as their decimal separator. Take `de_DE` for example where the usage of `.` and `,` are reversed from en_US or ko_KR. If a user enters `1.234` MMEX must interpret that as `1234.00`. Likewise `1,234` must be interpreted as `1.234`.

> Currency Locale = (Empty) >> can type Dot .

If you don't set a locale MMEX uses the decimal separator of the account currency (or `.` if there is no currency decimal as in the case of KRW).

> Currency Locale = ko_KR >> can not type Dot

I am currently unable to reproduce this by setting the MMEX locale to ko_KR, but I suspect it may be because my Windows locale is en_US. I will install the Korean language pack and see if that changes things.

**Comment by DevelopmentAnything** [comment]
@n-stein 

I just found out one thing.

qwerty Keyboard
 zxcvbnm,./  keys:  .(>) key is can type Dot.
but, Num Pad's .(Del) key is can not type Dot.

So it has nothing to do with the locale setting.
This seems to be a problem with MMEX.

**Comment by DevelopmentAnything** [comment]
This is a problem caused by ignoring the corresponding key value during input.
If the cursor is off after input, it should be processed.

MMEX is processing events both during and after input.

Typing...
![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/7cf1594e-c6da-43bd-b28e-e4adbff6f6b8)

Focus out
![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/57a4396f-322d-4144-a1aa-69b345d53d5b)

In the figure above, the . key on the left was used (not Numbad)

![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/c5050eae-54fc-4974-8fd2-474e1aa6defd)

**Comment by n-stein** [comment]
> qwerty Keyboard
> zxcvbnm,./ keys: .(>) key is can type Dot.
> but, Num Pad's .(Del) key is can not type Dot.

Ah, that explains why I couldn't reproduce. My keyboard lacks a num pad.

I have pushed a potential fix. Please try https://ci.appveyor.com/project/whalley/moneymanagerex/builds/49495151/job/tnk51c3gru1ilhjm/artifacts after the build finishes.

> MMEX is processing events both during and after input.

Yes, this is required because the user can enter calculations such as `1+(.599/12)` and MMEX will perform the calculation once the user clicks out of the field. 

It should also restrict you to enter only one decimal point, maybe the above fix will also correct that for you.

**Comment by DevelopmentAnything** [comment]
Test complete. GOOD. 😀

![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/118d352f-f3ab-4f11-bbd3-84715fb601f2)
