### ISSUE TITLE
Import CSV dialog is not not adapting to the screen size

### ISSUE THREAD

**Issue by spillaip** [moneymanagerex/moneymanagerex#6636]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

When CSV Import dialog is opened, the window does not appear fully. On my screen the filename field is missing. When I try to resize, then the preview panel is not visible.  My screen size is 14 inches.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:
Navigate to File->Import From -> CSV
Expected result:
The dialog appears fully with the action buttons and all the options
Actual result:
File name and Browse are invisible.  If I resize then the Preview is not visible.
# Additional information
<img width="714" alt="mmx-import-01" src="https://github.com/moneymanagerex/moneymanagerex/assets/13807297/107ed964-4372-43f0-b5e1-a213516cc866">

If you have a backtrace for a crash or a warning, paste it here.
[

**Comment by spillaip** [comment]
Thank you so much, appreciate it!

**Comment by spillaip** [comment]
I have downloaded the suggested version.  But the issue is still exists

[image: image.png]

**Comment by rmelillo76** [comment]
> I have downloaded the suggested version. But the issue is still exists

@spillaip  can you provide a screenshot and confirm the version you tested with?
I just installed the latest beta, forced my resolution to 1366x768, and it is working as expected for me. See below, horizontal and vertical scrollbars are added so that the dialog fits within the display area:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/51d6fcab-a30f-41a5-9349-aaf533360658)


![image](https://github.com/moneymanagerex/moneymanagerex/assets/95182117/618631c9-d1fb-4d9b-b0eb-fb52212c4fc0)

**Comment by spillaip** [comment]
I have done a clean install again.  My laptop has a 14" display, although
the dialog was not responsive, I do see a scroll bar on the vertical side.

**Comment by rmelillo76** [comment]
@spillaip can you provide screenshots showing us the issue as well as the about screen so we can confirm the version and other diagnostic info. You'll also need to visit the issue page here rather than use the email reply in order to attach screenshots.

**Comment by spillaip** [comment]
Please find the screenshots

<img width="303" alt="mmex-version" src="https://github.com/moneymanagerex/moneymanagerex/assets/13807297/ce9a7b11-45b3-47a4-a3e6-124069ee4ec9">


<img width="719" alt="mmex-import-dialog" src="https://github.com/moneymanagerex/moneymanagerex/assets/13807297/5f321b4e-bc72-4648-8d44-7b1defc1a334">

**Comment by rmelillo76** [comment]
> Please find the screenshots
> 
> 
> 
> <img width="303" alt="mmex-version" src="https://github.com/moneymanagerex/moneymanagerex/assets/13807297/ce9a7b11-45b3-47a4-a3e6-124069ee4ec9">
> 
> 
> 
> 
> 
> <img width="719" alt="mmex-import-dialog" src="https://github.com/moneymanagerex/moneymanagerex/assets/13807297/5f321b4e-bc72-4648-8d44-7b1defc1a334">
> 
> 

Thank you for providing the screenshots. From my perspective, this is working as it should. The window was changed to be scrollable so there are both horizontal and vertical scroll bars on the outermost part of the dialog. That was the intended change so I'm unclear on what issues you are still experiencing.

**Comment by spillaip** [comment]
My understanding of responsiveness is to resize the import dialog to the display without scrollbars.

**Comment by rmelillo76** [comment]
Thanks, now I understand. No, unfortunately that's not how MMEX is designed. Most of the dialogs will remember the last size and a few of the larger windows such as this one now have scrollbars so they fit within the boundary of your screen, but that's the extent.

Redesigning the user interface to be responsive is probably not possible, that's something you typically see in a web-based application which MMEX is not. The underlying framework does not have that functionality built-in, and there are complexities with cross platform compatibility that would probably make it a nonstarter. And MMEX is designed to run on a traditional desktop, not mobile where a responsive UI is necessary. 


Potentially, we could add to the backlog a redesign some of the busier windows to incorporate the use of tabs so that there aren't so many controls on one panel but for now the best we can do is the changes that were made to add the scrollbars.

**Comment by spillaip** [comment]
I totally understand the constraints, may be I was ambitious.  I think the usability improves if  window resize is enabled.  I see currently it is disabled.
