### ISSUE TITLE
Credit Limit progress bar shouldn't include future payment

### ISSUE THREAD

**Issue by gemellon** [moneymanagerex/moneymanagerex#6640]
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [x] Mac OSX
 - [ ] Linux 

# Description of the bug

The new progress bar for Credit Cards (#6311) is including a future payment when it shows the %. This means the user can think they have more available balance than they have. 

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Make a new transaction for a future date in your credit card account.

Expected result:

Credit limit progress bar is accurate to the current day, because it is allowing user to view remaining credit on account.

Actual result:

Credit limit progress bar includes the future transaction, so the user doesn't see an accurate remaining credit for the current day.

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by n-stein** [comment]
I think the issue is really that the "Ignore Future Transactions" setting doesn't work in the checking panel.

For example, I have a future deposit. Without "Ignore future transactions" it is shown and included in the balance summary:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/b900e1f1-d23e-40b4-a262-2024820dc554)

If I turn on "Ignore Future Transactions" it is no longer shown, but is still included in the balance summary:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/baf99c7f-c0fb-4514-8fa7-d06e7f810613)

The dashboard does report the current balance correctly:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/f9b5b319-55e2-42c6-8ed2-4c2d258cd7f7)

**Comment by n-stein** [comment]
Now the setting is respected. If you want to see the current balance turn on View -> Ignore Future Transactions.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/ebfabeef-f340-42d4-ae4c-ceda2d100196)

**Comment by ovari** [comment]
`exclude` and `hide` may be other suitable options for `ignore`.
https://www.beyondbank.com.au/need-help/how-to-exclude-or-hide-transactions.html

`show` may be another suitable option for `display`.
https://community.quicken.com/discussion/7852401/how-do-i-view-future-scheduled-transactions

**Comment by n-stein** [comment]
The option doesn't just suppress the display of the transactions in the account panel or transaction report, it also prevents them from being included in any calculations so perhaps `Show`, `Display`, or `Hide` don't convey enough information here. `Exclude` is probably closest to the intended meaning of `Ignore`. Maybe we just need a tooltip to provide more context for that setting?

**Comment by ovari** [comment]
Would another way to write "Credit Limit progress bar shouldn't **include** future payment" (this issue title) be "Credit Limit progress bar should **exclude** future payment"? This would agree with your comment that:
> `Exclude` is probably closest to the intended meaning of `Ignore`.
