### ISSUE TITLE
kann Buchung nicht abschließen, dann kommt folgende Meldung.

### ISSUE THREAD

**Issue by Geju57** [moneymanagerex/moneymanagerex#6741]
>mein
[dokumentation an pP.docx](https://github.com/moneymanagerex/moneymanagerex/files/15302137/dokumentation.an.pP.docx)
Programm lässt sich ganz normal öffnen, Nachdem ich eine Buchung eingegeben habe und mi OK bestätige ich die Buchung und es kommt zu dieser Fehlermeldung. Wie kann ich das Problem lösen?

PyMEEgeTex"
CHECKINGACCOUNT_V1: Exception attempt to write a readonly database[8]: attempt to write
ro readonly database, -
"TRANSID":-1,
"ACCOUNTID": 2,
"TOACCOUNTID": 25,
"PAYEEID": -1,
"TRANSCODE": "Transfer"
TRANSAMOUNT": 10.0,
"STATUS": E
"TRANSACTIONNUMBER":
"NOTES": E
"CATEGID": 865,
"TRANSDATE": "2024-05-13"
"LASTUPDATEDTIME": "2024-05-13T06:18:49"
"DELETEDTIME":
"FOLLOWUPID": -1,
"TOTRANSAMOUNT": 10.0,
"COLOR": -1E": "2024-05-13"
"LASTUPDATEDTIME": "2024-05-13T06:18:49"
"DELETEDTIME":
"FOLLOWUPID": -1,
"TOTRANSAMOUNT": 10.0,
"COLOR": -1

**Comment by renato-mmex** [comment]
@Geju57 
translated to english with www.deepl.com
_The program opens normally. After I have entered a booking and confirmed it with OK, I get this error message. How can I solve the problem?_
.
Since you do not tell us which operating system or which version of MMEX is causing the error, we can only guess.
Presumably you are using Linux and the MMEX directories/files are write-protected.
......._Exception attempt to write a readonly database[8]: attempt to write ro readonly database,_ 

auf deutsch:
Da Sie uns nicht mitteilen, mit welchem Betriebssystem, welcher Version von MMEX der Fehler auftritt, kann man nur raten.
Vermutlich verwenden Sie Linux und die Verzeichnisse/Dateien von MMEX sind schreibgeschützt.

**Comment by Geju57** [comment]
Hallo Renate, ich danke Ihnen für Ihre Antwort. Die Datei war wirklich schreibgeschützt. Jetzt funktioniert wieder alles einwandfrei.
Liebe Grüße

Gerhard

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
