### ISSUE TITLE
Delete menu is not visible

### ISSUE THREAD

**Issue by DevelopmentAnything** [moneymanagerex/moneymanagerex#6747]
MMEX version:
 - [ ] 1.7.0
 - [ ] 1.8.0
 - [x] 1.8.1 b1
 - [ ] 1.8.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/07eed40e-3e43-478c-9acd-f01fcc71eb7f)

langs: en-US, ko-KR, ...

empty menus... but can click menus

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

transaction grid
open context popup - delete sub menu

Expected result:

visible menus

Actual result:

empty string

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by renato-mmex** [comment]
On this homepage, users can make the translations themselves.
https://crowdin.com/project/moneymanagerex

**Comment by DevelopmentAnything** [comment]
@renato-mmex 
It's a different answer from the topic.
And please point out exactly what hasn't been translated. There are only 3 that I haven't translated.

**Comment by renato-mmex** [comment]
Sorry, it concerns the translations. I checked it in my German version and found that the texts are displayed in English, although I translated them into German.
It seems that there is a problem with the assignment of the texts.
<img width="487" alt="image" src="https://github.com/moneymanagerex/moneymanagerex/assets/76920138/0c08ac00-b8de-49bb-ac90-34156aba5982">

**Comment by ovari** [comment]
Crowdin is yet to be updated with the English source strings. @vomikan might be able to advise when the update is expected.

**Comment by n-stein** [comment]
Keyboard shortcuts were recently added, so the strings need to be pulled into Crowdin and retranslated:

700dbdd31a310414dabb3c65f00de56add114e9b
bf04a48646b2f858f79be269c8cb0ed83c4b939c

**Comment by n-stein** [comment]
The empty menus you see are probably because because the commits I referenced above changed the ASCII character `"` to the Unicode characters U+201C and U+201D `“ ”`, but the escape characters `\` were left in (when there is now nothing to escape). This results in an incorrect byte sequence when trying to convert to a wxString. 

However, we also can't just drop Unicode characters directly into the source strings and expect them to work -- you have to explicitly tell wxWidgets to interpret it as UTF-8. Otherwise it gets interpreted according to the standard encoding of your operating system, which for Windows is UTF-16 and not UTF-8. This results in odd results like:

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/00bac644-a020-472d-9f98-338bd46f462e)

So to use Unicode characters in a translated string you have to do something like this:

`wxGetTranslation(wxString::FromUTF8(wxTRANSLATE("Delete Viewed “&Follow Up” Transactions...")))`

Honestly its simpler and cleaner to just use the normal `"` character...

**Comment by ovari** [comment]
> So to use Unicode characters in a translated string you have to do something like this:
> 
> `wxGetTranslation(wxString::FromUTF8(wxTRANSLATE("Delete Viewed “&Follow Up” Transactions...")))`

Thank you for the tip, done at https://github.com/moneymanagerex/moneymanagerex/pull/6749/commits/b15da266c0b855aa24b0de56353637405f9670dd

**Comment by n-stein** [comment]
@DevelopmentAnything are you still seeing the blank menus?

**Comment by DevelopmentAnything** [comment]
@n-stein 

![image](https://github.com/moneymanagerex/moneymanagerex/assets/110871727/bb7f7793-3d9e-4307-a107-6f42379b2da5)

It was just confirmed.
Don't have a **build number** in the compiled file name, so I didn't know it changed until now. I check it almost often, but...
