### ISSUE TITLE
Shouldn't paying Credit Card/Loan accounts via Transfer show up as Expenses?

### ISSUE THREAD

**Issue by Squaredude** [moneymanagerex/moneymanagerex#6812]
I would like to understand this concept.

I have a Credit Card account. I owe X amount of money and I pay every month from my Bank account. As per the suggestion in other issues here and forum threads, I must use a Transfer transaction to pass money from Bank to Credit Card.

The problem I see is, as MMEX's help text also points out, Transfers do not count towards the Income/Expenses calculations.

However, in my mind, that money that went out of my Bank account is no more, it has been expended, and it is part of the monthly expenses.

But MMEX does not show it that way. It shows Income as I expect it, but Expenses does not include the payment I just made to the Credit Card. Doesn't this skew charts down the line? When I'm looking at this data in 12 months from now, won't I have the wrong idea of what my Expenses were?

I hope someone can clarify this for me. I think part of the problem is that my brain is still stuck in my custom Excel spreadsheet, and MMEX just doesn't work that way. But it would be very helpful if someone could explain it.

**Comment by n-stein** [comment]
You are (or should be) recording the expenses directly in the credit card account as you use your card to make purchases.

Say you start the month with 0 balance.

Now you make a $100 purchase at the grocery store. You log the $100 withdrawal for "Food:Groceries" in the credit card account. 

Next you have a $200 bill from your power company that is paid with your credit card. You log a $200 withdrawal for "Bills:Electricity" in the credit card account.

These transactions are your expense transactions, the total of them is your spending for the month. Your credit account has -$300 in it (i.e. $300 worth of expenses).

At the end of the month you pay your credit card by transferring $300 from your checking account to the credit card account. You have already logged that $300 as expenses via the individual transactions in the credit card account. You don't want the bank transfer to also count as expense, otherwise it looks like you expended $600 this month ($300 in the credit account and $300 in the bank account).

Does that help?

**Comment by Squaredude** [comment]
Thank you very much for responding and giving me such a detailed explanation. It helped me understand the concept much better.

I did understand the idea of adding the expenses as Withdrawals in the Credit Card. My "problem", I realized halfway through your explanation, is that I added the debt all in one Withdrawal and as the months pass, this will not show up in each current month as I make the payments.

For this, I have to explain how it works in my country...

I'm not sure how it is elsewhere, but in my country, I can use my credit card or a loan to make a big purchase, and then pay it with installments (each month the same prearranged amount). In some cases, I have to add a specific amount of interests, and in other cases no interests are added.

So, for example, I buy a new TV at 500, but I get to pay it in 6 months: around 83.34 each month, and because this is a credit card with perks, I don't have to pay interests. I will be 500 in debt to the Credit Card, and each month, I will transfer 83.34 and be in less debt.

However, as we have said, Transfers are not shown in Expenses.

I guess, a way would be to schedule the transactions as Withdrawals in the Credit Card account, for the necessary months. But then the Credit Card will not show the total debt.

How would you go about this?
