### ISSUE TITLE
Enabling INT64 and SUID for MMEX4Desktop

### ISSUE THREAD

**Issue by whalley** [moneymanagerex/moneymanagerex#6966]
From: Lisheng Guan
 Hi there
 
 I'm writing this email to discuss enabling SUID for MMEX4Desktop to improve conflict resolution in the future.
 
 The proposal is to use SUID to fill the table's primary key instead. The SUID is composed of milliseconds and 3 random digits. 
 Once done, ID conflicts will be difficult. Then, merge and importers (both full and partial) would be possible. We can leverage data sync from the file level to the table/row level, and even column level.
 
 Here are two examples for Payee from mobile
 
```
 {
   "name" : "Payee A", 
   "website" : "www.payeeA.com",
   "id" : { 
     "value" : 1731396158462442
   },  
   "pattern" : "", 
   "categoryId" : { 
     "value" : 1731396158461053
   },  
   "number" : "123456",
   "notes" : "Frequent payee",
   "active" : false
 }
 
 {
   "categoryId" : { 
     "value" : -1
   },  
   "active" : true,
   "website" : "", 
   "number" : "", 
   "notes" : "", 
   "id" : { 
     "value" : 1731396213842905
   },  
   "pattern" : "", 
   "name" : "payee from android"
 }
```
 
 the change should be under control, here is some pseudo-code for table Tag_V1
 
 ```
--- a/src/db/DB_Table_Tag_V1.h
 +++ b/src/db/DB_Table_Tag_V1.h
 @@ -362,7 +362,7 @@ struct DB_Table_TAG_V1 : public DB_Table
          wxString sql = wxEmptyString;
          if (entity-id() <= 0) //  new & insert
          {
 -            sql = "INSERT INTO TAG_V1(TAGNAME, ACTIVE) VALUES(?, ?)";
 +            sql = "INSERT INTO TAG_V1(TAGNAME, ACTIVE, TAGID) VALUES(?, ?, ?)";
          }
          else
          {
 @@ -377,6 +377,8 @@ struct DB_Table_TAG_V1 : public DB_Table
              stmt.Bind(2, entity-ACTIVE);
              if (entity-id()  0)
                  stmt.Bind(3, entity-TAGID);
 +            else
 +                stmt.Bind(3, SUID());
 
              stmt.ExecuteUpdate();
              stmt.Finalize();
```
 
 
 
 Thoughts and feedback?

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/pull/6964
https://github.com/moneymanagerex/moneymanagerex/pull/6965

**Comment by georgeef** [comment]
For individual insert into the database, an SUID collision is almost impossible. However when many new entries are inserted in batch mode, an SUID collision is quite probable. For example if more than 1,000 new entries are inserted within the same ms, an SUID collision is certain.

This means that functions which insert new entries should better be tolerant to SUID collision, rather than assume that an SUID collision never happens.

## Proposal

The low-level insert functions should retry after a few ms if the new SUID already exists. In order to avoid a deadlock (due to bugs), there should be a limit in the number of trials, e.g., try two times and then either report an error or switch to automatic ROWID (selected by SQLite). The second alternative avoids propagation of errors by adding more complexity in the low-level functions, therefore the handling of SUID collisions is transparent to the rest of the code.

**Comment by guanlisheng** [comment]
The first step is to support SQLite3 Integer with Int64/wxLongLong

**Comment by whalley** [comment]
https://github.com/moneymanagerex/moneymanagerex/pull/6965

**Comment by whalley** [comment]
Caught a few more I think
