### ISSUE TITLE
Pre-loaded data translation

### ISSUE THREAD

**Issue by gabriele-v** [moneymanagerex/moneymanagerex#707]
- [ ] For "pre-loaded" categories/subcategories/currencies should be provided a translation during view.
  If user renames a pre-loaded entry, translation will be lost (that's fine).
- [ ] Provide same translation in GRM\SQL reports and standard reports
- [ ] In Currency table only CurrencyName, Unit_Name and Cent_Name must be translated, all other fields must not be into _() or wxTranslate() because resultant .po file it's really poor and unusable.
- [ ] Coordinate with Android team to provide the same fix in Android version & translations

Please make that changes or fix #704 because current behaviour it's wrong.

**Comment by gabriele-v** [comment]
@moneymanagerex/desktop-mmex-team Other suggestions are welcome

**Comment by vomikan** [comment]
What about to store translations in DB?

воскресенье, 14 февраля 2016 г. пользователь Gabriele-V написал:

**Comment by stef145g** [comment]
As for preloaded user data to the database on database creation, this should set in the language of the user. Additions or changes to the initial data set done by the user, will then match the user's language setting. As user data, I would not expect the program to modify my data added to the database.

The current language implementation for preloaded user data implemented prior to #704 was discovered to be wrong. The fix was also provided in #704 but was rejected.

**Comment by guanlisheng** [comment]
@gabriele-v please help to make the finally call here.

**Comment by vomikan** [comment]
I suggest to postpone this issue and return to it with v 2.0
