### ISSUE TITLE
YQL

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#713]
We need something like this
https://github.com/tforsberg/yql-yahoo-finance-wrapper/blob/master/ESGI.YahooFinance/Operations.cs

Related issues:
https://github.com/moneymanagerex/moneymanagerex/issues/647
https://github.com/moneymanagerex/android-money-manager-ex/issues/687

**Comment by guanlisheng** [comment]
@moneymanagerex/desktop-mmex-team  Any volunteer here?

**Comment by MisterY** [comment]
YQL has been unreliable for me lately. Sometimes the whole service is down.
The prices are also unreliable. The last known price, for example, for a host of Australian ETFs gets reset to the values as of June 9th approximately one hour after trading hours. This makes the values unusable if one is updating prices outside that window.
Hence I also added Morningstar as the price source. They don't have currencies so that's a drawback when updating currency exchange rates. One has to switch providers.
Just my $0.02.
