### ISSUE TITLE
Feature suggestion: Loans and Debts

### ISSUE THREAD

**Issue by CarloLucibello** [moneymanagerex/moneymanagerex#778]
Hi,
and thanks everyone for this nice open source software. 

There is thing I miss from mmex compared to other softwares I tried: the possibility to keep track of how much money you owe and to who, and viceversa. 

Bye, 
Carlo

**Comment by siena123** [comment]
If you enter your debts as an account with a negative initial balance you can keep track who and how much on the home page.

**Comment by CarloLucibello** [comment]
thanks @siena123, it kinda works, but is not as I like it. Let's say Alice rents an apartment to Bob, so each month Alice adds a withdrawal transaction in the Debts account, indicating Bob as payee. Then, when B actually gives the money to A, A adds a deposit transaction in the Debt account, so that he can keep an eye on the evolution of the debt. Also A can see the net debt of B in the Payee section, this is also nice. 

The annoying thing is that A would like the second transaction to figure out also into her main account, since she is actually cashing the money and this a source of her income. So she has to add another transaction in her main account. There is  an easier way to do this?

**Comment by siena123** [comment]
The way I have handled something similar is to have two databases one for each person. In one account I just do deposits and withdraws having payee being the name of the other person. In the other database I have an account with the other persons name which shows the debt between the two.

So in your case you outlined I would have databases Alice and Bob. In database Bob, I would just have normal deposit and withdraw transactions using Alice as the payee. in the Alice database, I would have an account for Bob and have normal withdraw payment from another (main) account showing the rent payment and do a transfer from the Bob account into the other (main) account showing the payment/income from Bob.

**Comment by stef145g** [comment]
@CarloLucibello, In the scenario you have pointed out I would create an account for **Bob** as the tenant, and an account for the **Apartment**. Set the account types to suit.

- Rent for the apartment would be a transfer from Apartment to Bob. Set up as an auto payment in repeating transactions for the rent. This is not registered as income or expense. 
- Payment from Bob would be a deposit in Bob - Registered as Income.
- Payment to Alice would be a transfer from Apartment to Savings Account. - Income already registered when Bob made the payment.

This has the benefit that if you spend money on the apartment, you can transfer money to the apartment, and pay maintenance bills from the Apartment account. This allows for the apartment expenses to be recorded. Set up categories to suit.

**Another Scenario:** We loan money to a friend.
- Create an account for the friend.
- Transfer money to the friend account. as the loan
- Transfer money back from friend when money is paid back to you.

The only thing we need to keep in mind here is that positive amounts in this Loan account, is money owing to you. Because we use transfers, they do not register as overall income or expenses.

**Comment by stef145g** [comment]
No further activity required. Closing this issue.
