### ISSUE TITLE
Methodology to check network connection status

### ISSUE THREAD

**Issue by guanlisheng** [moneymanagerex/moneymanagerex#843]
currently, the GA will black the program a while if there is no connection between MMEX and google server.

**Comment by vomikan** [comment]
I suggest to postpone this issue after 1.3 release

**Comment by gabriele-v** [comment]
Instead I think that this is really important and need to be solved before 1.3 GA. 

We cannot slow down all MMEX only for some stats..

**Comment by siena123** [comment]
The way to fix this would be to put the send stats in its own thread and let the main app continue. I put something quickly together (https://github.com/siena123/moneymanagerex/tree/issue-843) although it has one minor issue at the moment in that it reports a memory leak on shut down due to trying to send something on exiting which can be handled with some additional code but this should be enough for someone to test if it fixes the problem that people are seeing.

**Comment by slodki** [comment]
#938
