### ISSUE TITLE
[BUG] Asset interest calculation

### ISSUE THREAD

**Issue by RustyNomad** [moneymanagerex/moneymanagerex#846]
It seems like there might be an error in the interest calculation used in the Assets module. The interest calculated on MMEX comes out a little lower than my own calculations. Example:

a) Setup a new asset with following parameters: Initial balance of 1,000, Start date one year back i.e. 1 July 2015 (today is the 2nd of July 2016), Appreciation of 10%.
b) In the Assets window the Current Value for the above asset is shown as 1,100.57.

If I redo this calculation on a spreadsheet I get a balance of 1,106.06 up to the 2nd of July. If I do this calculation on a financial calculator I also get 1,106.06.

Not a major difference but if you increase the initial value of the asset to say 5,000,000 then the difference increases into the tens of thousands which will lead to a major discrepancy over a couple of years.

Windows 10
MMEX 1.3.0 Alpha (DB v.6)

**Comment by guanlisheng** [comment]
@stef145g how was everything going?

**Comment by siena123** [comment]
I have identified what is happening. First, MMEX is only compounding the interest once a year while from it appears from the numbers you give that you are compounded daily. Second, The time period you have in your example has the extra day from being a leap year. I did notice that MMEX has a slight error due to not handling this.

A quick calculation using your numbers (Initial Balance: 1,000; Appreciation: 10%) I get 1,105.16 after 1 year when compounded daily for a year (365 days) without accounting for the leap year. Would you mind sharing the spreadsheet with your calculations because even when I attempt to account for leap year I still don't come up with your values. I would like to reconcile what the difference is before making any changes as I likely have the slight error since your values matched with two different methods.

Note: This same issue also applies to depreciation values.

**Comment by siena123** [comment]
I was able to replicate your value of 1,106.06 by compounding 365 times per year and going out 368 days but I don't think that is what you are doing.

**Comment by stef145g** [comment]
Thanks James for the fix.
I was unable to replicate the values by @RustyNomad  but I can replicate the values by @siena123 (James) 
I now consider this closed unless someone else has more on this issue.
