### ISSUE TITLE
Make secure connection for web server

### ISSUE THREAD

**Issue by J316** [moneymanagerex/moneymanagerex#893]
The external access via web server should be protected with password

**Comment by guanlisheng** [comment]
Should be safe enough as it's in your own box.

**Comment by J316** [comment]
If you access from remote a secure protocol is needed

**Comment by J316** [comment]
@slodki It's not, a VPN cannot make an insecure communication secure, you still need SSL

**Comment by slodki** [comment]
And VPN adds the SSL to the connection.
Server is running on localhost, and VPN is securing link to the machine. If you not trust programs running on the target machine - adding https is worthless.

**Comment by slodki** [comment]
Can https be added to web server in MMEX?
We have client side https implemented already via libcurl in #1432 ...

**Comment by slodki** [comment]
https://cesanta.com/docs/http/ssl.html

**Comment by Rocketeer007** [comment]
For what it's worth, I don't think adding SSL to the web server in the MoneyManagerEx desktop application makes sense.  To do HTTPS properly, you need a certificate that matches the hostname, and which has been signed by a trusted source.  On a desktop application, the hostname would be the name of the user's PC - so every user would have to go out and generate their own certificate, and get it signed.

The more practical approach is to use a reverse proxy between the internet and your device, for example with Nginx or Apache.  There's a ton of tutorials out there on how to do this - just search "nginx ssl reverse proxy"

**Comment by Rocketeer007** [comment]
Honestly, you might be right if you’re just using one device.  However, if I want to access from a random device - my wife’s phone, an Internet cafe or whatever, having to manually install the certificate, or override the trust settings in chrome (etc.) is a pain in the backside.  

If you’re running MMEX on Linux, adding Nginx is trivial.
If you’re running on Windows, its unlikely that you’d have an internet facing IP, so you’d already have to have some mechanism to route from your public IP (i.e. your router) to the desktop PC.  If that’s simply port forwarding, then yes, adding a proxy is going to be tricky.  However, if you’re hosting anything more than just the one service, adding the reverse proxy is going to help out a lot long term.

**Comment by slodki** [comment]
letsencrypt.org certs are free and supported by all browsers/clients. It's easier to install additional file with cert then install, configure and manage (update, monitor etc.) additional software unknown to end user.

**Comment by Rocketeer007** [comment]
Agreed. However, it would be impossible to distribute a Let’s Encrypt certificate with the application as you don’t know the end user’s host name - and making MMEX support someone getting a new certificate would require supporting additional endpoints that are just used for host name authentication. 

I guess it’s *possible* to do it in MMEX... it just seems that using a reverse proxy is such a common solution that adding this would be of little benefit.

**Comment by J316** [comment]
Trusting a certificate from whatever device is a few seconds task, and as @slodki said there are open CAs, that's why even OpenWRT, pfSense and other security focused OSes use this method by default to grant remote access to a device. Both methods can be used on the same machine, I don't understand why bashing down a simple, secure and effective method just because it doesn't match your preference. HTTPS would be very beneficial to implement.

**Comment by Rocketeer007** [comment]
I'm not intentionally "bashing" a method - apologies if it's come across that way!

My starting point was simply that there is a simple and commonly used solution for providing HTTPS access to applications that don't natively support it (i.e. reverse proxy) which doesn't require much effort to install and use.  My assumption here was that anyone who's interested in having HTTPS access to the MMEX dashboard has probably similar things before, and woudn't be too upset at having to add an additional tool.

My second point was that it's not possible to distribute any useful certificates with the application, since you have no way to know the end user's hostname.  However, as @slodki rightly pointed out, it's quite easy to get a certificate for a host, and if we just assume the user already has the necessary certificates and keys, there's no reason this should prevent MMEX from supporting SSL.

I've got a proof-of-concept working now, since this is something that interests me a lot - even though it's not my first choice solution - so I'll share that on a feature branch shortly...

**Comment by gabriele-v** [comment]
Why we need to add HTTPS support to mmex?
Up to me it will just introduce more complexity that it's actually not needed at all:
why someone should need to see the dashboard (and just the dashboard actually) from outside?

Also, if it's introduced to support future functions in webserver, we should first consider how to deploy mmex as a service, because just keep it open is not a valid solution.

In case you want HTTPS, simply install a reverse proxy in the same network where you can do everything.

Instead, IMHO better to specify clearly that webserver is not needed for app usage, and enable it at your own risk because it could introduce weakness.

**Comment by gabriele-v** [comment]
Why add complexity and time to a feature that will be used by very few users (actually with just the dashboard up to me it's useless) when we have other tasks with higher priority?

**Comment by slodki** [comment]
Because some developer wants to work on it?
