### ISSUE TITLE
Https connection problem to web-money-manager-ex instance

### ISSUE THREAD

**Issue by okaufmann** [moneymanagerex/moneymanagerex#935]
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [ ] 1.3.x
  - [x] 1.2.7
  - [ ] 1.1 or older

Hi there

I just installed https://github.com/moneymanagerex/web-money-manager-ex on my hosting. Then I installed a new Let's encrypt ssl certificate and redirect all http requests to https with the following apache RewriteCondition in the .htaccess file:

```
# Force https
RewriteCond %{HTTPS} !=on
RewriteRule ^.*$ https://%{SERVER_NAME}%{REQUEST_URI} [R=301,L]
```

Back in MMEX i correct the server settings to the following:
![image](https://cloud.githubusercontent.com/assets/4414498/19784466/35a724fc-9c96-11e6-8bc4-68094f9a5ca2.png)

After a restart, when I try to import the data from the Web-Tool, this error appears:
![image](https://cloud.githubusercontent.com/assets/4414498/19784611/ab1cbc38-9c96-11e6-8db6-8b64da6d7930.png)

Seems MMEX ignores the https protocol and try to acces the Web-Tool via http and don't follow the redirect?

Maybe this have smth. to do with https://github.com/moneymanagerex/moneymanagerex/issues/893

I don't want my Data to be transferred unencrypted.

**Comment by okaufmann** [comment]
Just saw that https is explocit replaced by https in the web client under https://github.com/moneymanagerex/moneymanagerex/blob/2b9497172fd299731065b53407cbb6b8e44bf440/src/webapp.cpp#L36

For which reason this was done ?

**Comment by gabriele-v** [comment]
Hi, I'm the developer of WebApp: unfortunately problem is caused by old wxwidgets library to handle http connection from desktop app. 

In fact that library doesn't completely support HTTPS (if I remember correctly it has problems with POST calls). So, meanwhile we found a solution, I've choosen to make that trick of replace HTTPS with HTTP. 
I know it's tricky and unsecure, but unfortunately I haven't a better solution for now. 

Personally I've temporarily solved the problem disabling HTTP redirect to HTTPS and using WebApp from mobile in HTTPS (from mobile you can connect to open and unsecure networks where HTTPS its needed) and from desktop in HTTP (generally you import transactions when connected to your home network so quite secure).

I'll add a warning when saving options to notice about this.

**Comment by okaufmann** [comment]
@vomikan does it now support https to connect to the web client?

**Comment by slodki** [comment]
No IMHO - see sources [here](https://github.com/moneymanagerex/moneymanagerex/blob/fa27fff9eada83c5936fe5be1aca8fac1fd7095e/src/webapp.cpp#L36) and [here](https://github.com/moneymanagerex/moneymanagerex/blob/fa27fff9eada83c5936fe5be1aca8fac1fd7095e/src/webapp.cpp#L143).

@vomikan is this really fixed?

**Comment by slodki** [comment]
See https://cesanta.com/docs/http/ssl.html
