### ISSUE TITLE
support previous/next option for reports

### ISSUE THREAD

**Issue by guanlisheng** [moneymanagerex/moneymanagerex#990]
![snip20170105_16](https://cloud.githubusercontent.com/assets/721973/21676617/36615ef0-d371-11e6-94ee-2d5b21cad940.png)

**Comment by vomikan** [comment]
Do you mean the Next and Previous buttons for navigation?

**Comment by guanlisheng** [comment]
correct @vomikan

**Comment by vomikan** [comment]
test
https://github.com/vomikan/moneymanagerex/commit/ab8a3509f8763e4135c06dcaacf3cd062abb3563

**Comment by vomikan** [comment]
@siena123
James, what do you think about this feature?
I think it may be realized some stack with reports id or names and others parameters. 
If Prev/Next button pressed then proper report should be selected in navigation tree.

**Comment by siena123** [comment]
I just got a copy of your test and will take a look at it a little later.

If the plan is to to use just the reports showing in the navigation tree then there is no need for a separate stack, just use the navigation tree functions (GetNextSibling / GetPrevSibling, GetFirstChild / GetNextChild, etc.). That will be the easiest since the list is now sorted by name (Built in reports and GRM reports mixed together) and the built in reports can be hidden / removed from the tree list.
